### ISSUE TITLE
[Warrior] Charge

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1223]
Jimmy17
OP
 — 12/11/2022 10:19 AM
Charge pathing is wrong , shoudln't go straight line when the target is on highground.

Mitosis — 12/11/2022 10:22 AM
Additionally charge can go through terrain and force you out of bounds

**Comment by Greywolf59** [comment]
This is from TBC classic so not sure how relevant: https://www.youtube.com/watch?v=h54wj7U2oT4. Timestamp 1:03. It is quick but you can see it is not in a direct line.
I can also say that Charge acts as Jimmy said on Wotlk free server I played at AFTER they repaired it.
I will try to look for some more info/videos about this. I can also say that when I charged a mob under me, under a little hill, instead of running down the hill I basically jumped on his head which felt really really weird.

**Comment by UltraNix** [comment]
More info needed here - screenshots, spots, locations, etc

**Comment by Greywolf59** [comment]
3:39; 4:53 https://www.youtube.com/watch?v=snS5lZmjq1k&t=221s; watch the white line closely which occurs at the start of charge
Suffice to say it is really hard to find some legit Cata videos where it is clearly visible that charge/Intercept is not always a straight line As long as you keep LoS the charge is possible, problem is if you have one huge hill in front of you on which the enemy stands and on your right are three smaller hills on which you could most likely run/jump up to the enemy, charge should choose the 3 smaller hills as its path and not go just straight, often even under texture for a while, which often leds to falling under texture to your death. This is the same problem that I have seen on every free server so far. But I am not versed in cataclysm, if there was any change to this.

**Comment by UltraNix** [comment]
@Greywolf59 I mean locations/spots/screenshots of bugg from our server.

**Comment by Greywolf59** [comment]
Ah okay, will do. For now here are two videos how it look on wotlk elsewhere for further comaprison: https://files.fm/u/zmht74xs9

**Comment by Greywolf59** [comment]
@UltraNix Here you have it https://files.fm/u/6s3p5ndbf Charge should normaly go a bit to the left to choose a less steep part of the hill and prevent this from happening.

**Comment by UltraNix** [comment]
Should be fixed soon.

**Comment by UltraNix** [comment]
Fixed.
