### ISSUE TITLE
[Death Knight] Summon Gargoyle

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1238]
Jimmy17
OP
 — 12/11/2022 8:04 AM
Gargoyle should spawn high in the air , not on the ground

**Comment by Afgann** [comment]
fixed

**Comment by WhitemaneSylah** [comment]
More bugs on this one unfortunately Afgann,  see below

Icetomeetyou
OP
 — Today at 09:24
Due to the fact that I saw 4 bugs at once, it would be better if the developer himself checks this spell
And so the bugs:
1.) Spawn:
If you use a gargoyle near a tree, it can spawn on it (most likely on other surfaces that are above the character), this can create many unpleasant situations for both the dk himself and his opponents. Also, her landing itself looks strange ...
2.) Target change:
The gargoyle should instantly switch to the target the ghoul is hitting. In reality, this happens with a delay, I have to press the attack button 2 or 3 times for this to happen, also the debuff that marks the target as a gargoyle should also appear on its new target.
3.) Damage:
6k per hit in 406 gear...really? Check this out please, its something wrong here.
4.) Health: 
Im not sure, but Gargoyle health is low here, on any other pserver she had atleast 100k, ill try to find some proves if needed.

**Comment by UltraNix** [comment]
Fixed.

**Comment by APTX4869s** [comment]
There is a bug with Gargoyle at this moment
If you attack a dummy while having your pet ( raise dead ) assisting you, the Gargoyle won't cast anything and it just follows you around.
But if you attack a dummy without your pet ( raise dead ), the Gargoyle casts normally and does damage.

**Comment by UltraNix** [comment]
@APTX4869s Create a new report.
