### ISSUE TITLE
[PTR][Dungeon] shadowfang Keep Heroic lvl 85

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1375]
**How to reproduce:**
1. Commander Springvale missing mobs next to him at start of the fight "tormented officer" and " wailing guardsman" 
you can see them next to boss in this video : https://www.youtube.com/watch?v=pHVE48qkk28
2. Lord walden conjure poisonous mixture got issues after casting it, object follows the player around and also hits it in melee which is broken it should not happen.
3. Lord godfrey is doing pistol barrage in 120degree cone while it should be 60degree in front of him
also sometimes his animation bugs out and points forward but hits behind him
![image](https://user-images.githubusercontent.com/36106057/208914347-413cf560-fb1d-46df-90ad-e8a977315d76.png)
![image](https://user-images.githubusercontent.com/36106057/208915442-6b9d5c2e-c7c9-4f95-a493-b25bd93601eb.png)

also the event after finishing the boss is missing and dead bodies of the guards are keeping you in combat 
![image](https://user-images.githubusercontent.com/36106057/208916291-14d38f88-54f4-4a85-9850-fe1895d8c821.png)

**Comment by WhitemaneSylah** [comment]
More issues 
Waroxx — Today at 23:43
You get combat bug after 2nd boss - need to check with .debug hos what is causing it

**Comment by WhitemaneSylah** [comment]
<GM> Sylah — Today at 16:59
Trash packs seem to do less damage than intended, needs further testing

Baron Ashbury - Working fine

Baron Silverlaine - Working fine

Commander Springvale -  After a wipe it seems to cause issues with add spawns.  Tormented officers spawn in the ground after fight is engaged again after wipe.

Lord Walden - Ice shards OK
Conjure Poisonous Mixture - OK
Conjure Frost Mixture - OK
Toxic Coagulent - did not stack at all when players were not moving
Toxic Catalyst - OK

Lord Godfrey - Can be pulled outside of the boss room - This should cause a reset.
Pistol Barrage - Should point at a random player then cast Pistol Barrage in that direction in a 60 degree cone for 6 seconds, Instead he's facing a random player then using pistol barrage on the aggro target.

Warrior specific - WARRIORS CANNOT HEROIC LEAP ANYWHERE IN SFK 
Kinden — Today at 16:59
https://youtu.be/wRkb7WAj124 Tank PoV

**Comment by WhitemaneSylah** [comment]
Updated test 04.02 

BOSSES

Baron Ashbury -  has been seen to interrupt himself from casting Dark Archangel Form (93757) at 25%, THis then means he does NOT cast Calamity (93423) at this threshhold

Baron Silverlaine - No further action needed, scripted 100%

Commander Springvale 
Desecration (93687) does not deal damage fast enough,  It should hit every 1.5 seconds when within the area,  it is only doing damage every 3 seconds
Wailing Guardsman & Tormented Officers can spawn and run under the floor while hitting players making them untargetable. 

Lord Walden - No further action needed,  Scripted 100%

Lord Godfrey - Pistol Barrage(93520) damage is incorrect.  It should be 30k per second,  Currently it's doing between 38 and 52k per second,  Graphic error still exists but ability is functioning correctly 


ADDS
Spitebone Skeleton, Shadowy Attendant, haunted Servitor has been shown to fall under map,  potential pathing issue 
Kinden — Today at 19:48
^^EDIT:
Baron Ashbury: Dark Angel Form casts at 20% instead of its intended 25%, additionally if Baron Ashbury falls below the threshold to cast "Dark Angel Form" whilst Casting Asphyxiation, he interrupts himself casting any other spells and stands there dealing no damage. (repeatable by using excessive DPS at short notice).

Lord Godfrey - boss is pullable outside the boss room using Feral Fearie Fire, with no negatives. boss should reset/despawn if he crosses the door. 

https://youtu.be/pF0jwRY0Ih4 Tank PoV
[YouTube](https://www.youtube.com/)
[Commander Rug](https://www.youtube.com/channel/UC-Djnwt77ltERotKJicDM2g)
[Shadowfang Keep Run.](https://www.youtube.com/watch?v=pF0jwRY0Ih4)

**Comment by DjaouedBen** [comment]
Update/
- Adds called "Lesser Gargoyle" on the bridge before Lord Walden, these adds are casting fear on players, we had a situation where i got feared and i jumped out of the bridge on the right side, with no way back, Kinden just jumped and followed me right after that, we should have an invisible wall there to avoid this.

**Comment by DjaouedBen** [comment]
**UPDATE:**

- **Baron Ashbury:** Everything works perfectly now, except that the boss turns into a gigachat 50ft Undead on the last phase, shouldn't go that big
RP doesn't get activated after killing Baron Ashbury, so unable to continue the rest of the dungeon ( the npc that does the RP then opens the door is not summoned ) 

- **Baron Silverlaine:** Works perfectly
Trash after Baron Silverlaine is got undermap upstairs, but it didn't on second attempt for some reason.

- **Commander Springvale:** Adds who comes from the door got undermapped on first attempt, but came normally on second for some reason, everything else works perfectly.

Trash before Lord Waiden, called **Lesser Gargoyle** should cast more fears.
And we shouldn't be able to jump out of the bridge.

- **Lord Waiden:** Works perfectly, but still no RP after the boss, so the iron door remains closed

RP Before last boss **Lord Godfray** is missing, so the door of the last boss doesn't open.

- **Lord Godfray:** Pistol barrage cone is still bugged, that should be a 60°  V cone but you take damage even if you stay on the sides for some reason, the only way to avoid taking damage is to go behind the boss.

**HEROIC LEAP** still not working, it works normally in the beginning, then it stops working after **Baron Silverlaine** as soon as you get upstairs ( No path available )

**Comment by Commander-Rug090** [comment]
update: 
**Baron Asherby:**
 - Calamity causes boss to get very big.
 - adds on floor above get pulled. 

**Lord Walden:**
Toxic Catalyst does no damage

**Lord Godfrey:**
 - can be pulled outside of room. 
 - pistol barrage completely visually broken. 
 - ghouls summoned with "summon bloodthirsty ghouls" ability do not move, just stand there and die.

**Comment by Afgann** [comment]
fixed
