### ISSUE TITLE
[PTR][Dungeon] Deadmines Heroic lvl 85

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1376]
[**How to reproduce:**
1. Glubtok is not using his blink ability at all also damages of fires wall around him on second phase is inconsistent sometimes does 50k+ 2-3 times back to back and cause players to die instantly that should not happen it should be per sec
![image](https://user-images.githubusercontent.com/36106057/212217723-31e7f9f7-6a00-4785-abdd-4535cbfd920f.png)

2. olaf smash should take away 60% of your hp on heroic and it does no damage
his grab is not working properly sometimes he doesnt grab anything just does the move after killing the olaf helix didnt cast leap to jump on people, he didnt cast heli'x cew as well adding 4 additional members to the guys that drop bombs ( 8 crew members in total)
also this https://github.com/gamefreedomgit/Maelstrom/issues/1869
3. During vanessa vancleef event fires should not be attackable, also looks like jumping through them makes you to not take damage, might be related to the parachute that we get on cauldron and on next area worgons were not fighting humans
![image](https://user-images.githubusercontent.com/36106057/208922962-665dff86-d128-4faa-9d7c-a675cc851fa3.png)
also in this event ship is not on fire at all, fire should get more and more over time and with explosion, there are some animation bugs with rope usage as well,
you can see the whole fight here it should work like the video below.
https://www.youtube.com/watch?v=tkNxQ176Bhs
4. spell harvest on foe reaper 5000 hitting you behind the boss as well by the look of it
5. blackspots where cannons hit on last area don't have a black spot it should be visible for the players (i could only see them with gm on) https://youtu.be/5JuLT_qkGRg?t=419
![image](https://user-images.githubusercontent.com/36106057/212212296-94c7575e-8ade-4edb-b5ba-a876966b7696.png)

**Comment by WhitemaneSylah** [comment]
Initiation : 
Members of Horde can phase into alliance version of DM meaing they're attacked by level 20 quest givers,  Vice verse for Alliance being able to phase into horde version

Furnace room : Players can see the arrows pointing to the steam vents 

Glubtok:

Phase 1 - Still does not use blink

Phase 2 - Fire Blossom and Frost Blossom are being used very quickly on Heroic. 4-5 are being shot at once , should only be 1-2 per use 

After glubtok:  Mining monkeys have no chain to click thus always neutral/hostile 
Mining bunnies - Motivation hits far too hard.  Should only hit 3k per hit , doing 10k per hit at the moment- They're not dropping refreshments either (clickable buff)

Helix: Bombs are dropping to frequently,  should be dropped once every 5-10 seconds.  Priest somehow cannot cast renew on anyone if they haven't been picked up by Oaf smash.  Helix also does not jump to anyone in this phase
Phase 2 - Helix still does not jump to anyone

Foe Reaver:  Harvest seems to focus on the aggro target instead of being used infront of him

Admiral Ripsnarl:  The fog does not stop because Ripsnarl never uses Go for the throat.  This should be used every 10-15 seconds 

"Captain" Cookie : Scripting is fine,  but does use Rotten food more than fresh food,  should be equal preference 

Vanessa VanCleef :  CRITICAL - WHEN WIPING ON AANY OF THE NIGHTMARES THE FIGHT BREAKS AND CANNOT BE RESTARTED. 
Rope visual is a bit jarring, should be smooth.

**Comment by WhitemaneSylah** [comment]
Kinden — Today at 15:24
https://youtu.be/0EXxskikxRY
Videos from retail
https://www.youtube.com/watch?v=8eWPQgz432w
https://www.youtube.com/watch?v=5JuLT_qkGRg

**Comment by sadgh05t** [comment]
After the platform fix deadmines are undoable. The mobs and all of the bosses that are on the ship fall trough the textures.
![image](https://user-images.githubusercontent.com/35288643/215287068-d39da812-53f3-4387-83ac-7bf59eb28f48.png)

**Comment by MrTide** [comment]
Update: Test run on  — 02/12/2023
----------------------------------------------

Global issue: all dungeons appear to be throwing players into Alliance instances? might be linked to Tol barad victory? changing ownership of Tol barad has no change to instances. everyone is locked to alliance sided instances. 

Glubtrok: 
Blink does not work. he does not blink to another player after either "Fists of fire" or "Fists of frost" wears off. 
Second Phase starts at the right amount of health, the fire line is now the correct speed and damage, however too many adds are spawning, "fire blossom" and "Frost Blossom" should be alternating, instead they are coming up together, resulting in too many adds. 

Olaf: 
getting the "Rat Pack" achievement (kill 20 rats during the fight) cause full instance crash. Critical error

trash before Foe Reapoer 5000 boss:
Defias Reapers do not clear DoT's after they become friendly resulting in them dieing before you can use them to dps the boss. 

Foe Reaper 5000:
aggro table is fucked, tank cannot taunt. at any part of the fight. (even though they appear to have aggro boss will continue to attack another target (see video for more info got to 1:08:00 on video linked)

pre-Venessa phasing:
is much improved- however in the first room, several players phase out from everyone else and slowly come together overtime. 
additionally the lightning sparks that spin and do damage, once the "disappear" they still remain with parachutes and can damage players that get too close (see video for more info). 

Venessa Vancleef:
after the first "Fiery blaze" Venessa will stand in the middle of the deck and do nothing, she wont damage, auto-attack or move. this could be linked to her 50% threshold changing her abilities.

https://youtu.be/bCuNLel64y4 tank PoV

**Comment by UltraNix** [comment]
Fixed.

**Comment by Commander-Rug090** [comment]
Glubtrok:
in the second phase Fire wall is hard to see on the ground, looks half sunk into the textures? 
too many adds are spawning, "fire blossom" and "Frost Blossom" should be alternating, instead they are coming up together, resulting in too many adds. - as above.  

Foe Reaper: 
Harvest: does damage correctly but doesn't target a random players location instead stays with it current aggro target (ie the tank)

Admiral Ripsnarl: 
although the fog on the ground disappears now, the players still have the "fog" effect around the edges of their screen. during the whole encounter, disapears when ripsnarl dies. 
the "Vapor" enemies simply disappear when ripsnarl re-appers from the smoke, they should persist through both phases. 

Vancleef: 
minor bug: the audio of her yell to grab the ropes is not audible. she appears to vanish instead of standing in the middle
of the deck
