### ISSUE TITLE
[Moved from discord] All Ret Paladin issues "abilities and gear"

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1431]
liljon
OP
 — 12/15/2022 8:29 PM
What this includes: All talents usable by Rets, PvP set bonus, PvP gloves bonus, T11 set.
What this doesn't include: Glyphs (although they seem to be airtight), scalings while leveling - all testing was done at lvl85.

Pursuit of Justice gives holy power even if you are immune to certain CC effects - for example, if you are immune to roots due to DR, Freedom, or one of your immunities, you still generate a Holy Power. You also generate HP on conditional stuns, such as Holy Wrath, which shouldn't stun Humanoid targets, but you do get a Holy Power.

Divine Purpose can proc from Divine Storm or Holy Wrath even when not in combat, or without any targets being hit. Based on the tooltip, this should be accurate, but I am pretty sure this is not intended.

PvP Gloves only increases the lower end damage of Crusader Strike by 5% - essentially, it makes your Crusader Strike more consistent, but not actually stronger raw damage wise. I've done a lot of digging into this, as this has been around in Wrath (and I believe Mists and WoD as well), and there isn't an official confirmation anywhere that this is a bug, but from talking to several long time Paladin players who play on Wrath Classic currently, they all argue that only boosting the lower end damage is a bug - in fact, Wrath Classic has issues like that on it's own with other talents, such as Improved SoR. If we go by the tooltip purely, the raw damage should be increased. 5% damage on a main rotational ability is quite a bit to miss out on, and this affects both Prot AND Ret.

Edit: After extensive testing, compared with the T11 2 set bonus, which claims to boost TV damage by 10%, T11 does actually boost the overall damage. Using gear with the same strength value, without the 2set, my high end no-crit no-modifier TV is roughly 28.6k. With the 2 set, it is roughly 31.5k. Running it in a calculator, 28.6*1.1=31.46, meaning it lines up precisely with what you'd expect. You don't get the same benefit from the PvP gloves though, despite both having similar tooltips.

2 set: Increases the damage done by your Templar's Verdict ability by 10%.
PvP gloves: Increases the damage dealt by your Crusader Strike ability by 5%.

Despite this, one of them is not like the other.

Edit2: I realize I forgot to attach CS numbers. Using gear with the same strength, and removing all variance and crits, low end CS is 12.4k without gloves, and 13k with the gloves, whereas the high end in both cases is 15.1k. 
liljon
OP
 — 12/15/2022 9:02 PM
Also, the Exorcism issue talked about in the Hpally post affects Ret as well (copy paste: Exorcism has a 6 second cooldown and causes a GCD to occur when hardcasted. The GCD can be circumvented if you start casting another spell / instantcast on the same batch as the casted exorcism lands, but if you dont you have to sit an entire GCD.)

**Comment by UltraNix** [comment]
`Pursuit of Justice gives holy power even if you are immune to certain CC effects - for example, if you are immune to roots due to DR, Freedom, or one of your immunities, you still generate a Holy Power. You also generate HP on conditional stuns, such as Holy Wrath, which shouldn't stun Humanoid targets, but you do get a Holy Power.`
Already fixed.

`Divine Purpose can proc from Divine Storm or Holy Wrath even when not in combat, or without any targets being hit. Based on the tooltip, this should be accurate, but I am pretty sure this is not intended.`
Yes - this is intended.

`PvP Gloves only increases the lower end damage of Crusader Strike by 5% - essentially, it makes your Crusader Strike more consistent, but not actually stronger raw damage wise. I've done a lot of digging into this, as this has been around in Wrath (and I believe Mists and WoD as well), and there isn't an official confirmation anywhere that this is a bug, but from talking to several long time Paladin players who play on Wrath Classic currently, they all argue that only boosting the lower end damage is a bug - in fact, Wrath Classic has issues like that on it's own with other talents, such as Improved SoR. If we go by the tooltip purely, the raw damage should be increased. 5% damage on a main rotational ability is quite a bit to miss out on, and this affects both Prot AND Ret.

Edit: After extensive testing, compared with the T11 2 set bonus, which claims to boost TV damage by 10%, T11 does actually boost the overall damage. Using gear with the same strength value, without the 2set, my high end no-crit no-modifier TV is roughly 28.6k. With the 2 set, it is roughly 31.5k. Running it in a calculator, 28.6*1.1=31.46, meaning it lines up precisely with what you'd expect. You don't get the same benefit from the PvP gloves though, despite both having similar tooltips.

2 set: Increases the damage done by your Templar's Verdict ability by 10%.
PvP gloves: Increases the damage dealt by your Crusader Strike ability by 5%.

Despite this, one of them is not like the other.

Edit2: I realize I forgot to attach CS numbers. Using gear with the same strength, and removing all variance and crits, low end CS is 12.4k without gloves, and 13k with the gloves, whereas the high end in both cases is 15.1k.`

W/o gloves
![WoWScrnShot_122722_113727](https://user-images.githubusercontent.com/80540499/209654495-9bf37949-db99-444e-9258-d4990829f391.jpg)

With gloves:
![WoWScrnShot_122722_114023](https://user-images.githubusercontent.com/80540499/209654527-4de03386-942f-4fcd-8ac0-425b3b3eb093.jpg)
Damage is increased by 5% correctly.

No bugs in this report.
