### ISSUE TITLE
[Moved from discord] All Holy Paladin issues "Abilities and talents"

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1432]
liljon
OP
 — 12/15/2022 7:05 PM
What this includes: All talents usable by Holies, PvP set bonus, PvP gloves bonus, T11 set.
What this doesn't include: Glyphs (although they seem to be airtight), scalings while leveling - all testing was done at lvl85.

Exorcism has a 6 second cooldown and causes a GCD to occur when hardcasted. The GCD can be circumvented if you start casting another spell / instantcast on the same batch as the casted exorcism lands, but if you dont you have to sit an entire GCD.

2/2 Enlightened Judgment only increases the healing of Judgment by a couple hundred, instead of doubling it. The heal also seems to be incapable of critting (with 16% crit, after casting it 80 times, Enlightened Judgment never once critted).

Light of Dawn triggers Protector of the Innocent despite not being a targeted heal.

Aura Mastery doesn't properly double the effect of Retribution Aura, it only has a 1.25 multiplier instead of a 2.0.

Denounce crit debuff does not work (tested against a guaranteed crit Lava Burst, Denounce should have priority).

Guardian Angel's 10% spread healing heals enemies (tested in a duel against a Horde target, might be a result of cross faction?).

Pursuit of Justice gives holy power even if you are immune to certain CC effects - for example, if you are immune to roots due to DR, Freedom, or one of your immunities, you still generate a Holy Power. You also generate HP on conditional stuns, such as Holy Wrath, which shouldn't stun Humanoid targets, but you do get a Holy Power.

**Comment by UltraNix** [comment]
`Light of Dawn triggers Protector of the Innocent despite not being a targeted heal.`
Works okay.

`Aura Mastery doesn't properly double the effect of Retribution Aura, it only has a 1.25 multiplier instead of a 2.0.`
![WoWScrnShot_122722_122305](https://user-images.githubusercontent.com/80540499/209659645-9b3c4def-2343-4999-a72f-529c477df5e0.jpg)

![WoWScrnShot_122722_122427](https://user-images.githubusercontent.com/80540499/209659726-c1eeac86-bfcf-4113-9a76-fc6dba68afae.jpg)

Works okay.

`Denounce crit debuff does not work (tested against a guaranteed crit Lava Burst, Denounce should have priority).`
This spells works okay. I have found no proofs that it should have higher prio than Lava Burst with Flame Shock.

`Guardian Angel's 10% spread healing heals enemies (tested in a duel against a Horde target, might be a result of cross faction?).`
Works okay.

**Comment by UltraNix** [comment]
Fixed.

**Comment by WhitemaneSylah** [comment]
Issue still present

**Comment by UltraNix** [comment]
@WhitemaneSylah Please, record video of this.

**Comment by WhitemaneSylah** [comment]
@UltraNix  was resolved as part of #1567, Close when ready
