### ISSUE TITLE
[WIP] Eastern Plaguelands Alliance Levelling Report

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1461]
https://www.youtube.com/watch?v=1FecsOh-rP8&list=PLBTW52IZwY7fGGm0zvw9-wyEVbOLTx2Re

1. [Fiona's Caravan](https://www.wowhead.com/npc=45400/fionas-caravan) is dead.

2. Foina's Caravan is missing [Preston](https://www.wowhead.com/npc=45433/preston) and [Argyle](https://www.wowhead.com/npc=45434/argyle) when it stands on its stops.

3. List of buffs offered by the Caravan is somewhat buggy and a bit out of order. You can gt certain buffs before you manage to get the person linked to it join the caravan. Most notably [Beezil's Cog](https://www.wowhead.com/spell=85619/beezils-cog) is avialable already in the very first camp at the river. Playe just needs to choose some other buff and talk to the  caravana again and Cog will be available.

4. I do not know to whcih this is conencted but lot of NPCs in EP hav yellow names from afar so they seem neutral. If you get close to them to see their HP or if you target them, the proper color (green, yellow, red) will appear. I have no idea by what this is caused and it seems this problem dissipates and returns. It might be a problem caused by travelling in the caravan. EDIT: It is indeed connected to travelling by the caravan.

5. I haven't noticed [Death's Step Miscreations](https://www.wowhead.com/npc=45444/deaths-step-miscreation#abilities) using their abilities.

6. I am not sure if Fiona does her /say after you hand in A [Gift for Fiona](https://www.wowhead.com/quest=27372/a-gift-for-fiona) and [Greasing the Wheels](https://www.wowhead.com/quest=27369/greasing-the-wheel).
- video: 14:30 https://www.youtube.com/watch?v=1FecsOh-rP8&list=PLBTW52IZwY7fGGm0zvw9-wyEVbOLTx2Re

7. [Gidwin Goldbraid](https://cata-twinhead.twinstar.cz/?npc=45677) (not sure if right ID) talks but is not visible during the caravan travel during quest [Onward, to the Light's Hope Chapel](https://www.wowhead.com/quest=27373/onward-to-lights-hope-chapel).
Same video a few seconds later.

8. [The Trek Continues](https://www.wowhead.com/quest=27448/the-trek-continues)
- During the Caravan ride, the player and [Tarenar Sunstrike](https://www.wowhead.com/npc=45678/tarenar-sunstrike) (not sure if right ID) are not seated correctly (180 degrees).
- Player also gets into combat when the caravan starts to move and leaves the combat when he leaves it at the second tower.

9. [Boys Will be Boys](https://www.wowhead.com/quest=27455/boys-will-be-boys)
- When player accepts this quest, Fiona nad the Caravan disappears, which should not happen.
- Fiona and the caravan appears again after you take or finish some other quest at the tower (no clue which), but she should not disappear at all.

10. [To Kill With Purpose](https://www.wowhead.com/quest=27451/to-kill-with-purpose)
- should be handed in via comm
- video: 4:40 https://www.youtube.com/watch?v=NjUfVIqTtGs&list=PLBTW52IZwY7fGGm0zvw9-wyEVbOLTx2Re&index=3

11. [Dark Garb](https://www.wowhead.com/quest=27452/dark-garb)
- should be handed in via comm
- same video as above, 5:15

12. [Catalysm](https://www.wowhead.com/quest=27453/catalysm)
- should be offered via comm after both Dark Garb and To Kill with Purpose are handed in.
- same video as above, 5:20

13. [Pamela's Doll](https://www.wowhead.com/quest=27384/pamelas-doll)
- parts of the doll can be looted from [Ghosts of the Past](https://www.wowhead.com/npc=10940/ghost-of-the-past).
- wowhead comments on both links do not mention it should be possible to loot it from the ghosts, actually they mention problems with finding all three parts.

14. [The Battle of Darrowshire](https://www.wowhead.com/quest=27390/the-battle-of-darrowshire)
- When you talk to [Joseph Redpath](https://www.wowhead.com/npc=10936/joseph-redpath) he only says greetings in gossip.
- His gossip should say what is written here at 5:14 https://www.youtube.com/watch?v=AZ-ycmRqKog
- there might be an event missing unless they removed that part with Cataclysm. Redpath should go talk to Pamela at least it was so in pre-cata version of the quest. https://wowpedia.fandom.com/wiki/The_Battle_of_Darrowshire_(quest)#Notes

15. [Garginox](https://www.wowhead.com/npc=45681/garginox) should patrol around the Glade. Instead he stands on the spot.

16. [Argent Upheaval](https://www.wowhead.com/quest=27618/argent-upheaval)
- This quest should be avaialble only after you finish all appropraite quests: Scarlet Salvage, The Wrathcaster, The Huntsman, The Commander
- At the moment quest is also available if you hand in only [Scarlet Salvage](https://www.wowhead.com/quest=27614/scarlet-salvage)
- If you hand in another quest of the 3 left, the Upheaval disappears again and is avaialble only after you hand in all four pre-quests as it should be.

17. [Victory from Within](https://www.wowhead.com/quest=27612/victory-from-within)
- There should be friendly NPC coming out of the portal when you click it.
- This does not happen on PTR, no npcs spawning.
- Video: https://www.youtube.com/watch?v=2Ivc54ieQZY

18. [An Opportune Alliance](https://www.wowhead.com/quest=27457/an-opportune-alliance)
- After you hand in this quest [Fiona](https://www.wowhead.com/npc=45417/fiona) and her caravan disappears until you leave the Eastwall Tower zone and come back again. This should not happen.

19. [Ix'lar the Underlord](https://www.wowhead.com/quest=27487/ixlar-the-underlord)
- On this quest Tarenar Sunstrike should join you (no clue which ID). He does not.
- [Ix'lar the Underlord](https://www.wowhead.com/npc=45744/ixlar-the-underlord) is not using his abilities.

20. Quel'lithien Lodge NPCs
- All the NPCs in this zone seem to have major issues, although they count towards the quest they are objective of
- All the NPCs are missing "Wretched" part of their names. [Woodsman](https://cata-twinhead.twinstar.cz/?npc=8563), [Ranger](https://cata-twinhead.twinstar.cz/?npc=8564), [Pathstrider](https://cata-twinhead.twinstar.cz/?npc=8565)
- Almost all the NPCs have sleeping icon above them, some standing, most of them laying. It should not be this way.
- The laying NPCs won't get up to fight you, they stay on the ground even when they move.
- https://www.youtube.com/watch?v=iZ16JJ4egjs

21. [Beat it Out of Them](https://www.wowhead.com/quest=27522/beat-it-out-of-them)
- This quest needs higher chance to get credit for "Discover Gidwin's Location" (The Plaguewood is too big! Your friend is gone! You will never find him!)
- All the videos I have seen get both the answers within max 10 kills. I have cleared every [Engineer](https://www.wowhead.com/npc=17878/scourge-siege-engineer) but never got Location out of them. On the other hand I got the Captor credit multiple times.

22. [The Baroness' Missive](https://www.wowhead.com/quest=27551/the-baroness-missive)
- When you hand in this quest, [Tarenar Sunstrike](https://www.wowhead.com/npc=45729/tarenar-sunstrike) disappears and player has to log out or leave the Plaguewoods zone and come back to make him appear again and take the next quest.

23. [A Crazy Grab Bag](https://www.wowhead.com/item=15902/a-crazy-grab-bag)
- It was empty, with message "This slot is empty" or something like that. I do believe it should always contain one uncommon item.

24. [Large Termite Mound](https://www.wowhead.com/object=177464/large-termite-mound)
- According to [Wowpedia](https://wowpedia.fandom.com/wiki/Large_Termite_Mound), this object was removed with Cata. I have found at least two I could interact with still.

**Comment by Greywolf59** [comment]
I will continue and finish this report when https://github.com/gamefreedomgit/Maelstrom/issues/1466 gets fixed.

**Comment by MrTide** [comment]
Thanks for your hard work on this report greywolf59
i will highlight the major issues in this report so developers and pick and choose what to fix or pass on here depending on the time available to them
**i will embolden the font of the issues that require fixes sooner than later.**
1. nothing major but player is right
2. can confirm
3. correct but nothing major up to developers
4. most creatures in this area are beasts and not hostile i believe thats intended behavior but still we need specific names to check them
**5. correct they are missing their abilities**
6. Can confirm nothing major up to developers
7. can confirm
8. nothing major but player is correct
9. i believe this is phasing issue and related to the quest itself you need to turn it in first in order to  make the caravan appear again i would assume its done to make sure players don't skip the quest and most likely intended behavior
10.11,12 i believe these guys were testing it on Beta version of cataclysm probably later on it changed, also multiple databases showing it that you need to turn it in (requires more data) still nothing major
13. true but nothing major
14. true but i believe they shortened everything on purpose later on. nothing major
15.  true its pathing is also provided in the link image
16. I don't think this is correct cataclysm database says otherwise 
to the baracks opens up a lot of quests which what you suggested is one of them
being in a series doesn't necessarily means requirements, sometimes some quests are optional 
![image](https://user-images.githubusercontent.com/36106057/210087880-6090485a-41c7-424d-b943-997e0ae291a2.png)
![image](https://user-images.githubusercontent.com/36106057/210088010-fc6b18c3-47d1-4dc2-8bae-d9db85a1b644.png)
17. can confirm
**18. can confirm requires attention**
**19. can confirm he is missing his abilities** 
**20. can confirm they require attention**
21. can be improved but still doable
**22. after accepting the quest blind fury npc phases in but after accepting the quest after that in that story line which is a offered by an drop item phases him out that should not happen.** 
![image](https://user-images.githubusercontent.com/36106057/210090364-f4f28652-5945-468b-97f0-d8160fdc82bb.png)
**23. can confirm** 
**![image](https://user-images.githubusercontent.com/36106057/210090483-63265bbc-e23e-47f4-9073-e7968877eeab.png)**
**24. can confirm**

**Comment by Greywolf59** [comment]
Nice work, thank you for putting your time into this. Just a note to point 16.: the Argent Upheaval flavour text says:
I'll say we've done enough damage to these barracks to call this a win. **A commander, a huntsman, and a warlock, all slain...** not to mention the relics that we've liberated. Or shall I say... YOU liberated.

The cathedral still remains, but not for long. Talk with [Archmage Angela Dosantos](https://www.wowhead.com/npc=16116/archmage-angela-dosantos), in the central courtyard. The fate of Tyr's Hand's cathedral falls in her able hands.

That would logically mean the player killed all those mentioned npc and got the relics (thus done all the available prequests) before he was handed this quest.

**Comment by UltraNix** [comment]
Fixed.
