### ISSUE TITLE
[Death Knight ZONE][Quest][Taking Back Acherus]

### ISSUE THREAD

**Issue by Orcmage** [gamefreedomgit/Maelstrom#1514]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After accepting this quest, you use Death Gate to go complete but you end up in a phased empty Acherus, making this a dead end.

**How to reproduce:**
Use Death Gate after picking up the spell.

**How it should work:**
https://www.youtube.com/watch?v=nLG1fM1mrO0

**Database links:**
/?quest=13165
/?spell=50977

**Comment by UltraNix** [comment]
Already fixed.

**Comment by sadgh05t** [comment]
@UltraNix Hello the issue still persists

**Comment by sadgh05t** [comment]
Here is the temporary solution from @Vasquea in discord


I found away around this bug due to being on ptr but it would not fix it for live

If you .skip to gm island teleport to org and get zep back to other island

get on a flight point to the ebon hold and it loads right version it death gate bringing you to wrong one.

You have to do this every time you want to go back so spawn all weps u need and do runeforging once
