### ISSUE TITLE
[Moved from Discord][Zone: Elwynn Forest] Sound issue with wolves 

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1577]
Icetomeetyou
OP
 — Today at 09:53
Being in the Elwynn Forest, you can often hear the howl of a wolf, I thought it was ambient, but the howl was too loud and its volume was not changed by adjusting the ambient sound option. It sounds like the howl of an NPC wolf, which is very close, but the sound can sound anywhere and anytime, even if no one is around, a rather loud and annoying sound. While leveling my paladin, I was annoyed by this.  The sound varies, about 3 variations, also they are interrupted after about a second, which is unpleasant

**Comment by Greywolf59** [comment]
I can confirm I have found the howling a bit weird too. Might have been the same in Dun Morogh too but I haven't spent so much time in there.

**Comment by Soylenin** [comment]
This howl occurs in Coldridge Valley as well.

Track seems unaffected by any of the available sliders under "sound" tab, but appears to be part of the ambient loop. Incredibly loud and distracting.

Unsure if this occurs exclusively at night.

Imgur link because 10MB video limit omegalul: https://imgur.com/a/cyeLRav

**Comment by UltraNix** [comment]
I don't if we can do something about it. It's rather client than server.
