### ISSUE TITLE
[Raid] Blackwing Decent issue list

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1644]
Trash in general falls through the floor

Omnotron Defense System -  Fight not functioning at all,  NPCs phase through the floor
https://www.youtube.com/watch?v=4VCqjH5hMGg

Magmaw - Fight is scripted but head has graphical glitch where it disappears for no reason,  NPCS at start also phase through the floor
https://www.youtube.com/watch?v=l2QSQf3I_0M

Chimaeron - Fight is scripted however caustic slime occurs before mixture is applied resulting in instant deaths - On death Chimaeron also fell through the floor meaning no loot was obtainable 
https://www.youtube.com/watch?v=Jqcf5BsyrE8

Atramedes - Fight cannot be started
https://www.youtube.com/watch?v=jb3pY1Vmd9o

Maloriak not tested - should function like this https://www.youtube.com/watch?v=8sFFqH2Rx44

Nefarian's end untested - https://www.youtube.com/watch?v=uxENd1Hamas

**Comment by Dechuka** [comment]
**1- Omnotron Defense System**
* Arcanotron : spell stealing _Converted Power_ does not show a buff or on the player and the effect is way longer than should be and it reduces haste instead of increasing it.

*[Magmatron] : Acquiring Target : does not deal damage.

https://wowpedia.fandom.com/wiki/Omnotron_Defense_System#Abilities

2- Magmaw 
*Massive Crash : does not work
https://wowpedia.fandom.com/wiki/Magmaw

* Point of Vulnerability : Raid members should be able to attack Magmaw exposed head, and Magmaw should receive 100% more damage from raid members

https://www.wowhead.com/spell=79010/point-of-vulnerability

**Comment by sadgh05t** [comment]
Tested in 10 man normal on 01.17.2023
Omnotron defense system :
The tank threat was not building at all any healer cast or dps burst was doing more aggro than tank with full vengeance ( you need always use taunt and overgear to clear this fight )

Magmaw
When you charge it with warrior or use killing spree with rogue you are falling into the lava and dying. ( seems like the feral charge does the same but we did not test it )
When he is using mangle on the tank and releasing you after he took the needed amount of  damage you are slowly falling to the lava ( for about 7 seconds ) and then you are teleported to the middle of the boss arena
Lava parasite is not applying Parasitic Infection debuff

Atramedes
When you are pulling him for the first time after he melts the bell he falls under the ground and continues the fight beeing underground ( we tried to come to the edge of the platform and various other ways to debug it but nothing worked)
Some gongs are not working properly and bugged with not possible to click on them
The roaring flame breath speed is wrong

Chimaeron 
During stage 2 he does an extremely low amount of damage to the tank 

Maloriak
Stage 2 is bugged 

Nefarian's end
The lava does not disappear during the onyxia encounter, even after killing her nefarian does not fly down

Might need an update on this one in case I missed something

https://cata-twinhead.twinstar.cz/?zone=5094

**Comment by WhitemaneSylah** [comment]
Update from 17.01 from tester team
----------------------------------------
Magmaw - Parasites should target their attacker ( so they should target hunter for example if he uses immolation trap + multi shot on them ) and they went under the ground once
---------------------------------------- 
Atramedes- We used 4 gongs but we had 8 used gonks at the end ( that should be in heroic only )
----------------------------------------
Nefarian - Not scripted.
---------------------------------------- 
@Hotandspicy for Atra, "sonar pulse - is giving too less sound - its only giving 3"
That's how it should be, it gives 3 in normal and 7 in heroic

**Comment by WhitemaneSylah** [comment]
Tester run 05/02 
Kinden — Today at 20:03
Leap of Faith dropping players that are gripped right as they try to walk out through raid portal. (just Currela things)

some of the starting adds for Magmaw are under the map. (first group by the door)

Adds by the door of Omnitron are spawning the red AoE's twice as often as they should. 

"Drakonid Drudge" Blade Scythe attack hitting behind the model instead of in front. 

Magmaw:players are immune to Renew, possibly tied to the casting of an ability or boss mechanic? 
Charging the boss throws the player into the abyss.
Massive Crash not working, animation is there but some players reported that they didn't get stunned or hit, might be range problem (if standing too close/far) or maximum amount of players hit? 

Omnitron: bosses health pool are not shared, because of this if one of the "Tron's" dies then it will stop the rotation, open the door and bug the boss. no loot. but can move on. 
Arcanotron: Power generator can target other "tron's" instead of players. 
Electron: Lightning conductor range is too small, should be 8 yards, instead it is 4.
Magmatron: Acquiring Target follows but doesn't update Flamethrower with character final location, uses initial
character location instead. 
Flamethrower zero damage , but does take the location from acquiring target. (even though its given the wrong location)
Toxitron: Gas cloud, should turn entities in it green, this happens for players but not the bosses. 
Expunge effect not doing any damage when used on bosses. should be doing an extra 10k damage on every hit. 

Adds on upper ring are not patrolling. left set of dogs might not be casting abilities. dragons are clipping through floor. but are otherwise fine. 

Artremidies: missing, £10000 reward for capture dead or alive. (after adds die, no RP event starts and gong is not hittable, to start fight)

Tank PoV https://youtu.be/kQaHvIP4rnk 

warriors can also charge through the floor on magmaw 
![image](https://user-images.githubusercontent.com/121137397/216844518-b0eafa44-8eca-45e3-991f-68eb90c58cc2.png)

**Comment by WhitemaneSylah** [comment]
Rice
OP
 — Today at 00:50
The two adds on magmaw holding the chains to him fell through the floor after our bear tank taunted and backed up. couldnt get a picture because we couldnt recreate it. the adds just dissapeared.

**Comment by Commander-Rug090** [comment]
update: Drakinoids before Magmaw boss are hitting everyone except tank's, they should be hitting in a cone in front of themselves instead of basing it off of their currently selected target (or in this case the opposite of it)

Mag'Maw
Lava parasites: "parasitic infection" ability not working at all, it should spread an infection to the player on contact with a player and make a new parasite. 

update to "renew not being castable" problem: not only renew but ANY HoT style spell is not castable. single target spells are still castable, additionally a problem with Bloodlust/Timewarp seems related: "when a player casts Bloodlust or Timewarp during Mag'Maw fight, they player receives the buff but not every player around them, despite being in range, in their group and their raid."

Omnitron
Magmatron's "flamethrower ability tracks the target before and after "acquiring target", however it still does no damage. 

the shared healthpools work for the first rotation of the bosses activation only, after the recycle back to the first boss the HP is different from each other, this is also true of wipes.

Atramedes
Sonic Breath has no effect on players standing inside the bosses red ring on the floor. the damage should be coming from the centre of the bosses body not the outer ring making up the range radius of the fight. 

Tank PoV https://youtu.be/zAId7PpTxaw

**Comment by Commander-Rug090** [comment]
**Critical error:** 
Able to walk through the gate separating Mag'Maw and omni from the rest of the bosses, by pressing "W" key (walking forwards) after logging back into the game. this was achievable by having a low quality PC running the game on high graphics settings, causing the "gate" to not render briefly (as best we can tell, need confirming) Video proof: https://youtu.be/Mm6cohE0Dvg

**Comment by Commander-Rug090** [comment]
Update:
**Drakonid Drudge:**still not working as intended see previous notes. 
**Golem Sentries:** red circle attacks happen at the right time now, however they hit players to far away from the intended range, standing very far away from the red circle still results in being hit. 

**Omnitron:**
*Toxitron:* "Poison Soaked Shell" still does not apply damage buff to player damage when hitting targets after gaining it. 

"Chemical Bomb" placement not as appears, Druid Tank got the debuff and declared using /s (auto generated from DBM) that it was being placed on him but it appears elsewhere in the room, but still debuffs the tank. (see video for more info, check the end of the fight).

**Adds:** 
*Drakadon Mongrel*: do not leave the "Slayer" and ignore all taunting, whole group fails to patrol, its not in the video but members of the raid reported seeing them patrolling when coming down the lift. 

**Chimeron:** hunter's mark partially initiates the boss, it wakes up the boss but he does not attack until someone steps in melle range. (this also happened with DK pet)

additionally Chimeron will follow players outside his room instead of resetting like other bosses. 

**Artremedes:** 
*Sonic Breath* is avoidable by stepping inside Artremedes "red Circle" on the ground. the damage begins at the tip of her snout but should extend from the very centre of her character model/range. 

*Airborne Phase*, *Roaring Flame Breath*: begins at the correct speed but does not increase over time, additionally hitting any of the gongs (Resonating Clash) around the edge of the room should cause Artremedes to  be stunned temporarily then use her breath on a new target.

Tank PoV https://youtu.be/GFWvnM3S8ZE
