### ISSUE TITLE
[Raid] Throne of the four winds issue list (Normal)

### ISSUE THREAD

**Issue by Dechuka** [gamefreedomgit/Maelstrom#1719]
**1- Anshal, Rohash and Nezir should not leave their platform**

**2- Rohash issues :-** 

*- _Wind Blast_ does not work at all ,the boss ability can be found below
https://wowpedia.fandom.com/wiki/Rohash

**3- Nezir issues :-** 

*- _Ice Patch_ does not work at all, the boss ability can be found below
https://wowpedia.fandom.com/wiki/Nezir

**4- Anshal is scripted**

**5- Al'Akir is scripted**, however after the boss is defeated, raid members should receive _Eye of the Storm_ buff which allows them to fly and their movement increased by 300%
https://www.wowhead.com/spell=82724/eye-of-the-storm

Thanks to Mullich feedback, loot range should be 50K yards

**Comment by WhitemaneSylah** [comment]
Retest 22.01
Nezir - Mechanics working correctly,  slight pathing issue during tank swap (refer to video)
Anshal -  During Nurture cast it should spawn 1 Ravenous Creeper every second for 5 seconds.  Currently he only spawns 2.  Should spawn 5
Rohash -  Windblast is scripted but Rohash does not move around.  Model does not match the mechanic
<GM> Sylah — Today at 14:29
Al'Akir - Bugs  still present from previous report,  Squalline still needs the immunity but functioning better , Phase transition is working now
Potential target bug with Acid Rain - Might be targeting the aggro target rather than whole room.
Kinden — Today at 14:29
https://youtu.be/XJtkhEch2iA tank PoV

**Comment by UltraNix** [comment]
Fixed.

**Comment by WhitemaneSylah** [comment]
1st boss issue list

 -General stuff
  (game-breaking) We noticed that sometimes we can't take platforms when you have the buff "Slipstream". We have to click off the buff and try it again (we suppose it is bc of the buff)
  (minor) We take fall damage taking tornados to Al'Akir platform 

 -Nezir boss
  (major) Ice on the ground damage seems to be low
  (major) Stacking buff damage seems to be low

 -Rohash wind boss
  (major) Wind Blast visual does not match the ability (facing one way, getting knocked by ability on his sides)

**Comment by UltraNix** [comment]
Please- next time do not open already closed report and open a new one.

**Comment by varjla** [comment]
Add this one to the list:
Sometimes, all the 5 players get a bug combat, and even after killing the first boss, that combat never releases. If you use the eye option "leave the dungeon" and reenter again with the eye, the dungeon gets restarted fully (only for the players that leaave), and the eye gets bugged, and you can't even open the menu of the game.
