### ISSUE TITLE
[Quest] Defend the Tree - undoable

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1739]
Quest: [Defend the Tree!](https://www.wowhead.com/quest=13935/defend-the-tree)
Issue: [Shade of Shanumbra](https://www.wowhead.com/npc=3831/shade-of-shadumbra) needs Energy to use its abilities (like feral druid). Shade has no energy and it is not gaining any energy at all. That results in player being unable to kill a single enemy, making the quest undoable.

**Comment by EdyGlockenspiel** [comment]
Additionally, the Goddess's Boon buff you get for being in the moonwell dose *not* regen any HP to the cat, and you don't regen hp passively for being out of combat, either. This means you are going to die 100% and need to get a new cat multiple times. This is on top of the fact that your only means of killing mobs is auto attaking because of the already mentioned no energy or energy regen.

**Comment by Mistral01** [comment]
Undoable, you can't even kill one before dying because of low damage you do.

**Comment by KevlinTallfellow** [comment]
This quest is still broken, as described above.

**Comment by PanJanuszek** [comment]
fixed 15.01.2024
