### ISSUE TITLE
(Heroic) Dungeon - Blackrock Caverns

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1971]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
[Group comp: Rogue, Ret Paladin, RDruid, Hunter, Feral Druid]
There were only a few major bugs/wrongs in the one run we did, but we were still able to complete the dungeon in average ~340-350 ilvl gear:

Rom'ogg Bonecrusher
-[Quake] happened about every 3-5 seconds it felt like, some times we couldn't even kill the first wave before the second quake came
-[Chains of Woe] would not take the root off after being killed once, not sure if it was a weird one time thing, will probably retest later

After killing Rom'ogg, Raz the Crazed should drop down and clear a path for the players up until the end of the bridge to the second boss. He did drop down and start combat, but he did not kill any of the adds in our way. We probably could not have gone through without the Rogue somehow sapping every single one of them, I'm sure he will report the bug on this in his own time. [Clueless]

Corla, Herald of Twilight
-The beams coming down from [Evolution] were not properly showing who the beam was landing on, this made it very confusing and unless you were looking at your debuffs you wouldn't know 100% if you were soaking or not. (There was also a moment where our Rogue seemingly hiked up his stacks almost instantly turning him into the Twilight Drakonid, unsure what it was from)

After reaching the second bridge after Corla, Raz the Crazed should appear again to clear the bridge for the players. He did not appear at all, and we again relied on the Rogue for passage.

Karsh and Beauty worked perfectly. And while Raz, again, didn't appear to clear the adds beforehand, Ascendant Lord Obsidius gave us a hard time, his mechanics worked as well.

**Database links:**
Rom'ogg Bonecrusher (normal): https://cata-twinhead.twinstar.cz/?npc=39665
(heroic): https://cata-twinhead.twinstar.cz/?npc=39666
Quake (unsure which): 
https://cata-twinhead.twinstar.cz/?spell=92546
https://cata-twinhead.twinstar.cz/?spell=95317
https://cata-twinhead.twinstar.cz/?spell=92545
https://cata-twinhead.twinstar.cz/?spell=75372
https://cata-twinhead.twinstar.cz/?spell=75272
Chains of Woe:
(normal) https://cata-twinhead.twinstar.cz/?npc=40447
(heroic) https://cata-twinhead.twinstar.cz/?npc=50379

Raz the Crazed: https://cata-twinhead.twinstar.cz/?npc=39670

Corla, Herald of Twilight (normal): https://cata-twinhead.twinstar.cz/?npc=39679
(heroic): https://cata-twinhead.twinstar.cz/?npc=39680
Evolution:
https://cata-twinhead.twinstar.cz/?spell=87378
https://cata-twinhead.twinstar.cz/?spell=75610
https://cata-twinhead.twinstar.cz/?spell=75697

**Comment by UltraNix** [comment]
`-[Quake] happened about every 3-5 seconds it felt like, some times we couldn't even kill the first wave before the second quake came`
Timer is 17 sec (with exception on Chains of Woe - 5 sec).

**Comment by UltraNix** [comment]
`Corla, Herald of Twilight
-The beams coming down from [Evolution] were not properly showing who the beam was landing on, this made it very confusing and unless you were looking at your debuffs you wouldn't know 100% if you were soaking or not. `
I don't see any kind of "warning" on any video.

**Comment by UltraNix** [comment]
Fixed.

**Comment by UltraNix** [comment]
@Aughra23 After DC?

**Comment by Commander-Rug090** [comment]
Rom'Ogg
chains of woe, are non targettable, this causes the boss to either TPK the party or do massive damage to the tank at the very least.

Raz the Crazed stands still until the party bring some enemies near him to kill, after this he helps clear the first and secodn bridge but never reappears on his final spot in front of the final boss to clear the enemies at the back. 

Corla:
after changing into the big guys the adds kill a player then stand thier doing nothing. they should pick a new target and try to kill them.

Grievious wounds applied by the Evolved Twilight Zealot's not dissapearring after full heal, as the tooltip says, the debuff should go after the player is fully healed. 

Ascendant Lord Obsidius:
Shadow of Obsidus:
Twitchy ability not working, taunting the enemies does not work, they dont seem to follow the rule of "attacking the last player to recently generate threat"

**Comment by Aughra23** [comment]
> @Aughra23 After DC?

Don't recall a DC. Was two of us, we killed the first boss and Raz never came.

**Comment by UltraNix** [comment]
Fixed.

**Comment by whothatdog** [comment]
@UltraNix, @MrTide, @Sketish can I use this issue instead of open new one? I hope it's ok.
following => https://github.com/gamefreedomgit/Maelstrom/issues/3241#issuecomment-1722523051


Ascendant Lord Obsidius:
The boss is fine except his **Shadow of Obsidius**.
The melee damage of the NPC is wrong.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/5ae3aead-0dd8-4122-965d-9eae4744b508)

compare their damage to this here:
https://www.youtube.com/watch?v=lxIx_fu_bQ0 => 0:10-0:20
https://www.youtube.com/watch?v=_sArB-YXz4M => 1:43-1:50

the NPC can be dodge, resist, miss, parry
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/c10787cc-45d9-4179-862c-b0cb17cadebe)
which cause them to not apply Crepuscular Veil.

There should be only 1 Crepuscular Veil debuff, not 3.
in Whitemane each Shadow of Obsidius has own debuff, that wrong.

NPCS:

**Conflagration**
on some videos Group able to pull the NPC upstairs, near the bridge so Quicksilver won't be activated.
on Whitemane they said if you do that the NPC just go under texture.

https://www.youtube.com/watch?v=VQ-QGTOkruM => 8:05
https://www.youtube.com/watch?v=8eYTNIx37dA => 6:16

Although according to this video
https://www.youtube.com/watch?v=-dqtb__obpE => 16:25 they do follow even if you go upstairs.

Others:
You can use the teleport to Karsh before killing him.
according to what I know you cannot use the teleprot before this boss is killed.

**Comment by UltraNix** [comment]
@whothatdog The issues from this report have been fixed and closed some time ago.
Please, open a new report.
