### ISSUE TITLE
[Tester raid] Baradin Hold issue list

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1988]
Pets fall through the floor on boss mods
![image](https://user-images.githubusercontent.com/121137397/213933848-d39e4f9a-7168-4eb0-80aa-f9767fcf9da4.png)
![image](https://user-images.githubusercontent.com/121137397/213933853-181dbfde-acec-47d3-9a4b-6a51282cf01b.png)

Kinden — Today at 13:10
When an enemy is Charged by any means on pull, then the enemy drops through the floor of the map and does not return, similar things happen to pets, (hunter, DK and Warlock). in addition, shamans totems falls through the map too, not sure if related?

https://youtu.be/KLGNi4pykD8

<GM> Sylah — Today at 15:10
@GaGa  Good to go,  Only bug to keep in mind for Baradin Hold is that Pets and adds will fall through the floor and boss will fall through the floor if charged by a warrior/druid ,  pictures here https://discord.com/channels/1063031147501723658/1064195383686864956/1066702675233742888
GaGa — Today at 18:39
Please push it to github.

**Comment by UltraNix** [comment]
I can't reproduce it anymore. Still valid?

**Comment by WhitemaneSylah** [comment]
Will retest !

**Comment by UltraNixx** [comment]
@WhitemaneSylah How's the result?

**Comment by Sketish** [comment]
23.03
Run on main realm

Trashes before boss have wrong hp pool
https://wowpedia.fandom.com/wiki/Demon_Containment_Unit
on 10m have 400k hp instead of 2,074,850 hp
on 25m have 995k  but should be 6,224,500 hp

Argaloth
-First cast of Fel Firestorm is now not working at all, boss is interrupting his cast but fire is spawning randomly after some time.
-Slashes are working correctly now
-Next casts of Fel Firestorm are working correctly
