### ISSUE TITLE
Death Knight [Raise Dead] Frost, Blood

### ISSUE THREAD

**Issue by Mietla122** [gamefreedomgit/Maelstrom#2008]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Pet deals a way more damage than in unholy spec 5.5k+ without glyph Raise Dead [https://imgur.com/a/w7nXU1q]

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by MullichWhitemane** [comment]
I've tried looking for sources that this shouldn't be this way, but couldn't find anything. If you can, please provide us with evidence that this behavior is not intended.

**Comment by MullichWhitemane** [comment]
So I've scoured a lot across youtube, and I found some evidence from Retail Cataclysm.
https://www.youtube.com/watch?v=XHv4Mwg0qmo at 5:38, a Frost DK has his ghoul active, and is pummeling the Rogue, does roughly 1k normal hits and slightly below 2k crits.
![frost dk ghoul](https://user-images.githubusercontent.com/121984461/214486657-7be44dc4-152d-4c34-b1f5-c2813896121c.PNG)

https://www.youtube.com/watch?v=yiii5ultT_Q In this one, we can see an Unholy DK with an unbuffed ghoul go up against a geared warrior, who has a much higer armour value than the Rogue (and likely higher resilience), yet the unbuffed ghoul is hitting him for 1.2k per normal hit.
![unholy dk ghoul](https://user-images.githubusercontent.com/121984461/214486784-b24fba80-5a62-41bc-88c4-bd2275a8caea.PNG)

It seems as if our iteration of the Unholy Ghoul is working correctly, it is the Frost and Blood variants that hit too hard. Remember that our Target Dummies have 0 resilience and have very low armour (roughly 1k), which is why they can be hit exceptionally hard.

**Comment by UltraNix** [comment]
Hmm, so what is in Unholy Spec, that should make the pet hits harder than in those 2 specs?

**Comment by MullichWhitemane** [comment]
> Hmm, so what is in Unholy Spec, that should make the pet hits harder than in those 2 specs?

Ghouls scale off of the player's Strength, and Unholy DKs have 25% more strength compared to other specs through the Unholy Might passive.
