### ISSUE TITLE
Gargoyle dmg being too broken

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#2197]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Summon gargoyle does too much damage on full pvp gear target, 12k uncrits.

**How to reproduce:**
https://www.veed.io/view/00705aec-9219-4d2c-8e6c-015d1a1921d9?sharingWidget=true&panel=share

**How it should work:**
Theres something wrong with the scaling or coding on this spell / npc since it does too much dmg.

**Database links:**

**Comment by MrTide** [comment]
Hello player is correct
its because its effected by glyph of raise dead
![image](https://user-images.githubusercontent.com/36106057/220729568-2208321f-e63e-47d7-ad6b-335a396115df.png)
with glyph
![image](https://user-images.githubusercontent.com/36106057/220730011-9113541a-2184-4950-b8de-e0ee861f2fc2.png)
without glyph
![image](https://user-images.githubusercontent.com/36106057/220729858-4265e57a-6874-41ab-b85c-be8aec51c0fa.png)

**Comment by UltraNix** [comment]
Fixed.
