### ISSUE TITLE
Bad manner easily avoidable

### ISSUE THREAD

**Issue by Wees369** [gamefreedomgit/Maelstrom#2268]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
It is impossible to cc with bad manner a target that goes opposite the monkey (even if we spam the key).
And if we only use bad manner once, the monkey does not use bad manner at all but will attack the target.

**How to reproduce:**
Use bad manner on a moving target, which is moving away from the monkey (it can easily avoid it even if it is slow).

**How it should work:**
https://youtu.be/S5BBIPiMsqE?t=379
The monkey should be able to stun the target, even if it runs away from him.
On the video we see that the target is still moving (on the mini map).

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=90337

Tell me if more evidence/information is needed.

**Comment by MullichWhitemane** [comment]
The issue here - or lack of issue rather - is that we don't have spell batching, whereas Retail Cataclysm did. There was a very real mechanic that some few dubbed "slide casting" that basically meant that when someone went out of range, you still had 1-2 tenths of a second to get a cast off. This is because on the client side, the game realized that the target is out of range, but the server didn't receive that info, meaning the cast was successful. Ever since Spell Batching was removed in WoD, slide casting completely disappeared. This is also the reason why (for example) we don't have mechanics such as Polymorph into Frost Nova for a guaranteed Shatter for Mages, despite it existing on Retail Cataclysm.

This is not a bug.
