### ISSUE TITLE
Using on-use trinkets in Hunter Camouflage breaks the camo

### ISSUE THREAD

**Issue by Wees369** [gamefreedomgit/Maelstrom#2269]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
Edited by @MullichWhitemane, check https://github.com/gamefreedomgit/Maelstrom/issues/2269#issuecomment-1451804347

**Description:**
On use trinkets break Camouflage, with the exception of Cataclysmic Gladiator's Badge of Conquest, as this specific trinket had a fix applied some months ago here: https://github.com/gamefreedomgit/Maelstrom/issues/1273.

**How to reproduce:**
Use camouflage, and use a non-damaging on use trinket (for example, [Vicious Gladiator's Badge of Conquest)](https://www.wowhead.com/item=61033/vicious-gladiators-badge-of-conquest), and notice how it breaks Camouflage.

**How it should work:**
https://youtu.be/Xe8YLohHLrQ?t=206
Video example shows that using an on-use trinket that buffs the user doesn't break Camouflage.

**Comment by Murk825** [comment]
but the video is from s11 gear so 403 ilvl trinket not 352/365

**Comment by Murk825** [comment]
@Torpis

**Comment by Wees369** [comment]
They are the same trinkets, they work the same way, find a video that proves otherwise

**Comment by Murk825** [comment]
if is the same trinket why they dont work like dat in Whitemane ? all 352/365/403 should disable the camo then or not

**Comment by Murk825** [comment]
ok it should not remove camouflage with s9 gear 
proof : https://youtu.be/M6MxCpx_WmY?t=142

**Comment by MullichWhitemane** [comment]
A global rule for using on-use trinkets in Camouflage is that unless they do damage - or otherwise debuff an enemy in some way - is that they won't break Camouflage. The reason why 403 works is because of an old bug report that only detailed the 403 Badge not being useable. On the other hand, for other stealth mechanics (Stealth, Prowl, Shadowmeld, Invisibility), using on-use trinkets should always break stealth.

I will edit this bug report to reflect this.
