### ISSUE TITLE
Hyjal Nordrassil Inn WPvP Safespotting

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2324]
![WoWScrnShot_030423_181005](https://user-images.githubusercontent.com/121984461/222919510-7df5178d-ed03-4392-902a-6ef31c5efc50.jpg)

Need 2-4 Furious Hyjal Warden-s spawned in this area. Currently, people can safe spot by engaging others with ranged spells and attacks, and as the guards are in their LoS, they will never get pulled.

**Comment by EdyGlockenspiel** [comment]
Just had a ele sham try and gank people standing on the banister above the innkeeper. The guards should be well within range to agro to anyone standing there and use their shoot ability. However, I don't believe they even have the ability to shoot for some reason. Though it is listed as an ability on twinhead that they should have. 

https://cata-twinhead.twinstar.cz/?npc=43427

Additionally, they don't seem to be doing nearly enough damage. I, a lvl 80 frost DK in blood press, only got meleed for under 22k hp. I seem to recall these guys hitting like absolute trucks during official cata, at 85. They should easily be able to one shot me in my boosted greens, let alone this shaman in blues I gripped off the celling into the guards. Should most likely 2-3 hit non tanks, especially undergeared ones. I remember a 5 man group farming Booty Bay guards during cata for pirate rep and the tank having to use CDs constantly and the healer having to spam heal him to live. These guards in Hyjal are supposed to be just as strong if not more so. (On top of the fact they are for some reason lvl 90 instead of 85, which makes their pitiful damage even more confusing.

**Comment by EdyGlockenspiel** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/126888684/976b6439-ca05-4030-94ed-110bba107c99)
This is where the ele sham was attacking (the AFK DK in the SS) from until I gripped him down. The shoot ability is *also* a knockback as well and deals a fair bit of damage, maybe not as much as their melee, but roughly 10kish a shot?

**Comment by UltraNix** [comment]
Fixed.
