### ISSUE TITLE
QA RUN - THRONE OF THE FOUR WINDS

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2557]
Retest 22.01

Conclave of the winds
Nezir - Permafrost is doing no damage at all.  It should do 12k damage every 1 second in a 50 degree cone for 3 seconds.
Ice Patch does not do any damage.  Icepath should spawn on a random player and last 3 seconds.  Icepatches should do 4k damage every 1 second to all players within 10 yards and slow their movement speed by 5% (stacking)

Rohash - Windblast is scripted but Rohash does not move around. Model does not match the mechanic

https://wowpedia.fandom.com/wiki/Conclave_of_Wind#:~:text=The%20Conclave%20of%20Wind%20is,in%20combat%20engages%20them%20all. 
----------------------------------------------------------------------------------------------------------------------------
Al'akir should only engage when attacked.

Ice Storm should not target pets

Pets and totems will fall through the floor and despawn on phase 3.  they should be flying in the air on transition.  

Warriors/Druids can charge Al'Akir and end up in the centre of his hitbox,  they should not be able to do this. They should only move to the inner hitbox (next to the cloud swirls)

https://wowpedia.fandom.com/wiki/Al%27Akir_(tactics)

**Comment by WhitemaneSylah** [comment]
@Afgann  fixes to nezir were pushed and can confirm working 100% ,  Rohash still has same problem as specified above

**Comment by WhitemaneSylah** [comment]
Boss armor values are incorrect

All bosses should have armor value of 11977 ,  Currently Al'Akir has 1079. 

Please adjust all armor values.

![image](https://user-images.githubusercontent.com/121137397/227390496-1c84bc02-d966-4d61-b01d-4f9712c62613.png)

**Comment by Insilopeh** [comment]
Killing the ice guy in conclave, will reduce him to 1 hp and the effect of his ult is never removed (it deals no damage, but will lock everyone to the platform).

If any of the djinns resurrect due to the timer after having been downed to 1hp, they will no longer abide by their scripting and will behave like normal mobs and start chasing people on other platforms.

A resurrected djinn still counts as being dead for the purpose of the encounter (ie you just need to kill them all once, and not having them all dead at the same time).
