### ISSUE TITLE
[Paladin] Holy Power 

### ISSUE THREAD

**Issue by Nelson215121** [gamefreedomgit/Maelstrom#2606]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Hammer of the Righteous and Crusader Strike don't grant a charge of Holy Power every time they hit like they are supposed to. Likewise, Shield of Righteousness doesn't always USE the gathered charges of Holy Power.

**Comment by Nelson215121** [comment]
Yeah I've paid attention to it over the week making sure that it's not giving the charge when it hits.

**Comment by bl2x14** [comment]
Confirmed, doesn't always generate Holy Power when it hits for me either.

**Comment by Consealer** [comment]
It happens when Shield of Righteousness is blocked.
The block does not block the damage. Instead Shield deals 3xHoly Power damage, even if it's only 1/2 Holy Power. And it does not use Holy Power.
I just reproduced it with a 36% passive block prot warrior. Each time he was supposed do block it, he didnt and the bug accured. He blocked properly crusader strike.

**Comment by UltraNix** [comment]
@Hatepoem @Nelson215121 @bl2x14 @Consealer Still happens?

**Comment by UltraNix** [comment]
Fixed.
