### ISSUE TITLE
MMR GAIN/LOSS

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#2642]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently its not possible to climb high rating, even with a 75%+ winrate and 100 games you are stuck at 1800 rating cause you lose more mmr/rating than you gain most of the time.

**How to reproduce:**
Que a 2v2 arena with similar mmr and check win / loss difference, and do that for lets say a 1500 mmr team vs a 1800 mmr team, and see the win / loss difference, and same with 1500 mmr and 1400 mmr.

**How it should work:**
MMR should be checked when game ends and if you face a similar mmr team win/loss mmr should be the same but when facing higher rated teams you win, you should gain a massive amount of mmr / rating due to the mmr difference. And the opposite vs low rated teams.
**Database links:**

**Comment by MullichWhitemane** [comment]
I've done some research. I couldn't find any raw info on how the exact calculations are made, the closest estimate I could find was this: https://www.wowhead.com/guide/a-pvp-beginner-s-guide-to-the-dragonflight-pvp-rating-system-18980

The following images are a winstreak I've tried on the PTR with freshly made toons, and the last image is a victory with the lose-streak team.
![round1](https://user-images.githubusercontent.com/121984461/227990726-09008e06-6c33-4721-9588-a68d638213fe.PNG)
![round2](https://user-images.githubusercontent.com/121984461/227990913-e20756e6-e346-4e63-b2eb-2ef6925fba9b.PNG)
![round3](https://user-images.githubusercontent.com/121984461/227990947-7214b4ff-196d-478f-aab3-172395cd502f.PNG)
![round4](https://user-images.githubusercontent.com/121984461/227990971-830d6226-a46f-4d20-aa8e-0fd72a193b1f.PNG)
![round5](https://user-images.githubusercontent.com/121984461/227991166-01a5e245-bceb-4a97-9cf5-ea32767decd5.PNG)
![round6](https://user-images.githubusercontent.com/121984461/227991204-ec0ec124-80c2-4ecb-ac22-7aba32cdd8eb.PNG)

What we can deduce is the following:
On Whitemane, the base MMR gain / loss is set to 12 instead of 15.
On Whitemane, teams are not being rewarded / punished for win / loss streaks after the 4th streak.

**Comment by Kenniflopper** [comment]
https://www.mmo-champion.com/threads/720492-Guide-Match-Making-Rating-(MMR)

**Comment by UltraNix** [comment]
Fixed.
