### ISSUE TITLE
[Raids] -  25 man should drop 5 items

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2664]
25 man raids should drop 5 items (with a 6th being possible if mounts are applicable)

This works out as 1 item Per group (5 groups in 25 man).

Should a boss drop a mount their is a possibility for a 6th being that mount itself.

Source below

https://www.mmo-champion.com/threads/815953-How-many-pieces-of-loot-do-bosses-drop-on-25-man

Loot from 25 man raids should be 5 item drops (with a 6th possible if said boss drops a mount)

BH specifically -  2 items will be PVE, 2 items will be PVP,  and the last item will be random from that bosses loot table

**Comment by jlldarocha** [comment]
This is wrong. On cataclysm, when they unified 10 and 25 loot, their intent was always on 25 having more loot per player, as it was more complex to organize than a 10m. Theres several evidence for it(every video from retail cata), but im linking a direct quote of a blue post.

https://www.bluetracker.gg/wow/topic/us-en/24401856405-cataclysm-raid-progression-refinements/

Loot was: 
10man= 2 pieces and 1 token(on bosses with tokens)
25man = 6 pieces and 3 tokens(on bosses with tokens)

**Comment by UltraNix** [comment]
Fixed.

**Comment by testdk123** [comment]
Wait, was this actually fixed? Because the original report was wrong, 25m should drop 6 items + 3 tokens in applicable bosses, as the other comment correctly showed.

That mmo-champion thread is just plain wrong, you can see 25m never ever dropped 5 items even in 4.0.6 patch. Only in Dragon Soul loot suffers one alteration; in that tokens share a spot with regular boss item drops. Meaning 10m token bosses would drop 1 item off the regular loot table + 1 token, and 25m bosses would drop 4+2.

**Comment by jlldarocha** [comment]
25m loot is now wrong, dropping less loot than it should because of this false report.
As i said in my previous answer:
bossses that drop tier tokens should give 6 pieces of loot, and 3 tier tokens, Ex: al akir https://youtu.be/NJCfe6YJ6Rc?t=572

Bosses without tier tokens should give 6 pieces of loot, Ex: chimaeron https://youtu.be/S8A8tamdI2s?t=470
 
Baradin hold bosses should give 6 pieces of loot, 3 pvp and 3 pve, Ex: argaloth https://www.youtube.com/watch?v=rzid0DGMLU4&t=238s

**Comment by jlldarocha** [comment]
25m loot is now wrong, dropping less loot than it should because of this false report.
As i said in my previous answer:
bossses that drop tier tokens should give 6 pieces of loot, and 3 tier tokens, Ex: al akir https://youtu.be/NJCfe6YJ6Rc?t=572

Bosses without tier tokens should give 6 pieces of loot, Ex: chimaeron https://youtu.be/S8A8tamdI2s?t=470
 
Baradin hold bosses should give 6 pieces of loot, 3 pvp and 3 pve, Ex: argaloth https://www.youtube.com/watch?v=rzid0DGMLU4&t=238s
