### ISSUE TITLE
druid 's Skullbash vs hunter's Detterence

### ISSUE THREAD

**Issue by jimmyiwnl** [gamefreedomgit/Maelstrom#2689]
Feral shouldn't be able to skull bash through Detterence, u can test it while casting scare beast while in detterence.
nothing expect chaos bolt should go through detterence in cata.

**Comment by bonfax4** [comment]
@UltraNix 

https://www.mmo-champion.com/threads/992725-Hunter-PVP?highlight=skull+bash+deterrence
2011-10-06
> For Ferals, you deal with feral charge the same way you deal with shadowstep. But ferals are incredibly easy to deal with as a Hunter. Just trinket right away his opener since its at that point he sets up most of his damage on you. Ice Trap him, if he trinket just scatter-> Scare Beast. Fake-casting scare beast is also awesome to make them waste skull bash, but they can interupt it trough deterrence, learned that the hard way in a 2s game, but most ferals don't seem to know this.

https://www.wowhead.com/spell=19263/deterrence#comments
![6495849afed6391a885a888480a4adec](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/123b7f2d-1ea3-47dd-8655-b0df45e8ce95)

https://cata-twinhead.twinstar.cz/?issue=3099
Link they have as proof is unavailable and unnacessable with webarchive but they came to the conclusion it should work through deterrence since interrupts cant miss in cata and deterr gives 100& miss to melee abils.

**Comment by UltraNix** [comment]
Another one bites the dust...
