### ISSUE TITLE
Warlock Dark Intent

### ISSUE THREAD

**Issue by Sanzu9055** [gamefreedomgit/Maelstrom#2808]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:

In link below.

**How to reproduce:**

**How it should work: both of warlock should get 1 buff stacked to 3(1% per stack) and 1 buff stacked to 3 (3%per stack)

**Database links:

https://imgur.com/a/ERp9R0U

**Comment by bonfax4** [comment]
@UltraNix  This recent fix needs a second look. Patch 4.1 hotfix that made the DI proc to the target become a 3% dmg increase from 9% also had a stealth fix where dark intents would not stack with each other so this is shouldn't possible to begin with. And even before this hotfix it never worked like this, why it was recommended for warlocks not to DI each other when possible, you'd lose 2x 9% buffs since they would not stack before the hotfix.

Sources: 

https://www.mmo-champion.com/threads/894576-Ninja-dark-intent-nerf-(not-in-patch-notes)?highlight=Dark%20intent%20warlocks
> I tried swapping DIs with a warlock, we couldn't both benefit from the 3% haste buffs, was this intentional? Can anyone else confirm this?
> 
> I.e, he put his on me and it overwrote the buff that I get from putting it on him.

https://www.mmo-champion.com/threads/813759-Mechanics-Dark-Intent-(4-2)/page11
> Can't stack the DI's anymore, so if you try to swap it with another warlock to get 6% haste, it overrides the previous DI, and will only give the 1% stacks to the warlock you gave it to. From what I can tell give it to the player that can get the benefit out of it as the buff is so much less now. Notice I said player and not a certain class, as each raid is different in terms of player skill -
