### ISSUE TITLE
Hunter pet cooldowns not being shared between all pets

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#3019]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

I noticed in solo que that a few try hards, I call them" dismiss bot " hunters who are having 5 monkeys as a pet and they use them 5 times in a short period of time in arena.

That means they can use 5 times monkey stun and 5 times roar of sacrifice which will give them an unfair advantage in the game.
Roar of sacrifice is a spell that makes the buffed player immune to critical strikes for 12 seconds.
Pretty much OP right?

**How to reproduce:**

**How it should work:**

Hunter pet cooldowns should be SHARED between all pets.
It worked like that during retail cata as far as i remember.

**Database links:**

https://www.youtube.com/watch?v=3dJ5Haw_8JE 

https://www.youtube.com/watch?v=MFql5TSpT5M

These are two clips from one of the worlds best hunters during Cataclysm live and as you can see in the videos he never did play with the dismiss strategy like all private server heroes do, cause pet cooldowns should be shared between all pets.

**Comment by Sketish** [comment]
Cooldowns are not shared, as example


https://youtu.be/dDyfijDWqTg?t=485

You can see he has 3 min cd for Call of the Wild, by swapping pets he can reuse this instantly.

Only bug I found is that Bad Manner should share cd with Scatter shot, currently this one is not working.

" In 4.0.6, with MM hunters being massively buffed, this is getting nerfed to keep us in line, and it will break on damage. Bad Manner does share DR with Scatter Shot, however, but you can still use a Monkey to pull off some sick CC chains. Scatter Shot + Bad Manner + Freezing Trap + Silencing Shot is 17 seconds of CC in a world where Polymorph only lasts 8 seconds. That's insane if you can pull it off. That said, spiders (and sometimes crabs) are still king for duels, fighting melees, and most situations. Aimed Shot is our bread and butter now, and people don't usually stay in line of sight of us long enough to get one off unless they're rooted."

**Comment by Sketish** [comment]
11 years ago was retail cataclysm. From that video you can see that pets are not sharing cooldown. If you find any pvp proof that they should share cd then we will have confirmation. Because  saying "as far as i remember." is not enough.

**Comment by Renehadox** [comment]
> 11 years ago was retail cataclysm. From that video you can see that pets are not sharing cooldown. If you find any pvp proof that they should share cd then we will have confirmation. Because saying "as far as i remember." is not enough.

Then why Braindeadly one of the worlds best hunter in that time never did that in one of his clips ?

I watched 3 clips of him, he never did it.

**Comment by Sketish** [comment]
As I said, this is not confirming or denying if pets should share cd for abilities.

**Comment by Renehadox** [comment]
> As I said, this is not confirming or denying if pets should share cd for abilities.

Yes but also, private servers existed in those times as well.

However since you are a developer you also know that wow as a game itself is hard as hell.

Imagine if a hunter who got 5 monkeys, uses 5 times bad manner and 5 times RoS, that means 5 x 12 = 60 seconds aka 1 minute of immune to critical strikes?

Thats unfair advantage and not blizzlike.

" Because saying "as far as i remember." is not enough. "

I said like that cause i played during retail cata and i don't remember all things 100% from 12 years ago,.

**Comment by Renehadox** [comment]
Look what i found, the bug that i reported is applied as a fix on one wow server which i dont wanna mention name. :D

![hunterpets](https://user-images.githubusercontent.com/67479994/232049894-640321c1-7d19-4bea-ad50-3e9e611add65.PNG)

**Comment by Sketish** [comment]
That's why I took pve content because 11 years ago there were noone pve scripted private servers. What I was able confirm that Bad Manner and Scatter shot should share DR.

Imagine if a hunter who got 5 monkeys, uses 5 times bad manner and 5 times RoS, that means 5 x 12 = 60 seconds aka 1 minute of immune to critical strikes?

Thats unfair advantage and not blizzlike.

If you find proof it's not blizzlike then it will be fixed. Using other pserver as source wont work.

**Comment by Renehadox** [comment]
Are you joking or are you serious?

" Using other pserver as a source wont work "

So you are trying to say the developers of that private servers were " dumb " to apply that fix and post it publicly? Oo

It is a bug man, 

Did you even watch braindeadly videos???

I literally just showed you a screenshot of the bug applied as a fix from other legitimate server.

**Comment by Sketish** [comment]
Find any video from retail that will proof it.

**Comment by Renehadox** [comment]
> Find any video from retail that will proof it.

I am literally watching 4th Braindeadly video.

I've yet to see he is changing pets, i mean... the guy was 3000 rated back then.... 

So if he never plays that " strategy " that means is a common bug on most private servers out there.

I gave you a logical explanation above also a SS as a fix from other server, you don't consider them, i mean idk what to say, watch braindeadly pvp videos and see for yourself...

**Comment by bonfax4** [comment]
https://www.mmo-champion.com/threads/841249-Call-of-the-wild-discussion/page2?highlight=call+of+the+wild+swap 

Call of the wild was clearly there. Other abilities not sure.

**Comment by bonfax4** [comment]
https://www.mmo-champion.com/threads/1051525-Dismissing-pets-freshly-called-pet-having-very-low-health-and-dying?highlight=bad+manner+pet+swap 

> For a hunter to be any good in PvP it is required by the hunter that he has alot of monkey pets for monkey blind and roar of sacrifice. Personally I have one cat, one spider and 3 monkeys.
> 
> I recently made a ticket complaining about freshly called pets spawning with very low hp causing them to die. When a hunter pet dies, It's very hard to get it back if the enemy is any decent, and when your pet dies you're basically SCREWED as you cant call a new pet without ressing your dead pet.
> 
> An enemy that knows about this will watch for a hunter dismissing his pet, and be ready to kill the new pet instantly because of low hp once it spawns.
> 
> The gm I got a response from said that this is actually INTENDED. How stupid isn't that?
> 
> The response; "As for the pet health while they are just summoned, that's an intended mechanic to stop several exploits. This way it also gives fair chance to the other players when you unsummon almost dead pet just to summon a new one with full healt, making it more fair in pvp combat. If you don't wish for your pet to be killed right away, please be sure to summon him before the fight."
> 
> This Game master doesn't seem to understand why we are dismissing our pets; "please be sure to summon him before the fight." I LOL'D.
> 
> Discuss. Cry with me.

**Comment by Sketish** [comment]
Thank you bonfax4

**Comment by bonfax4** [comment]
Low heal thing the guy mentions needs to be adressed tho, you can see it in the video you linked too. Couple seconds where pets have like 6k health on swap/call so you can easily kill it.

**Comment by Sketish** [comment]
> Low heal thing the guy mentions needs to be adressed tho, you can see it in the video you linked too. Couple seconds where pets have like 6k health on swap/call so you can easily kill it. 3-4 seconds it seems.

Moved to https://github.com/gamefreedomgit/Maelstrom/issues/3023

**Comment by Hoofjob-Instinctz** [comment]
Sketish with all do respect lets just point out how many wrong things are going on here. 1# i literally just showed you both lines of text from the official wow patch notes on my own post, not a private server and u closed my post. i gave you the proof the other guy didnt, sketish. #2 wowhead dosnt containt an accurate list of ALL patch notes, twinzstars actually does to an extent with some small mistakes which the staff for that server is aware of AND the staff member of whitemane who made this github ( who clearly isnt you ) literally has it in the guide to use twinstar for examples a different private server as an example FOR patches, to which you respond to the other person saying you cant use that as an example and yet thats what the guide suggests to use. also the post the other player posted which for some reason he didnt wanna say is is from warmane ( even if it isnt has the same line of text ) which for cata was a staff with official tournament based patches to which they stole source code directly from blizzard which is half of why MOLTEN wow got shut down years ago to which then warmane came out then when they had a cata server up used the same source code and then took it down cuz it wasnt worth the risk with a lower player basis. #3 the reason you saw in the video pets werent sharing cooldowns is becuase there DIFFERENT pets being used which is why even the best players in the entire world didnt use this method, after the first 2 months it came out. pets of same family sharing cooldowns as in abilities by same name such as the bad manners ability started sharing CD thats why the line of text in the official patch list i showed you ( pet families added ) is in reguards to that issue, and also made it so the ability behaves exactly like a rogue blind rather then a stun or taking some damage to break which is whats happening on the server ( taking some damage to break instead of no damage ) #4   PATCH IT. its supose to share CD and its behaving like the damage from a fear instead of a rogues blind. as in its taking multiple hits to break rather then instantly from one single hit. i will repost my links again. your ignoring blatant eveidence. 

https://wowpedia.fandom.com/wiki/Patch_4.0.6    <---OFFICIAL WOW PATCH LIST

https://www.youtube.com/watch?v=5Es7wWtZIb8      Explained that during the same patch when stun was fixed that the pet families started to share CDs .... now do your job! and fix it.

**Comment by Hoofjob-Instinctz** [comment]
> Are you joking or are you serious?
> 
> " Using other pserver as a source wont work "
> 
> So you are trying to say the developers of that private servers were " dumb " to apply that fix and post it publicly? Oo
> 
> It is a bug man,
> 
> Did you even watch braindeadly videos???
> 
> I literally just showed you a screenshot of the bug applied as a fix from other legitimate server.

Lol Dont worry man i just got confirmation this is gonna be fixed, sketish u were completely wrong. happy to say we wont be dealing with this BS anymore

**Comment by Renehadox** [comment]
> > Are you joking or are you serious?
> > " Using other pserver as a source wont work "
> > So you are trying to say the developers of that private servers were " dumb " to apply that fix and post it publicly? Oo
> > It is a bug man,
> > Did you even watch braindeadly videos???
> > I literally just showed you a screenshot of the bug applied as a fix from other legitimate server.
> 
> Lol Dont worry man i just got confirmation this is gonna be fixed, sketish u were completely wrong. happy to say we wont be dealing with this BS anymore

I am a Cataclysm retail gladiator myself and i none of the hunters in my battlegroup used that shit style of play like they do here.
I already posted a screenshot of that fix from another cata server but the developer didnt take that into account.
I knew very well what was i reporting...
Those hunters that play with that strategy i call them " dismiss bots "

**Comment by bonfax4** [comment]
Dude there's multiple sources in mmo champion mentioning the pet swap on late cata, way after 4.0.6 ( Only fix they did here was make bad manner break on damage, it behaved like a stun ). 100% you're misremembering stuff. They should really add the low health pet thing on swap tho and it will hinder this playstyle since you should be able to 1 tap pets easily, even though that's a non intended thing. But if they intentionally add shit mage ignite mechanics thy should also do this.

More cata dated sources :

https://www.mmo-champion.com/threads/1054570-Tips-on-beating-a-rogue-1v1?highlight=Monkey+pet+swap

> Make sure you have 2 monkeys, you have to either monkey blind or sac every kidney/dance. I usually monkey blind his opener then flare+ice trap and start pumping damage. They'll usually shadow step to you, disengage away them pop RF+dmg trinket. They'll probably vanish here. As a rule, whenever they vanish quickly switch to your back up monkey. Also, after they have blown trinket (they'll usually trinket a scatter > snake/ice trap) you can scatter > monkey swap.
> 
> I also trinket full kidneys instead of blinds (just let ur pet attack).
> 
> As long as you always have a monkey out to blind/sac their kidneys/dances it's really easy and the rest you should be able to figure out, it's just basic kiting.
> 
> I get upset when I see hunters using spiders vs rogues/mages/ferals. Monkey is overpowered. E.g vs a feral I can win on 100% HP easily with monkey (all their damage comes from opener, which u can stop with blind). With spider its usually very close or they win because opening bleeds can take you to 40% even if you kite well.
> 
> VIVA LA MONKEY
> 
https://www.mmo-champion.com/threads/1165659-Hunter-macro-for-pet-changing?highlight=Monkey+pet+swap

> Anyone got a macro that will swap between 2, maybe 3 different pets (I'm trying to make switching monkeys mid arena easier) cycling so i don't call one that already used sac/monkey stun? thanks in advance.

**Comment by bonfax4** [comment]
@Renehadox @Hoofjob-Instinctz  Here you go a video to finally shyt this issue down once and for all. Hard to find rogue hunter duels in cata for some reason. 4.3 video 2012, check @ 1:20 and listen to what he says and the bad manner on his toolbar.
https://youtu.be/XvORL45IXdc

**Comment by Renehadox** [comment]
Alright, we have a dismiss bot in the house.
@bonfax4

**Comment by bonfax4** [comment]
@Renehadox Funny thing is I don't even play hunter on this server lol. Just admit you were wrong tho.

@Sketish make sure they don't "fix" something that is working properly pls.

**Comment by Renehadox** [comment]
So this is gonna be fixed or what?

**Comment by Sketish** [comment]
as @bonfax4  linked video there is already proof that pets shouldnt share CD's. 
Also linking 4.0.6 patch notes which was released 
February 8, 2011 but then people in 2012 are discussing swapping pets on arena https://www.mmo-champion.com/threads/1165659-Hunter-macro-for-pet-changing?highlight=Monkey+pet+swap

Only bug is that pets should have low hp when resummoned, and its already reported in other issue.
