### ISSUE TITLE
4.1.0 content Like Pike? / Time for Slime (Undercity Fishing Daily Quests)

### ISSUE THREAD

**Issue by Mepox1** [gamefreedomgit/Maelstrom#3044]
The two daily fishing quests can't be completed.

**1) Like Pike?**
- the needed quest item "Corpse Worm" can't be looted from the grave in the Undercity courtyard, therefore the "Corpse-Fed Pyke" can't be caught/fished out
- https://www.wowhead.com/quest=29320/like-pike

**2) Time for Slime**
- since you can't dive in the Undercity waters, I couldn't loot the "Squirming Slime Molds"
- https://www.wowhead.com/quest=29322/time-for-slime

**Comment by UltraNix** [comment]
About 2.
https://www.wowhead.com/quest=29322/time-for-slime#comments:id=1462410
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/7cdaeb08-67c4-43f1-9600-c3fe82cce40f)

**Comment by emirie1** [comment]
Based on a comment on the Wowhead page for "Like Pike?", the quest is not working properly because the current state of the Ruins of Lordaeron is that of "The Day of the Dead". The comment reads:

> It's worth noting that the Day of the Dead presents a bug that renders this quest impossible to complete. I picked up Like Pike? on the Day of the Dead and could not click on the graves to retrieve the worm. However, the next day when the Day of the Dead was over, the graves became click-able again and I was able to complete the quest as normal.

If the world state for the Ruins of Lordaeron is changed back to normal, then the quest "Like Pike?" should become able to be completed.

https://www.wowhead.com/quest=29320/like-pike#comments

**Comment by UltraNix** [comment]
Fixed.
