### ISSUE TITLE
Guild reputation between 60-79

### ISSUE THREAD

**Issue by hamzaeleuch97** [gamefreedomgit/Maelstrom#3099]
Hello, when you do a dungeon with 3 members of same guild same level as the 3 dungeons itself  You should be getting reputation towards guild, the quests give 3rep per quest and dailies 22per per quest.
It's nearly impossible for a level 70 to get any reputation towards guild at that level.
To put you into context, my guild is making a level 70 twink project where we will do rbgs/arenas/raids so this will be a global problem.
https://imgur.com/a/kkEX227

**Comment by Drevil-Dion** [comment]
This issue effects all ways to obatain guild rep even quests in the world, MoP made some changes 25% increase to guild rep gains but they atleast detailed the changes the notes of what it was prior to Mists.

[Patch 5.0.4](https://wowpedia.fandom.com/wiki/Patch_5.0.4) (2012-08-28): The cap on weekly reputation gains has been removed. Furthermore, guild experience gains from quests have been increased from 25% of quest experience (17350 guild experience for most level 85 quests) to a flat 60000 experience for every green or better quest and nothing for gray quests. Since guild reputation from quests is based on their guild experience yield (1 reputation per 360 experience before reputation bonuses), this dramatically increased guild experience from quests, from ~48 at level 85 (and significantly less at lower levels) to 166-167 (before reputation bonuses) at all levels. Guild reputation doesn't automatically reset to Neutral on joining a new guild, now only drops to next level down, Exalted->Revered, Revered->Honored, Honored->Friendly, Friendly->Neutral.

**Comment by UltraNix** [comment]
Formula is given above.
