### ISSUE TITLE
Scrolls/Flasks interraction (Newest update bug)

### ISSUE THREAD

**Issue by triceratopsrider** [gamefreedomgit/Maelstrom#3180]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Scrolls right now can cancel flask effect, even if it has more duration and power.

**How to reproduce:**
Use flask on 300 agility, and then scroll for 100 agility.

**How it should work:**
Less powerful buffs should not be able to override more powerful ones. Less powerful buff should just not apply.

**Database links:**

**Comment by EdyGlockenspiel** [comment]
This bug was also present on Tauri. People would troll with level one scrolls to replace people's flasks. "Less powerful buff should just not apply." It should give an error message "A more powerful effect is already active" And not consume the scroll. The same way if you try and use a low level buff on a higher level player with the same buff like if you cast fort on a max level with it already, it should give the error and just not spend the GCD and mana.
