### ISSUE TITLE
[Guild Perc] Working overtime

### ISSUE THREAD

**Issue by triceratopsrider** [gamefreedomgit/Maelstrom#3183]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Does not work. 

**How to reproduce:**

**How it should work:**

**Database links:**
https://wowpedia.fandom.com/wiki/Working_Overtime
https://www.wowhead.com/spell=83949

**Comment by EdyGlockenspiel** [comment]
Pretty hard to determine if this is working or not since it is a low chance, random effect passive on an already random chance. I will say, after I join a guild on any character I always relog to make sure I have all the buffs since, at least on retail and other pservers I have been on, some times they don't take effect until after a relog. I will say that, at least for me, I have gotten pretty fast skillups on green crafts working my first aid and cooking. But since it is all random I might have just been lucky while lvling my first aid on 2 toons to 470 using frostweave.

**Comment by triceratopsrider** [comment]
What do you mean more info? It has nothing to do with green crafting. It has 10-20% chance. I leveled 2 whole professions, its more than 800 crafts and not a single time i gained 2 skillups per one craft with 10% chance.
Perc is just does not work.

**Comment by EdyGlockenspiel** [comment]
"gained 2 skillups per one craft with 10% chance"  That's not how that passive works. It means when crafting yellow/green skillups your chance to gain a skillup from them is increased as they don't have a 100% chance to give a skillup. It has nothing to do with getting 2 skillups from one craft.
