### ISSUE TITLE
[Throne of the Tides] Ozumat Encounter

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3233]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Adds (except for Murlocs and Blight Beasts) keep tunneling on Ozumat. Also the adds are being spawned in a set amount (Vicious Mindlasher and Unyielding Behemoth only spawn once during the whole encounter).

Unyielding Behemoth doesn't cast Shadow Blast (https://cata-twinhead.twinstar.cz/?spell=83929) at all.

Vicious Mindlasher doesn't cast Brain Spike (https://cata-twinhead.twinstar.cz/?spell=83915) at all.

In Phase 2 (where Blight Beasts and Faceless Sappers spawn) Ozumat doesn't periodically spawn Puddles (https://cata-twinhead.twinstar.cz/?spell=83561).

Blight Beasts don't automatically aggro.

Placing AoE's on the edge of the Room (to hit Ozumat) don't hit Ozumat.

**How to reproduce:**
Engage Ozumat in Throne of the Tides.

**How it should work:**
Adds shouldn't tunnel on Ozumat after attacking/taunting them.

Unyielding Behemoth should cast Shadow Blast (https://cata-twinhead.twinstar.cz/?spell=83929).

Vicious Mindlasher should cast Brain Spike (https://cata-twinhead.twinstar.cz/?spell=83915).

Blight Beasts should automatically aggro.

Placing AoE's on the edge of the Room (near Ozumat) should hit Ozumat.

**Database links:**
Reference Video: https://www.youtube.com/watch?v=SmQ0YTFu61k (8:00 - 13:02)

**Comment by staR1336** [comment]
Checking the issues

Phase1 - The Vicious Mindlashers and Unyielding Behemoths keep attacking Neptulon no matter what. Tanks cannot get their aggro

Vicious Mindlasher Casts Brain Spike correctly, and only that. It doesn't cast Shadow Bolt nor Veil of Shadow (curse on heroic mode) , probably due to the fact that it does not pickup players aggroes and are stuck on attacking Neptulon

Unyielding Behemoth Does not cast Shadow Blast at all - Unknown if due to aggro swap not working or just not working.

Phase 2 

Blight Beasts do not pickup aggro when spawned if Players are not close enough
Blight Beasts also continously cancel and reapply  Aura of Dread  debuff if there are more than one attacking (or standing close) to the player, effectively makin the debuff not stacking up at all (should stacks up double as fast if two beasts are close, for example)

This is actually important for Phase 3, because if these Blight Beasts are still around and giving the debuff, such debuff will empower Ozumat's Blight of Ozumat, the Damage per Second dealing debuff you get once p3 starts, effectively making the party take a lot more damage.

Ozumat Does not cast Blight of Ozumat puddles at all in phase 2. 

In phase 3 ,
Placing AoE's on the edge of the Room (to hit Ozumat) don't hit Ozumat at all as op said.

**Comment by Whatisthisclass** [comment]
Thanks for your work @staR1336

**Comment by varjla** [comment]
I must add something: sometimes the cachhé of neptulon in normal mode, has only 1 item to loot.

**Comment by UltraNix** [comment]
Fixed.
