### ISSUE TITLE
[Throne of the Tides] Commander Ulthok Dark Fissure Placement

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3235]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Commander Ulthok's Dark Fissure (https://cata-twinhead.twinstar.cz/?spell=76047) sometimes spawns under the actual position of the Tank after casting the spell.

**How to reproduce:**
Engage Commander Ulthok in Throne of the Tides.

**How it should work:**
Dark Fissure should always spawn on the position **where the Tank stood** at when Commander Ulthok **started casting** the spell, not the position the tank is at when the cast goes through.

**Database links:**

**Comment by Readie** [comment]
I've noticed this happens if I move immediately as the cast starts. If I wait half a second before moving the slam comes down where I was.

**Comment by staR1336** [comment]
As of Today, this issue seems resolved. i tested the boss while continously moving and it never did follow me with the dark fissure, on normal and heroic.

The only thing i noticed is that sometimes Commander Ulthok is not landing correctly, as he is not breaking the platform in middle, and sometimes he does not land at all.  upon engaging everything is working ofcourse, but the platform that is supposed to be destroyed - Entry: 205542 guid: 222244 - [Doodad_Abyssal_Coral_Chunk_Ceiling01_Break01 X:54.113899 Y:802.044983 Z:805.760986 MapId:643 - So that players have whole room to fight the boss. 

it isn't game breaking, but as it is a time gated encounter it might be troublesome sometimes.
