### ISSUE TITLE
[Deadmines] Helix Gearbreaker - Throw Helix, Oaf Smash and Sticky Bombs

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3245]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Throw Helix never happens while Lumbering Oaf is still alive.

Oaf Smash (https://cata-twinhead.twinstar.cz/?spell=88300) puts the Player at the end of the Line instead of making him jump away after crashing. On the Path of Oaf Smash the Player that is picked up also triggers all the Sticky Bombs on the way.

Sticky Bombs spawn way too quick and too close to each other.

**How to reproduce:**
Engage Helix Gearbreaker in the Deadmines.

**How it should work:**
Throw Helix should happen regularly while the Lumbering Oaf is still alive, enabling Players to deal damage on both Helix and the Oaf throughout all Phases.

Oaf Smash should make the Player jump/fly away after crashing. On the Path of Oaf Smash the Player that is picked up **should not** trigger any Sticky Bombs that are on the way.

Sticky Bombs should spawn slower and more random.

**Database links:**
Reference Video: https://www.youtube.com/watch?v=hDtJS2F5iLw

**Comment by staR1336** [comment]
https://www.wowhead.com/npc=47296/helix-gearbreaker/heroic-encounter-journal

![image](https://user-images.githubusercontent.com/130247490/236472844-fa3a752a-365b-4ffa-a316-37489ea355ba.png)
Sticky Bombs should NOT explode upon impact, instead trigger a six second countdown after that they will explode.
 
so correction on the report: On the Path of Oaf Smash the Player that is picked up will trigger the bombs along the way, just instead of exploding right away and possibly killing the player, they get triggered and in 6 seconds they will explode. (they keep exploding automatically after 18s of no interaction)

Everything else Whatisthisclass reported is right,

 no Throw Helix, a phase where we can damage helix while he latches onto a random player

so, sticky bombs being thrown too fast - they do not trigger any countdown, instead explode on impact. 

Player grabbed by Oaf Smash does not get knocked back aftert the smash into the log. (the oaf does)

references 

https://www.youtube.com/watch?v=hDtJS2F5iLw
https://www.youtube.com/watch?v=T5Tb6u292fk

Video proof 
https://youtu.be/xL9IAjm7SCo
