### ISSUE TITLE
Tremor totem

### ISSUE THREAD

**Issue by Hailelune** [gamefreedomgit/Maelstrom#3254]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
unable to use Tremor totem  WHEN **intimidating shout** ( warrior's fear) casts into SHAMAN in target or focus

**How to reproduce:**
Use Intimidating shout in shaman target and after let him use tremor totem

**How it should work:**
whenever shaman got fear effect from **Intimidating shout**, he has to be able to use **Tremor totem** to break it

**Database links:**
https://www.wowhead.com/classic/spell=5246/intimidating-shout
https://www.wowhead.com/classic/spell=8143/tremor-totem

**Comment by ussj10** [comment]
When it comes to case of shaman being a target - that's how it should work. "Cowers in fear" and "intimidated" are 2 different effects. On wiki the tooltip of the debuff in later expansions switched "cowers in fear" to "disoriented" but that's how it worked already back in cata. That's why targets of warrior's fear break from even slightest dmg put upon them (just like other disorient effects), while his aoe effect fear as well as all other fears in the game have a dmg bar to break.
It's a shame SkillCapped deleted many of their old videos because one of their warriors even included it (advise to always target shamans while fearing) in his arena tips.

**Comment by UltraNix** [comment]
Fixed.
