### ISSUE TITLE
Major Feral (DPS) Number issues missing from 4.2

### ISSUE THREAD

**Issue by msh2038** [gamefreedomgit/Maelstrom#3307]
![image](https://user-images.githubusercontent.com/104918750/235770524-7e9ec448-d05f-4e45-a58b-b266971371b0.png)
Potential missing 15% buff, 35 energy when it should be 25
![image](https://user-images.githubusercontent.com/104918750/235771113-7d3c2643-7998-4950-af77-1d45dec55027.png)
![image](https://user-images.githubusercontent.com/104918750/235771244-d210ed7d-e556-43fd-896d-949a61435216.png)
Savage roar is correct
![image](https://user-images.githubusercontent.com/104918750/235771303-f4b43f52-49a3-4e17-8fac-c29adedabc21.png)

Source
![image](https://user-images.githubusercontent.com/104918750/235770873-da5e12d7-c247-4dc0-9ff1-a66055db9e38.png)

https://wowpedia.fandom.com/wiki/Patch_4.2.0#Druids

Nothing changed in 4.3 so these are the last major changes to feral dps and theyre mostly wrong.

**Comment by Sketish** [comment]
Hi,
All of those things you listed are clientside issues, as example from coreside ravage is using 950% instead of  what tooltip says 625
![image](https://user-images.githubusercontent.com/122209088/235871567-74b5ea46-8a2b-4bb7-9831-0303f739cced.png)
We won't be changing client tooltips since it will lead to custom client. Blizzard just messed up with tooltips.
