### ISSUE TITLE
Sweeping strikes Warrior talent

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#3540]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Sweeping Strikes does way to much damage right now, how it scales is completely bugged and it has no ICD.

**How to reproduce:**
Try stack 2 targets next to eachother, have a warrior pop Recklesness,  On use trinket, sweeping strikes, use colossus smash and and then bladestorm and u will see for urself.

**How it should work:**
It should have an ICD i believe and it shouldnt make u able to kill 2 people 3 times over.

**Database links:**

**Comment by Sketish** [comment]
Please provide any proofs

**Comment by BalanCV** [comment]
There is no need for sweeping strikes to have ICD since the amount of attacks you are able to do is limited by GCD anyway.
Most you can do during 10sec SS is 6 abilities + around 3 autos + few heroic strikes if rage allows you.
Popping SS right before Bladestorm will actually reduce your overall damage because only your auto attacks get swept during Bladestorm, as such you sacrifice sustained damage for a lil bit of increase in burst (combo which you can do once per 5min anyway)

Regardless, this would be considered a balancing issue rather than bug related one.

**Comment by Kenniflopper** [comment]
Well considering you can autoattack while in bladestorm its bugged af, also the amount of dmg u do to 2nd target is bugged

**Comment by UltraNix** [comment]
@Kenniflopper @BalanCV Still valid?

**Comment by UltraNix** [comment]
Should be okay after recent fixes to SS.
