### ISSUE TITLE
Auto attacking in Warrior bladestorm

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#3541]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
You can autoattack while in bladestorm right now by spamming /startattack and/or /cast auto attack while in bladestorm

**How to reproduce:**
Look above

**How it should work:**
You should not be able to autoattack while in bladestorm

**Database links:**

**Comment by BalanCV** [comment]
This is not a bug!
[https://imgur.com/a/d2nhLLX](url)
Just by reading the ability tooltip you can see "you cannot perform any other ABILITIES"
Bladestorm always let you use autoattacks during it, the idea behind it is so that the ability doesn't accidentally become a rage block.

Further proof if needed:
[http://www.wowgold.hk/us-server/an-evaluation-of-the-capstone-talents-for-the-arms-and-fury-trees.html](url)
As stated in the beginning of the article "While the Warrior can not use any other abilities while using Bladestorm, the Warrior will still Auto-Attack"
Could most likely find more links if i start digging but cba.

**Comment by Manpower99** [comment]
Bruh this isnt even a bug, this is how bladestorm always behaved.
