### ISSUE TITLE
Omnotron - Issues with Arcanotron

### ISSUE THREAD

**Issue by Lycadd** [gamefreedomgit/Maelstrom#3647]
1st issue:

Arcanotron sometimes does not cast his shield ability Power Conversion

**How to reproduce:**
https://www.warcraftlogs.com/reports/gZyXJHkNvCG1hPbL#fight=3&type=casts&hostility=1&source=23&view=events
He used it only 1 time on 3 activations in this fight

**How it should work:**
Everytime Arcanotron has 45 energy he should cast power conversion on himself

**Database links:**
https://www.wowhead.com/spell=79729/power-conversion

2nd issue :

Arcanotron uses the spell Power Generator on a random friendly target instead of himself

**How to reproduce:**
https://www.warcraftlogs.com/reports/gZyXJHkNvCG1hPbL#fight=3&type=auras&pins=0%24Separate%24%23244F4B%24casts%241%240.0.0.Any%2442166.0.0.NPC%24true%240.0.0.Any%24false%2479624&spells=debuffs&hostility=1&ability=91556&view=events
We can see on these logs that Arcanotron sometimes uses Power generator under Magmatron or Toxitron

**How it should work:**
Despite what the spell tooltip says, Arcanotron only put the power generator pool under himself
Sources : watch any old footage of omnotron

**Database links:**
https://www.wowhead.com/spell=79629/power-generator

**Comment by Polynomix** [comment]
About 1st issue : I was looking at logs and i realize that the only time arcanotron did use his shield was when the Arcane Annihilator right before was not interrupted, and it made me think that maybe the reason why it does not use his shield is because he is silence from an interrupt on Arcane Annihilator. Every logs i have from Omnotron show the same thing.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/9cc28e0d-7d22-491c-9e89-2c412c0326c9)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/3b114b47-bcc1-4e26-a12e-ceddf9c2497e)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/503bfc54-aeeb-4d37-9796-f6bf1414920d)

**Comment by Afgann** [comment]
fixed
