### ISSUE TITLE
Ret Paladin Templar's Verdict is doing way too little damage.

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#3665]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Templar's Verdict damage after the 4.1.0 patch update is doing like 6000-7000 damage in PvP which is kind of ridiculous considering the fact its 351% weapon damage plus Vicious weapon.

I also noticed a couple of other rets noticing the bug.

Can you check the scaling?

**How it should work:**

**Database links:**

**Comment by xmrshoot** [comment]
u use it with 3 holy power?

**Comment by Renehadox** [comment]
> u use it with 3 holy power?

Yep, always...

**Comment by Renehadox** [comment]
Any updates yet???
@UltraNix @Afgann

**Comment by bonfax4** [comment]
What is wrong about it ? Tested with both glyph and crusade talent and both increase the damage properly ?

Verdict does is 2.35x weapon dmg ([235%](https://wowpedia.fandom.com/wiki/Templar%27s_Verdict?oldid=2970147)) before glyph/talents.
![766ea0d4ca3759204dec8e7b039af945](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/17eb96f2-e05b-4d83-8d60-f4ecd194b571)

Glyph + Crusade talent are additive so multiplier becomes 2.35 * (1 + (0.15 + 0.30) =  3.4
![75fa0cbee615afa458edcb03831bbb1a](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/eac2709b-b463-4292-aff5-ec55b98470f0)

My current weapon swing is 4306 with 0 variance with https://cata-twinhead.twinstar.cz/?item=57692 so it's easy for testing against lvl 3 dummy which has very low armor.
![6af1fcc6b4dea420d826776e0cc05de4](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/7686d7e4-a059-4a0b-b3d6-a9e9a0fea236)


Hit with no talent/glyph = 10096.   Expected 4306 * 2.35 = 10119.1.
![c3e3b92433980cb18c089df807d9da05](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/ca9ffb7a-dc79-490f-b73c-f5ecd66c0fec)

Hit with glyph = 11605.   Expected 4306*2.35*1.15 = 11636
![4f3121e7c56c7d19d92f1a3e09e0ae35](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/4a17e789-62a2-4f84-802d-3469e0ff9f10)

Hit with glyph and 3/3 Crusade = 14640.  Expected 4306*2.35*1.45=  14672.
![1a132af21b6dd859a6a74865bdda0f77](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/27e20617-085a-4054-a7bd-8ce82e6204cd)

Small difference is due to the minimal amount of armor they have but the numbers check out ?

**Comment by Renehadox** [comment]
Bumping

**Comment by UltraNix** [comment]
#5169
