### ISSUE TITLE
[HUD] Unusable buttons all over the game

### ISSUE THREAD

**Issue by varjla** [gamefreedomgit/Maelstrom#3745]
**Description:**
Some buttons got broken (maybe randomly). After 1 or 2 hours of playing, I must always relog, specially after random dungeons, because the hud get some buttons blocked. The buttons do nothing: you click them, the are being pushed and do the button animation, but they do nothing. ¿Maybe related to "lost control" spells, when you cannot move, like blind or mindcontrol?

Some examples: (those happens at same time)
- Recent achievements list is empty.
- Dungeon guide: you click on any boss, but nothing happens. You can change dungeon, but cannot click bosses.
- Quest journal: you cannot abandon or share a quest
- Raid info button 

There is a worse version of this bug, where you cannot open the ESC menu, you cannot join BG or RDF, cannot open character window... you can only do ALT+F4. but I guess that could be SO problem (win 7 here). This happened me once only. but the Dungeon guide and quest journal blocked buttons are daily bassis. (don't confuse with "lost connection" status, where your spells do nothing, npcs doesn't attack you or you write on chat and nothing happens)

**How to reproduce:**
I am testing how. Really don't know exactly what triggers this.

**How it should work:**
Buttons must work always.

**Database links:**
no links

**Comment by Sketish** [comment]
Are you using any UI addons ?

**Comment by EdyGlockenspiel** [comment]
This happens often in pretty much any version of the game. Just type /reload and it fixes it. Happens even on Blizzard servers. This happens because of addons bugging out with the UI, but as some addons are basically mandatory there is no real way around it unless you play with very little addons at all. It also bugs out reforging screen as well some times. Again, just type /reload while in game and it will fix it temporarily until something breaks again. It got to the point where I have a keybound macro just for this, both on pervers and on Blizzard servers.

**Comment by varjla** [comment]
Autioneer or auctionator are giving me some problems, Maybe they are the cause.
