### ISSUE TITLE
Glyph of Mirror Image

### ISSUE THREAD

**Issue by Pornoodemon** [gamefreedomgit/Maelstrom#3837]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
https://cata-twinhead.twinstar.cz/?item=45739
After installing this small glyph . Each of the copies of the mage in the "fire" specialization begins to deal abnormal damage 5-10 k .
![WoWScrnShot_052123_032608](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/217cbe60-1972-43fa-ab85-65f05433da02)
![WoWScrnShot_052123_032739](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/61a2f069-2570-41ba-ad9a-24414ac63844)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by bonfax4** [comment]
Only fire version seems to be broken btw.

**Comment by bonfax4** [comment]
Also Arcane Mirror images are currently not benefitting from owners arcane blast stacks. They're only a dps gain because of this interaction. (They should ignore their own stacks and only benefits from the player's stacks ) https://www.mmo-champion.com/threads/991622-Glyph-of-mirror-image-as-arcane-DPS-Gain/page2?highlight=mirror+image+arcane+blast

**Comment by UltraNix** [comment]
Fixed.
