### ISSUE TITLE
Wrong scaling of healing on BG

### ISSUE THREAD

**Issue by webabey** [gamefreedomgit/Maelstrom#3968]
**Description:**
Hi team! Playing disc priest noticed a huge mismatch in numbers between Skada/Recount and BG table statistics, I know I heal 2 times more that it shows me. Meanwhile, other characters like rdruids and hpalas heal as much as Skada shows. 

Please fix this, I am really embarrassed PVPing since DKs heal more than me.... they are not supposed to though..

**Comment by webabey** [comment]
![Annotation 2023-07-08 020059](https://github.com/gamefreedomgit/Maelstrom/assets/124592894/70db38e3-6b6b-49fa-83ac-224361eef945)

**Comment by webabey** [comment]
![123](https://github.com/gamefreedomgit/Maelstrom/assets/124592894/937fa205-3833-4453-aa0c-c516334ac3ca)

**Comment by Sketish** [comment]
So what are you exactly reporting ? That healing numbers are not counted correctly on bg scoreboard ?

**Comment by webabey** [comment]
Exactly.

**Comment by UltraNix** [comment]
@webabey Does Skada shows overheal/heal as different numbers?

**Comment by webabey** [comment]
@UltraNix Skada shows healing and overhealing as separate tabs. On the screenshot you can see the number only for healing and not overhealing.

**Comment by bonfax4** [comment]
Possibly not counting absorbs ?

**Comment by bonfax4** [comment]
Meant on the bg healing scoreboard. Did you try to subtract absorbed dmg and see if it's any similar? Not even sure if bgs should show absorbed dmg in cata.

**Comment by webabey** [comment]
didn't try. I think absorbed dmg is not counted there

**Comment by bonfax4** [comment]
in 2013 in wowpedia they added that disc heals would be skewed on scoreboards so that does kinda support that bg scoreboards should not account for absorbed dmg. ( Cata was 2010-2012 ). Video evidence would be better but the few videos I've found disc healers are not using meters in bgs sadly.

https://wowpedia.fandom.com/wiki/Battleground?oldid=3112354
"Players should bear in mind when viewing the scoreboard that it represents a very simplistic measurement of performance within the battleground. Invaluable contributions such as [crowd control](https://wowpedia.fandom.com/wiki/Crowd_control), dispelling, buffing and timely intervention or self-sacrifice are not shown. Defenders and flag carriers, while performing a vital role, will frequently rank extremely low on the battleground's scoreboard. In addition, total healing shown includes self-healing and healing of pets, but does not include any absorb effects, which can present a skewed impression of the efforts of healers such as Discipline [priests](https://wowpedia.fandom.com/wiki/Priest)."

**Comment by webabey** [comment]
i see, anyways, i reported about healing, considering absorbed damage is not supported on scoreboards to its full potential, i don't need it to be fixed or else.  just fix the healing thing

**Comment by UltraNix** [comment]
As I can see, Damage Meter counts absorbs into healing tab.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/0e2feb19-294d-41f8-85ae-5dfd457daf0f)
And here is the healing scoreboard from that bg:
![WoWScrnShot_071923_222449](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/8e5ceb6f-6150-470f-80db-c595df273c77)

So priest has done 2.24 mln healin according to DamageMeter.
But if we substract PW:S and Divine Aegis values, then we have 1.7 mln healing, which is the value that scorboard shows.

Skada does the same thing:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/8e39c654-f084-49d0-8035-3f836104efaf)

**Comment by webabey** [comment]
PW:S is counted separately as it actually heals if you are using the glyph (what I do and most priests I guess). So I think this must be included as a healing in the scoreboard but as I see it doesn't.
