### ISSUE TITLE
Camouflage

### ISSUE THREAD

**Issue by djesic** [gamefreedomgit/Maelstrom#4035]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
From the spell tooltip:
```
You blend into your surroundings, causing you and your pet to be untargetable by ranged attacks.
Also reduces the range at which enemy creatures can detect you, and provides stealth while stationary.
You can lay traps while camouflaged, but **any damage done by you or your pet** will cancel the effect.
Cannot be cast while in combat. Lasts for 1min.
```

Currently, there is a an issue where the buff gets canceled on when it shouldn't

**How to reproduce:**

Issuing a pet attack command will instantly cancel the effect.
Casting BM hunter spell Intimidation also instantly removes the Camouflage buff

**How it should work:**

The pet should start moving towards the target, while still camouflaged, only breaking when hitting an enemy.
Intimidation does not do damage, it should not break the spell.

**Database links:**

<https://cata-twinhead.twinstar.cz/?spell=51755>

**Comment by Pornoodemon** [comment]
"Issuing a pet attack command will instantly cancel the effect."
Because it introduces the pet into combat mode.
And any action by you or a pet other than setting traps will break invisibility (regardless of whether it deals damage or not).
This is normal work.

**Comment by djesic** [comment]
The pet does not become in combat when issuing the attack command, otherwise the player would instantly become in combat as well and that is not the case.

> And any action by you or a pet other than setting traps

This is not what the tooltip states, it states damage not action.

**Comment by djesic** [comment]
Eagle Eye is canceling the effect as well, and it should not

**Comment by djesic** [comment]
Flare, Mend Pet and Revive Pet are not breaking the effect, as espected.

**Comment by Pornoodemon** [comment]
There is some kind of proof which abilities should not break camouflage, otherwise no one will fix it at random.

**Comment by powercrystal** [comment]
pet shouldn't get into combat just because you send him on the target=shouldn't break camouflage until he attacks the target.
Hunter's mark for example doesn't break camouflage and that's how it should work,casting Intimidation also shouldn't break camouflage

**Comment by Pornoodemon** [comment]
> pet shouldn't get into combat just because you send him on the target=shouldn't break camouflage until he attacks the target. Hunter's mark for example doesn't break camouflage and that's how it should work,casting Intimidation also shouldn't break camouflage

You misunderstood me =). I meant that we need some kind of proof on the mechanics of this skill on 4.3.4 and what should and should not break camouflage. .And then it will most likely be quickly fixed.

**Comment by djesic** [comment]
I will try looking from some videos, but I'm not 100% sure I'll be able to find this.
It's not really the kind of gameplay someone would put into a pvp video.
I did play retail cataclysm and those were the interactions there.

For now at least, I can keep pointing back to what the tooltip states (`any damage`)

**Comment by Pornoodemon** [comment]
I have some infa (You can build on this) but this is not a proof.
Plus, the translation will be a little crooked.


Camouflage
In the last topic about camouflage, there are a lot of disputes and guesses, I put everything on the shelves:

1).http://cata.wowway.ru/?spell=51755 "Camouflage"
You and your pet blend into the environment, making you untargetable for ranged attacks. The distance at which opponents react to you is reduced. By remaining motionless, you are in a state of invisibility.
Using camouflage, you can set traps, but when you or your pet deals damage, the effect is canceled. Cannot be used in combat. Duration - 60 sec.
Aura:
Cannot be targeted by ranged attacks. Decreased enemy detection radius.

Video from our server http://www.youtube.com/watch?v=-5xuJ7RxjJE

2.1). Camouflage is knocked out by spell http://cata.wowway.ru/?spell=1725 "Distraction" (0.12sec on video)
2.2). Camouflage is not knocked out by spell http://cata.wowway.ru/?spell=1833 "Sneaky trick"
2.3).When activating the accessory http://cata.wowway.ru/?item=73648 "Token of Conquest of the Gladiator of Cataclysm" knocks out of camouflage (0.23sec on video)
2.4) When using two Camouflage Hunters, one can knock out the other with a spell http://cata.wowway.ru/?spell=31615 "Hunter's Mark" (0.29sec on video)
2.5). When ordering to attack a pet, the hunter remains in camouflage (0.41sec on the video)
2.6). When using camouflage, immunity to the traps of another hunter appears, ladders simply disappear (I forgot to film this)
2.7).Does not reduce the distance at which opponents react to you
3.1). Camouflage should not be knocked out by the "Distraction" spell.
3.2). Camouflage must not be immune to the Sneaky Trick spell and must be removed by it
3.3).Camouflage must not be removed when using active-trini.
3.4). On a Hunter in Camouflage, another hunter cannot put a mark.
3.5). When a pet enters a battle, the camouflage must be removed.
3.6). When another hunter gets into a trap, the camouflage must be removed, and the one whose trap must enter the battle.
3.7). The distance at which opponents react to you decreases.
4).22.03.2013
5).from launch 4.3
6).10\10 (please correct paragraph 2.3 first)
7).x25 cataclysm
Proofs
1).http://www.youtube.com/watch?v=PLtq9loNbOM 1.34 The fight starts with a Chip-shot and not with "Distraction"
+
http://eu.battle.net/wow/ru/forum/topic/3888532392 topic where the horn is dissatisfied with the hunt camouflage
2).http://www.youtube.com/watch?v=S9RaC2QopFk
0.58 Prozhat Burst but Camouflage in place
4). About the hunter's mark and the pet's attack, I think proofs are not needed, as well as the hunter's immunity to ladders.

**Comment by Pornoodemon** [comment]
And to be more specific, here it is.
1). Camouflage should not be knocked out by the "Distraction" spell.
3.2). Camouflage must not be immune to the Sneaky Trick spell and must be removed by it
3.3).Camouflage must not be removed when using active-trini.
3.4). On a Hunter in Camouflage, another hunter cannot put a mark.
3.5). When a pet enters a battle, the camouflage must be removed.
3.6). When another hunter gets into a trap, the camouflage must be removed, and the one whose trap must enter the battle.
3.7). The distance at which opponents react to you decreases.

**Comment by bonfax4** [comment]
https://web.archive.org/web/20121028120324mp_/http://www.wowhead.com/spell=51753#comments

> -Sending your pet to attack breaks camo immediately, even before your pet engages.

**Comment by Pornoodemon** [comment]
Everything you would ever want to know about this ability:

-Works on you & your pet.
-Can't be used while in combat, but feigning to drop combat & then casting camo immediately works.
-While standing still, you are stealthed, meaning no one outside your party can see you until they're very close.
-While moving you are, well, camouflaged. People can see you but can't attack you with anything except melee attacks.
-Stealthers can't use any of their stealth-only abilities on you; they have to pop out of stealth to attack you.
-Any damage taken by you, including AOE abilities like Flamestrike, Frost Nova, etc, breaks your camouflage.
-Your pet taking damage, but not you, does NOT break your camouflage.
-Camo is broken when arena games start; you have to use camo AFTER the gates open.
-Laying traps, swapping aspects, using mend pet, reviving your pet, using pet abilities (not attacks), & eating food do NOT break camo.
-Using any attack, dismissing pets & calling new pets DOES break camo.
-Sending your pet to attack breaks camo immediately, even before your pet engages.

Basically, this is an upgraded version of stealth with a 1-minute cooldown. In PvE, you can use it to get into position before the fight and start DPS as soon as the tank pulls. In PvP, you can use it to start off any fight any way you want. Because rogues & ferals can't use any openers on you, you no longer need to camp flare @ the start of an arena match; you can use the flare offensively to try and knock them out while you waltz over to the other team's healer, unable to be attacked until you open.

I think this is a really underrated ability. While it's not something you can use all the time, and it definitely doesn't make hunters a stealth class, you can still use it to get a unique advantage over other players. Plus it means you don't have to go night elf to be invisible, which is sweet, because night elves suck.

Edit:

AND OF COURSE, THE ANSWER TO THE QUESTION EVERYONE WAS WONDERING:

Casting Aimed Shot doesn't break camo.

Yeah, that means you can get off an aimed, use rapid fire, and start charging up your next one, all from stealth.

Edit2: As of 4.1, stealthers can use their openers on you while camo'd. I'm disappointed with the change. That was one of the things that made Camo unique.]
Last edited by [Neazy](https://web.archive.org/web/20121028120324mp_/http://www.wowhead.com/user=Neazy) on 2011/04/29 (Patch 4.1.0)

**Comment by powercrystal** [comment]
Camouflage should reduce the aggro radius to a minimum of 5 yards but it doesn't work on 85,i have downloaded addon RangeDisplay for it and it seems that aggro radius is still the same with and without camouflage
85 vs 85 (no level difference)
https://www.youtube.com/watch?v=MS7TW1mFN_M
85 vs 70 (15 lvl difference)
https://www.youtube.com/watch?v=92admDp50WY

**Comment by Sketish** [comment]
> Camouflage should reduce the aggro radius to a minimum of 5 yards but it doesn't work on 85,i have downloaded addon RangeDisplay for it and it seems that aggro radius is still the same with and without camouflage 85 vs 85 (no level difference) https://www.youtube.com/watch?v=MS7TW1mFN_M 85 vs 70 (15 lvl difference) https://www.youtube.com/watch?v=92admDp50WY

Please report that in new issue this one was for other thing

**Comment by djesic** [comment]
@Sketish can I please get some information on why this was closed?

**Comment by Sketish** [comment]
So provide any retail pvp video that can proof that is a bug

-Sending your pet to attack breaks camo immediately, even before your pet engages.
From same wowhead comment
