### ISSUE TITLE
Bugged NPC's in Sholazar Basin, Northrend.

### ISSUE THREAD

**Issue by heikki2001** [gamefreedomgit/Maelstrom#4038]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
My greetings, I hope your Devs are at a good health.
Today I was planning to start farming the Green proto-drake mount quest chain, now, I'm stuck at a quest called "The Mist Isn't Listening" which is located in Mistwhisper Refuge, Sholazar Basin, Because, I can't even attack the NPC's and neither they attack me.
I highly hope these respectful Devs are able to fix this bug.
-Sincerly Yours, Heikki.
**How to reproduce:**

**How it should work:**
The NPC's of this quest should be killable.

**Database links:**

**Comment by BalanCV** [comment]
This bug happens a few times across the questline, including the last quest where it doesn't matter which faction you pick because you are bugged forever.

Basically if you press U and check reputations with either oracles or furries even if u are hostile the "AT WAR" option is unchecked and greyed out so u can't press it.

**Comment by PanJanuszek** [comment]
fixed by @UltraNix long time ago
