### ISSUE TITLE
Ret Paladin's Communion talent randomly enables/ disables the 3% damage increase.

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4249]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

I have reported this bug 3 months ago and none actions were taken.

The talent that gives 3% damage increase while any aura is active is randomly enabling / disabling by itself and sometimes permanently most notably in arena,  i cant deactivate / activate aura and pay attention for the 3% damage increase while in arena match especially on a high mmr, 3% is damage increase for me and my team mates.

Please fix this asap, its a critical bug, thanks.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Polynomix** [comment]
Do you by any chance play with a Arcane Mage or a BM hunter ?

**Comment by BalanCV** [comment]
People noticed this in raids a lot as well it seems.

**Comment by Renehadox** [comment]
> Do you by any chance play with a Arcane Mage or a BM hunter ?

It doesn't matter i still should get the 3% damage increase it doesn't matter if im in party with arcane mage or BM hunter.

I can't really check my damage increase on my character panel while in a middle of a fight in an arena.

Sometimes the damage increase is lost permanently and u have to disable / enable aura again.

WTB Fix asap...

**Comment by Sketish** [comment]
Record situation when its randomly disabling so we can fix that issue.

**Comment by Polynomix** [comment]
> Do you by any chance play with a Arcane Mage or a BM hunter ?

What i mean is if you track only your communion, it might disappear because the mage or hunt overwrite it with their buff. If you do track general 3% buff then yeah its bugged. This is happening with totemic wrath from ele shaman. I thought it was randomly enabling/disabling until i realized it was because of the lock demonic pact overwriting it.

**Comment by Polynomix** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/b79a2ebc-8817-4c86-92a9-e3d1b1bc3eb7)

This is the uptime of conc aura from our ret on majordomo. It does seems like something's wrong. I dont know ret well but i believe the aura's not supposed to fade periodically like that. (The dk does not have the last gap because he died)

**Comment by Sketish** [comment]
Thank you for helping with finding source of bug

**Comment by Renehadox** [comment]
I do not have the time to explain the bug in details im just gonna copy paste my first bug report about it.

The bug report is made on April 3, 4 months ago...

https://github.com/gamefreedomgit/Maelstrom/issues/2818

**Comment by Renehadox** [comment]
> > Do you by any chance play with a Arcane Mage or a BM hunter ?
> 
> What i mean is if you track only your communion, it might disappear because the mage or hunt overwrite it with their buff. If you do track general 3% buff then yeah its bugged. This is happening with totemic wrath from ele shaman. I thought it was randomly enabling/disabling until i realized it was because of the lock demonic pact overwriting it.

So its from totemic wrath from ele shaman or from lock demonic pact???

From what i see in bgs / arenas its totally random... sometimes u dont even get the 3% at all ( when it gets disabled )

Something is triggering it but i dont know what...

**Comment by BalanCV** [comment]
https://youtu.be/7lt8GTjikK0

Here you go, video proof of the bug. It goes on and off constantly, the buff is unreliable af.
Dungeon comp was Bdk, disc priest, fire mage, ret, and surv hunter.
So that excludes interference with similar buff provided by arcmage or bm hunt cuz there was none. Also no lock or shaman.

**Comment by UltraNix** [comment]
@Renehadox @BalanCV Please - retest it.

**Comment by UltraNix** [comment]
@Renehadox Okay.
