### ISSUE TITLE
rogue killing spree

### ISSUE THREAD

**Issue by alilector** [gamefreedomgit/Maelstrom#4251]
**Description:**
casting killing spree at ragnaros fight put hero into fires.

**How to reproduce:**

**How it should work:**
when u cast killing spree it shouldnt put you in fire. it should put in a position of melee range somewhere

**Database links:**

**Comment by bonfax4** [comment]
Some guy in mmo says theres's up to 5-6 positions you can land with KS on rag. https://www.mmo-champion.com/threads/1006306-Killing-spree-on-Rag?highlight=killing+spree+al%27akir

I've only witnessed 4 but that's because barely any rogue uses it in the middle areas unless there's adds : 

1. Any left side killing spree always lands [here](https://youtu.be/d1TbiAorCgw?t=34) if you are at the left side of it which means its the closest left position, 2nd circle from the left.
2. [right side position 1](https://youtu.be/9SnTIt2I9kk?t=59) 1st circle from the right
3. [right'ish side position 2](https://youtu.be/9SnTIt2I9kk?t=224) 2nd circle from the right
4. middle'ish position [here ](https://youtu.be/d1TbiAorCgw?t=257)

P4 KS seems to properly target the backside of ragnaros on p4 in 4.3+, which goes against what that one guy said in mmo forum, prob hotfixed : 
https://youtu.be/WbqQJTIKy74?t=485
https://youtu.be/WbqQJTIKy74?t=556
https://youtu.be/WbqQJTIKy74?t=675

Before any hotfix, if there was any,  it did throw [this rogue](https://youtu.be/d1TbiAorCgw?t=624) in the left side position from phase 1-3 like the guy described.
