### ISSUE TITLE
Searing Totem Target

### ISSUE THREAD

**Issue by Vatnarok** [gamefreedomgit/Maelstrom#4256]
Searing Totem not prioritizing the target that has Flame Shock on it

Searing Totem should swap to the target that has Flame Shock on it, for Enhancement Shaman this is a game breaker in PVP because of the Improved Lava Lash talent, if we can't stack Searing Flames on the target how could we even use Lava Lash to burst the enemy

**Comment by Sketish** [comment]
Provide any source

**Comment by Vatnarok** [comment]
![WoWScrnShot_082023_180729](https://github.com/gamefreedomgit/Maelstrom/assets/142730851/274b6528-a0b6-4975-87d2-26d2551998c0)

as you can see, the totem is hitting the other dummi, not the one with flame shock

**Comment by bonfax4** [comment]
Flame shocking a target outside of searing range causes it to stop attacking after the changes.

Also from what I've seen in videos priority should be smthing like this when you summon it :

Flame shock or storm strike debuff target ( freshest flame shock prio within this)  >  current target if no debuffs are present ( on summon only )  **>**  locks on random target within range of it until a FS/SS is applied. 

Current way it works is also wrong since you shouldn't be able to switch on the fly unless you resummon, no debuffs are present  or targets run out of range but this version is way better tbf. Could have an impact on pvp tho, extra gcd + extra searing dmg on kill target + not having to worry about searing target at all makes it much easier to tunnel somebody.

**Comment by bonfax4** [comment]
@UltraNix

**Comment by UltraNix** [comment]
These changes are not live yet.

**Comment by bonfax4** [comment]
I tested on ptr few days ago and Flame shocking was changing targets instantly ?

**Comment by UltraNix** [comment]
Not sure if PTR was updated with this change.

**Comment by UltraNix** [comment]
@bonfax4 Could you test it again, this time on live?

**Comment by UltraNix** [comment]
Fixed.
