### ISSUE TITLE
Restoration Shaman - Healing Rain & Earthliving Proc chance

### ISSUE THREAD

**Issue by whothatdog** [gamefreedomgit/Maelstrom#4292]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I was in raid 25 persons - Occu'thar, Earthliving is doing 35% of the Restoration Shaman healing (2nd heal source via Recount)
1st was Healing Rain but Earthliving was very close to it => That’s looked wrong to me.  // that's why I open a bug report and call you to **check it.**

**How to reproduce:**

**How it should work:**
“AoE healing spells have a reduced chance to proc Earthliving Weapon. Healing Rain procs it correctly, but has way lower proc chance than Healing Wave for example.”

**I am not sure how it should work exactly**. I can assume it should work like this:
10 people get healing rain? - 20% / 10 = 2% chance proc.

the worldoflogs link below might not work, but if you somehow can open it
it's from Ultraxion fight when Earthliving was 24.4% healing source from Resto Shaman
I saw logs of Resto Shaman with Earthliving are around 15-20%, when 24.4% is the **highest**.

**Database links:**
https://wowpedia.fandom.com/wiki/Earthliving_Weapon
http://worldoflogs.com/reports/8afmi4a5j261iamr/sum/healingDone/?s=1322&e=1771#%C3%8Brza

**Comment by bonfax4** [comment]
> the worldoflogs link below might not work, but if you somehow can open it
https://web.archive.org/web/20170908215652/http://worldoflogs.com/reports/8afmi4a5j261iamr/sum/healingDone/?s=1322&e=1771

**Comment by amanita199** [comment]
the earthliving healing has more to do with 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129459223/08f641dd-3ad5-457c-af1f-90232d09d3d3)
if the raid consistently drops below 35% then earthliving should be perma up, thats why on fights like chimaeron (u get brought down to 1 hp many times) i don't think anything wrong with it since 20% chance from to proc earthliving wep itself + 80% from this talent, should get the 100%

also none of your WoL work for me

**Comment by whothatdog** [comment]
> the earthliving healing has more to do with ![image](https://user-images.githubusercontent.com/129459223/265099402-08f641dd-3ad5-457c-af1f-90232d09d3d3.png) if the raid consistently drops below 35% then earthliving should be perma up, thats why on fights like chimaeron (u get brought down to 1 hp many times) i don't think anything wrong with it since 20% chance from to proc earthliving wep itself + 80% from this talent, should get the 100%
> 
> also none of your WoL work for me

who the heck is below 35% in fights like Occu'thar?
that make your Earthliving doing 30-35% healing.

even if Ultraxion one of the most AoE fights for Healing
the **highest** ever recorded by WoL was 24.4%.

while most of time it around 15-20%.

The talent is correct for single-healing not for Healing rain and Heal chain.

**Comment by UltraNix** [comment]
Fixed.

**Comment by clam119** [comment]
> > the earthliving healing has more to do with ![image](https://user-images.githubusercontent.com/129459223/265099402-08f641dd-3ad5-457c-af1f-90232d09d3d3.png) if the raid consistently drops below 35% then earthliving should be perma up, thats why on fights like chimaeron (u get brought down to 1 hp many times) i don't think anything wrong with it since 20% chance from to proc earthliving wep itself + 80% from this talent, should get the 100%
> > also none of your WoL work for me
> 
> who the heck is below 35% in fights like Occu'thar, that make Shamans' Earthliving doing 30-35% healing in this server? it's extremely high, probabe duo to no decreased proc chance from AoE heals.
> 
> I just showed on the link above Retail-Ultraxion which is one of the most AoE fights healers (Resto shaman in this case of the report) the **highest** record WoL was 24.4% while the average is around 15-20%. it cannot be that Earthliving in whitemane healing the double amount (30% is x2 higher than 15%, right?)
> 
> The talent is correct for **single-healing** if you use HW/GHW/HS to below 35% target it will proc Earthliving 100% if picked 2/2 points on the talent. but not for **Healing rain** and **Heal chain.** I mean, if the 10/25 group is below 35% or just some of them the talent should affect the HR & HC aswell but still not proc 100% on every 'tick' or 'jump' of HR/CH.
> 
> About Chimaeron, I can link Chimaeron fight movie. But I find it very irrelevant because Chimaeron is a 4.0.3~ patch boss and the Shamans in the movies are probably using 4.0.3~ talents while **whitemane** server is using 4.3.4 talents + I am not sure what was in 4.0.3 and what changed during the Cata expansion.
> 
> Anyway Ultraxion > Chimaeron when it comes to patch 'wise'.
> 
> bottom line: the Earthliving should not has 20% proc chance from each Healing rain 'tick' or Chain 'jump' the chance to proc (as wowpedia's link) should lower for **AoE** heals (HR/CH)
> 
> as I **stated**, I am not certaintly sure how it should work I just 'feel' it proc too often on Whitemane specially AoE fights like I experienced (BH) that's why I am reporting it.
> 
> I call the developers of Whitemane to check the proc chance of Earthliving from Healing Rain & Chain Heal. the proc should not be 20% but just lower (I assumed: it depends on the amount of people standing on the HR and divide the proc-chance per player [assumption2: with I minimum chance that cannot be lower.])
> 
> Twinstar link: https://cata-twinhead.twinstar.cz/?issue=14649#reported-fixes
> 
> "Opravena proc chance z Healing Rain a Chain Healu" - Fixed proc chance from Healing Rain and Chain Heal
> 
> @UltraNix

If you have a Restoration Shaman that a) has the aforementioned talent and b) places it in anticipation of the breath coming into the group, then yes, you will **almost always** have a few people that are below the 35% HP threshold because they don't move and stand there taking damage taking them below that threshold, in which case, yes. It is completely within reason that Earthliving procs and does a majority of the Restoration Shaman's healing, especially if they are reaching the 21.4% haste cap.

@UltraNix Please re-consider this change because there is absolutely no reason that this should have even changed based on random "feelycraft" without supportive empirical evidence.

As the original reporter of this issue has aforementioned: "On WoWHead the AoE heals such as Healing Rain & Chain Heal should have reduced chance to proc Earthliving Weapon". Although, there was a mention of it in thee patch 4.0.3**: Now only has 25% of its full chance to proc from a single hop of Spell nature healingwavegreater [[Chain Heal]]**(https://wowpedia.fandom.com/wiki/Chain_Heal). But, there was no mention of this **at all whatsoever** with Healing Rain.

**Comment by amanita199** [comment]
look at this retail video of chimaeron
https://www.youtube.com/watch?v=1DRjBEXTtIM&ab_channel=Ehehcho
go to 2:20
he had 6 earthliving procs as massacre got cast, he put healing rain down, after that he had 19 procs from earthliving (others were not stacked or were already above 35% which does not guarantee the earthliving application
also occuthar is a boss you usually drop so the other guy's reasoning is invalid
reopen or something but dont push the "fix" unless you saw proof that it should be like that, the guy was right on the chain heal part, but not on the healing rain.

**Comment by bonfax4** [comment]
Thing is even analyzing the video he linked in slow speed, healing rain ticked 2 times ( actually 3 but the latest was too close to the next tick to count )  41 total ( 15 + 26 ) below 35% and only then you saw the ticks going from 4 to 14. This is so far away from a 100% or anything close to that.

**Comment by bonfax4** [comment]
@Ultranix Early cata data I found, could have changed later but you should prob start here with percentages and then compare to any worldoflog that's still available. This would put healing rain at 4,167% (heard blizz tends to round the nearest power of 4 )  and 14.03% < 35% with 2/2 talent. If this doesn't match try the values Sketish found and if those don't match either, try the early mop beta values. Quite possible they could have decided to change stuff later without any reference to it, they do it sometimes.

https://web.archive.org/web/20110216090603/http://elitistjerks.com/f79/t110263-%5Bresto%5D_cataclysm_raiding_discussion/p9/
> So it's a very important talent.
> - You often underevaluated Blessing of the Eternals because "it doesn't increase so much the probability for your chain heal". The probability yes but the expectation of ELW instead of being 0.2 (CHhit*20/4/100) is 0.85 ( CHhit*(80+5)/4/100) when the target is under 35%. It's the same thing for Healing Rain(you just have to divid it by 6 instead of 4). For me it's a must have (you juste have to look the gap of HPS between 0.4 and 0.3 on the chart)

**Comment by bonfax4** [comment]
https://youtu.be/fB0zgYaPctk?t=11s

Think this video pretty much confirms it has to be on the single digit % wise unless this dude was extremely unlucky ofc. It's perfect because he casts healing rain and proceeds to DPS after so other heals won't skewer the procs too much. He does cast riptide every now and then.

His healing rain ticks 7 times per cast ( haste capped ) that lasts about @10 secs give or take depending on haste. Earth living lasts about 12 secs, so on average 6 of HR ticks would count for the 1st earthliving tick right after healing rain ends ( assuming last tick from HR procs would not count for the 1st tick since EL ticks about every 3 seconds ). 

His first healing rain hit 16x6 = 96 target heals with 0 riptides and he only got 2 ticks out of that. Above math should average him about 3 procs if none of them overlapped wich kinda checks out. 

Throughout the fight up until he got green buff you'll see he very rarely got 4 going at the same time when he's casting a mix of HR + riptides only.

https://youtu.be/fB0zgYaPctk?t=11s
