### ISSUE TITLE
Lord Rhyolith Hc stomp dmg

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#4300]
**Description:**
Stomp is supposed to do 35k fire dmg on 10m hc, currently it's doing 45k
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/ec9cc126-94c5-4409-9cbc-fc7409739555)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/e38e57eb-dc2c-4314-adcd-4af66744f6f4)
**How to reproduce:**
Pull Lord on 10 hc and check stomp dmg done to player

**Comment by amanita199** [comment]
should be 35k before resistances

**Comment by UltraNix** [comment]
Wrong descriptions in the journal.
On heroic version it does higher dmg.

https://wowpedia.fandom.com/wiki/Lord_Rhyolith
`
[Hotfix](2011-07-14):
Concussive Stomp damage has been increased on Heroic difficulty.
`

**Comment by Lycadd** [comment]
Concussive stomp was buffed to compensate for an even greater nerf on eruption
![Rhyo](https://github.com/gamefreedomgit/Maelstrom/assets/134816583/370921d4-495a-4fe1-a31c-2c7e41a31ef2)

**Comment by clam119** [comment]
@UltraNix @Sketish Please reconsider opening this as I've checked retail kills after the 14th July 2011, and the base damage of HC Rhyolith's Concussive Stomp is still doing 32,000 - 35,000 damage after the aforementioned "hotfix." 

This first screenshot from November 10th 2011: https://i.ibb.co/VDdpBnf/image.png shows the Holy Paladin that only has Resistance Aura and no prior absorption shields, receives 31435 damage from Concussive Stomp. In addition to this, from the same encounter, in this second screenshot, again without absorption shields & defensive cooldowns, the Holy Paladin takes 34819 damage from Concussive Stomp: https://i.ibb.co/HLS66d1/image.png

The third screenshot from November 3rd 2011 in a separate guild's encounter: https://i.ibb.co/5xBHMdj/image.png shows the Balance Druid that also only has Resistance Aura and no prior absorption shields, receives a total of 32735 damage (25295 taken and 7440 resisted) from Concussive Stomp.

Lastly, the following images show a piece of conclusive evidence that the base 35,000 damage is in fact. The following screenshots are of the journals showing the damage for Concussive Stomp on both difficulties:

1. Normal Version: https://i.ibb.co/Gc7mZZM/image.png --> Which has the "hotfixed" heroic damage of 35,000. But, in reality, the Concussive Stomp damage on normal is significantly lower as shown here: https://i.ibb.co/tcJpy07/image.png where the Concussive Stomp deals 26632 **with** Fire Resistance active from the Shaman's Totem.
2. Heroic Version: https://i.ibb.co/vvsvZw8/image.png --> On the other hand, the value of Concussive Stomp on the journal is correct and reflects blizzlike numbers. 

In conclusion, the "hotfix" on HC Lord Rhyolith's Concussive Stomp was so that the base damage is set to 35,000 before resistance & absorption, and that the value reflected in the journal are blizzlike numbers as evident in the "post-hotfix" changes to HC Concussive Stomp shown in the first-to-third screenshots.
