### ISSUE TITLE
Revert Restoration Shaman "Fix" on Healing Rain 

### ISSUE THREAD

**Issue by clam119** [gamefreedomgit/Maelstrom#4468]
**Description:**
This will be referencing the following [Restoration Shaman - Healing Rain & Earthliving Proc Chance](https://github.com/gamefreedomgit/Maelstrom/issues/4292) 

If you did not have the chance to read my previous message on the GitHub issue above, then please allow me to reiterate that this change is completely unwarranted and should be reverted.

The premise of the previous GitHub issue was on a user's personal opinion and "feelycraft", or essentially that they believe that "something is wrong" with the proc chance of Earthliving Weapon on Healing Rain, and further down the line had mentioned the proc chance of Earthliving Weapon on Chain Heal.

In the previous GitHub issue raised, they had addressed on WoWHead that the proc chance of Earthliving Weapon should be reduced on AoE abilities, which again, was **incorrect.**

The only information regarding the proc chance of Earthliving Weapon on WoWHead's Cataclysm section is cited as follows: Patch 4.0.3a (2010-11-23) - Now only has 25% of its full chance to proc from a single hop of Chain Heal.

As you can see above, there are absolutely no mentions whatsoever about the proc chances of Earthliving Weapon on AoE abilities such as Healing Rain being reduced and divided by the number of players present in the Healing Rain. 

![image](https://github.com/gamefreedomgit/Maelstrom/assets/42842394/cedac42e-07d3-462e-95bf-27b4dd5d4aba)

As you can see in the image above which was on Occu'thar fight post-change is an astonishing 4.5% which is needless to say far below what would be realistic. 

And the following image below illustrates the overhealing of Earthliving Weapon was 3.9%.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/42842394/f8f05c17-3bcd-4c90-85ae-d3a2ea7652b6)

I deplore changes that are made with inconclusive empirical evidence to support its baseless claims that were based on solely "feely-craft" as admitted by the original user of the previous GitHub issue.

**How to reproduce:**
Use Healing Rain in a 25-man setting such as Occu'thar.

**How it should work:**
The Earthliving Proc chance should not be divided by the members currently present in the Healing Rain.

**Database links:**
[Earthliving Weapon](https://wowpedia.fandom.com/wiki/Earthliving_Weapon) - Refer to the Cataclysm Notes and how the only changes present on the proc chance were made to Chain Heal and **NOT** Healing Rain.

**Comment by bonfax4** [comment]
Don't rely on patch notes o  wowpedia for anything, sometimes changes go through without being officially logged. There's also no mention on any change in mop there but in this post you can see the % amounts from a dev in mop beta and healing rain had a reduction. I'm just unsure if these percentages were also like this in cata.

 https://www.bluetracker.gg/wow/topic/us-en/5889309137-beta-class-balance-analysis/


> Earthliving has a 20% base chance to proc, and an additional 80% (additive, total of 100%) if the target was below 35% HP when the triggering heal landed. After that, the chance is multiplied by 0.3 for Healing Rain, and 0.5 for Chain Heal.
> 
> For example, a chain heal on a healthy target has a 10% chance to trigger Earthliving. A Healing Rain tick on a healthy target has a 6% chance to trigger Earthliving.


This might actually require a lot of datamining and then log comparisons to retail logs to see if numbers match.

**Comment by clam119** [comment]
You are being absolutely ridiculous right now @bonfax4  I'm not going to sit here and debate with you and your feelycraft. The patch notes are there for a reason and something as significant as the proc chance of Earthliving Weapon will not be intentionally missed out on the patch notes just because you have a "feeling". 

As you can see, on Patch 4.0.3a the Earthliving Proc chance was adjusted for Chain Healing, and so you cannot sit here and really believe that they would not update anything and announce that the Earthliving Proc chance for Healing Rain being lowered. It's absolutely cynical.

@UltraNix Future reference, please do not push these "fixes" that have not been confirmed with empirical evidence to support its claims because it's just unprofessional and poor performance as a developer.

**Comment by bonfax4** [comment]
Lmao I'm actually advocating to actually test  and see if numbers match lmao. What is exactly feelycraft about that ?

Link a video of healing rain proccing with 100% chance on aoe to prove your claims then. Just search for chimaeron videos and you'll instantly see you're dead wrong and it had a penalty.

**Comment by clam119** [comment]
Incorrect, the original GitHub issue that you had pushed for was the division of Earthliving Weapon's proc chance based on the number of people that were currently inside of the healing rain. Stop strawmanning, I have never mentioned that Healing Rain had a 100% chance to proc. 

I do not care about a bluepost from a developer talking about MoP Beta's Earthliving Proc Chance, I am only concerned with the actual hotfixes that had been made to Earthliving Weapon, in which the entire expansion only had Chain Healing's interaction with Earthliving Weapon changed in 4.0.3a. 

Not going to bother replying to you if you don't see how absolutely dumbfounded you are and how you don't realise the shit that you're feelycrafting is gutting a reasonably performing class because you have no idea what you're reporting.

**Comment by bonfax4** [comment]
I didn't post anything...

**Comment by bonfax4** [comment]
Just following your retarded reasoning of logic, explain the percentages the Blizzard dev actually clarified on that bluepost without any official patch note in Mop smartass ?

**Comment by whothatdog** [comment]
I agree with you, it seems the 'fix' they pushed made it broken.
I left a message there but it is the same as I would say here.
https://github.com/gamefreedomgit/Maelstrom/issues/4292#issuecomment-1710959511

**Comment by Sketish** [comment]
So this issue with be a tough one. Because there are a lot of comments when proc rate was low for EL during healing rain as:

http://web.archive.org/web/20120327131851/www.wowhead.com/spell=51730#comments:id=1395196:reply=247795
Would be nice if you could delete one of your double posts. There's a discussion about the proc-chance on multi-target heals on the  Blessing of the Eternals page. The proc-chance on single-target-direct-heals (Healing Waves) is 20%, with the talent, on 35% targets, it's 100%. Chain Heal has a 5% proc-chance of earthliving, and with the talent it's increased to 21,25%, according to carighan. Healing Rain has an even lower proc-chance, I'd say 2%, but that would need some testing.

http://web.archive.org/web/20120309013758/www.wowhead.com/spell=51555#comments:id=1286065:reply=224240
Could it be that you are seeing the effect of your %-age of Chain Heal / Healing Rain casts? Chain Heal has only a fourth of the normal procchance. This means 5% per target, but it stacks weirdly with this talent: (<basechance> * 0,25 + <extra>) * 0,25. Meaning the total procchance on low-HP targets is 21,25%, not the 25% one would expect if it were a simple *0,25. Healing Rain has again a lower procchance, and I'm not sure what it is but I see ~8%-10% procs from Healing Rain.

http://web.archive.org/web/20120309013758/www.wowhead.com/spell=51555#comments:id=391016
With Cataclysm this also improves Chain Heal's and Healing Rain's procchance of Earthliving on low-health targets, however both of these spells have substantially lower base procchances, and hence will not increase to 100% chance on low-health targets.

https://www.mmo-champion.com/threads/817170-Restoration-Shaman-in-Cataclysm
"Healing Rain (HR, or just Rain)
10130 mana - each tick scales with 8,3% of Spellpower.
This is ground-targetted, and then creates a weird-looking light blue ground target with some liaht healing going on inside it. Due to the nature of it's healing it cannot directly save anyone, but the overall healing effect if people are all stacking up for it is very potent, especially as it gives you a good chance to proc Ancestral Fortitude on someone inside it. The procchance of Earthliving Weapon sadly is reduced, so there is no mass-ELW-potential in it. Still, if you got the mana and you got the bunched up group of people, this is a very powerful heal to fire at them - and you can continue casting while it works, too!"

And then are guides who suggested that it should have higher proc chance like:
https://www.mmo-champion.com/threads/852233-Restoration-Shaman-Guide/page50
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/3adb500e-6fe1-40f5-9a54-6e370d3a2855)

Also when watching retail videos from heavy aoe fight like Majordomo or Ultraxion it looks like :

![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/96c52bf4-0d2a-4792-8305-e3c359cb431e)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/d407b3e6-bbf8-467e-9800-7d2cf57c1957)
When buff prochance sometimes looks like 25%-35%

We would appreciate any help with finding sources and then we can find out a way to adjust proc chance

**Comment by Revly** [comment]
I support reverting, since they reduced Earthliving Weapon, healing with Shaman in Pve is no longer the same...

**Comment by UltraNix** [comment]
Fixed.
