### ISSUE TITLE
You don't need to be in a raid group in order to enter Molten Core

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4489]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently you have to party with someone in order to enter Molten Core.

**How to reproduce:**

**How it should work:**

**Database links:**

https://wowpedia.fandom.com/wiki/Molten_Core

[Patch 4.3.0](https://wowpedia.fandom.com/wiki/Patch_4.3.0) (2011-11-29): [Lothos Riftwaker](https://wowpedia.fandom.com/wiki/Lothos_Riftwaker) will now allow you to enter Molten Core without being in a raid group.

**Comment by Meyzie** [comment]
Technically we are not at patch 4.3. content yet. 

Patch 4.3.0: Hour of Twilight contains the [Dragon Soul Raid](https://wowpedia.fandom.com/wiki/Dragon_Soul) and three new [Caverns of Time](https://wowpedia.fandom.com/wiki/Caverns_of_Time) 5-man heroics, and is the end of [Arena season 10](https://wowpedia.fandom.com/wiki/Season_10). This is the largest content release since the opening of [Cataclysm](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Cataclysm).[[1]](https://wowpedia.fandom.com/wiki/Patch_4.3.0#cite_note-MMO-C_4.3-1)

**Comment by UltraNix** [comment]
Fixed.
