### ISSUE TITLE
[rogue] recuperate and slice and dice

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#4492]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
If there is a buff, it can be replaced with a new one with a shorter duration

**How to reproduce:**
use ability with 4-5 combo point and after with 1 combo point

**How it should work:**
if the new buff from an ability is smaller than the existing one, the ability should be unusable with error

**Database links:**
https://wowpedia.fandom.com/wiki/Slice_and_Dice
https://wowpedia.fandom.com/wiki/Recuperate

**Comment by whothatdog** [comment]
but I could not provide sources to prove it, except that how it works in Twinstar. (Haven't check SnD tbh)
https://github.com/gamefreedomgit/Maelstrom/issues/4389

**Comment by Sketish** [comment]
Waiting for any proof

**Comment by Hermeleen** [comment]
This is more "quality of life" i would say, because rogues tend to press recuperate when they know they got points which can't be spend on kidney/evis/rupture, so by habit press recup. Not on ferals with savage roar, you might want to press it with lower points, just to hope for proc for free cast for example.

**Comment by UltraNix** [comment]
#4389

**Comment by bonfax4** [comment]
@Ultranix 
Necro'ish but he is correct and this is currently how it works on cata classic. It only allows you to use it if it lasts longer than the current duration. You can still refresh a 5 point recuperate with a 1/2/3/4 point as long as the point duration > buff duration and when you do refresh recuperate, you do get an extra tick  from the last recup (+3sec). Same for slice and dice, minus the tick interaction since it's not a hot/dot.
