### ISSUE TITLE
[MAGE][BLINK] Blink Malfunctioning since last FL patch

### ISSUE THREAD

**Issue by Alleyn321** [gamefreedomgit/Maelstrom#4502]
Description:

Blink Ability Concerns:

There are several issues with the Blink ability that need addressing:

Charge Interruption: When warriors perform a charge, it applies a 0.5-second ministun effect ( talent ) . Ideally, I should be able to use Blink to escape this effect. However, currently, I am unable to do so. This gives warriors a significant advantage over mage players, as they can swiftly follow up with additional spells to disrupt my abilities.

Inconsistent Blink Range: The Blink ability's range appears to be inconsistent. It frequently teleports me only 1 meter, accounting for roughly 65% of my gameplay time, which is not consistent with its intended functionality.

Ineffectiveness Over Hunter Traps: Blink does not work effectively over hunter traps. There is a 0.5-second delay before the trap activates, theoretically allowing me to Blink away from the trap's location. Unfortunately, regardless of whether I attempt to jump while using Blink or not, I remain in the same spot. This situation significantly favors hunters, as I am unable to escape the trap's effects. Currently, my only option is to circumvent the trap by walking around it before being able to Blink forward. This lack of escape options makes it challenging for me, as a fire mage, to engage hunters effectively, ultimately resulting in rapid defeat due to the absence of defensive capabilities.

Water Ineffectiveness: Blink also fails to function properly in water. Regardless of whether I attempt to jump and Blink or stay in the water and Blink, I find myself inexplicably reappearing in the same spot. This issue further limits my mobility options and hinders my ability to navigate and engage effectively in aquatic environments.

Obstacle Challenges: Blink ability doesn't work over fences, stairs, or other areas where natural walking is not possible but jumping is required. Consequently, I cannot jump over these obstacles and then Blink to a new location. This limitation becomes problematic in fast-paced arena scenarios where time is limited, often leading to situations where I become stuck in place and are at a significant disadvantage, frequently resulting in my defeat.

How to reproduce:

To replicate this issue:

Simply follow the instructions outlined in the description above and test it out in-game. Please note that you may need to play the game for an extended period to observe these problems. It's important to mention that these issues may not be readily noticeable to regular players, so testing in this manner may not yield significant results.

How it should work:

The Blink ability should function as follows:

The Blink ability should not be influenced by player movement.
It should reliably teleport the caster 20 yards forward, unless obstructed by solid objects such as walls, mountains, doors, and unjumpable fences.
Additionally, using Blink should grant the caster immunity from stuns and bonds.
After using Blink, the caster's movement speed should be boosted by 60% for a duration of 2 seconds.

Links to the video 

Link 1 https://streamable.com/tup3nh 

Link 2 https://streamable.com/8imcrx

Link 3 https://streamable.com/ajoo5v 

Link 4 https://streamable.com/qf1kuq

Keep in mind that these links expire in two days. But I have evidence saved on my machine and I will try to record more. Thank you

**Comment by Alleyn321** [comment]
( Not my report i was told to post this )

**UPDATE: There was no ISSUES before last FL Update 2-3 Weeks Ago**

Just thought this info would help

**Comment by SimonBpvp** [comment]
+1

**Comment by whothatdog** [comment]
I haven't **investigated** Blink behavior Blizzard too much tbh, so if I may with all due respect (I might mistake here)

on Twinstar that how Blink work on water surface:
if the character is not a bit deeper in the water it Blink you in place.

Note the difference (the first photo is has more 'blue' [Blink animation] because it blink in place)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/2561776a-e19d-4b38-84c6-6ffd756131b8)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/828fc075-a00b-4379-8325-329f9fd3fcc9)

Twinstars changelog
"Blink will properly teleport on uneven surfaces, and will no longer fail unless the height difference is too big".
https://cata-twinhead.twinstar.cz/?issue=3052#reported-fixes

about Blink gives **60% speed for 2 sec**, I don't remember the ability work like this.
isn't it work like this only with 'Improved Blink'?
according to Talent Calculator I use (Twinstar one) It should give **70% for 3 sec** (2/2)

**Comment by MrTide** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/4501

**Comment by Afgann** [comment]
fixed
