### ISSUE TITLE
[MAGE] Living Bomb + Pyroblast DOT refresh bug

### ISSUE THREAD

**Issue by lukasani94** [gamefreedomgit/Maelstrom#4526]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In 4.3.4, refreshed DOT auras should always have +1 tick. Furthermore, the duration of the refreshed DOT aura should always be base duration + time remaining to next tick. 
This is not the case with Mage DOT spells Living Bomb and Pyroblast DOT. Take a look: 

[https://i.imgur.com/m4UzlOE.png](url)

Ticks only 4 times, should be 5. And regarding new duration, I had a tick at .26, refreshed at .28, next tick should've been at 29, but it's at 31.

I tested some other classes like Feral Druid and it seems only Living Bomb + Pyroblast DOT are affected? 

**How to reproduce:**
1. Cast Living Bomb or Pyroblast on Training Dummy
2. Refresh Living Bomb or Pyroblast DOT
3. It doesn't get +1 tick
4. The new duration doesn't follow the rule of base duration + time remaining to next tick

**How it should work:**
Refreshed Living Bomb and Pyroblast DOT should have 5 ticks, not 4. 
The duration of the refreshed Living Bomb or Pyroblast DOT should always be base duration + time remaining to next tick. 

**Database links:**
N/A

**Comment by Sketish** [comment]
Cant open imgur link + provide any retail source

**Comment by lukasani94** [comment]
It is easiest to provide examples of other DOT auras functioning correctly on Whitmane. Below I'll attach an example of Rake and Moonfire. They follow the normal behavior for auras in 4.3.4, as expected:
1. ALL refreshed DOT auras always have +1 tick.
2. The duration of the refreshed DOT aura should always be base duration + time remaining to next tick.
3. The time between ticks should not be interrupted or restarted when refreshing a DOT aura.

Here is a regular application of Moonfire on Whitemane, 6 ticks:
![Wow-64_2PNTiREeLA](https://github.com/gamefreedomgit/Maelstrom/assets/22174375/096ab7b9-c986-4715-bb55-01264429ca0e)

Here is a refreshed application of Moonfire on Whitemane, 7 ticks (+1 tick rule on aura refresh is followed correctly):
![Wow-64_I6ArTuvsAZ](https://github.com/gamefreedomgit/Maelstrom/assets/22174375/33fb4a4b-e6b7-4b64-a246-ca84ad2409bd)

Here is a regular application of Rake on Whitemane, 3 ticks:
![Wow-64_EJex7bq5kz](https://github.com/gamefreedomgit/Maelstrom/assets/22174375/ebed515b-7b59-4b81-8fda-2ca20c8315c0)

Here is a refreshed application of Rake on Whitemane, 4 ticks (+1 tick rule on aura refresh is followed correctly):
![Wow-64_5ZIzF7ldsz](https://github.com/gamefreedomgit/Maelstrom/assets/22174375/e58eb3a3-7d04-4b6f-8ca1-b958cd017a16)

Here is a refreshed application of Living Bomb, an extra tick is not added, it should tick 5 times, but only ticks 4. Also first tick of the new application should tick at .29 not at .31 in this example
![Wow-64_ehUtXvKNjr](https://github.com/gamefreedomgit/Maelstrom/assets/22174375/9d3a1074-2616-421c-a496-24a43cdfa9ce)

Here is a refreshed application of Pyroblast DOT, an extra tick is not added, it should tick 5 times, but only ticks 4. Also first tick of the new application should tick at .47 not at .49 in this example
![Wow-64_QPWfnVzlxV](https://github.com/gamefreedomgit/Maelstrom/assets/22174375/23df349f-9e01-46b6-b0ad-644295bb966d)

**Comment by BalanCV** [comment]
Living bomb is one of the few dots that are not meant to be refreshed. You are supposed to let it run out before applying a new one. I think in original it didn't even let you refresh it.
About pyroblast I can't say but make sure to calculate the leftover damage from previous dot because it might roll into the new dot instead of adding an extra tick.

**Comment by lukasani94** [comment]
Well whether it's meant to be refreshed or not doesn't change the fact that it doesn't function as intended. You could definitely refresh Living Bomb in original, you can also refresh it (and it functions correctly) on Apollo. 

Regarding Pyroblast rolling, it does not.

**Comment by bonfax4** [comment]
> Living bomb is one of the few dots that are not meant to be refreshed. You are supposed to let it run out before applying a new one. I think in original it didn't even let you refresh it. About pyroblast I can't say but make sure to calculate the leftover damage from previous dot because it might roll into the new dot instead of adding an extra tick.

Yup, you should not refresh it but it should still behave like other dots if you do. 

If proof needed https://youtu.be/1tX64eLakrs?t=358
Made sure i clipped at a point he had no temporary haste buffs  ( because haste can increase/decrease max duration up to half a tick duration ) and you see a living bomb applied with @12 sec duration and refreshed into 13 second duration with the same conditions @ 6:15.

**Comment by bonfax4** [comment]
> Living bomb is one of the few dots that are not meant to be refreshed. You are supposed to let it run out before applying a new one. I think in original it didn't even let you refresh it. About pyroblast I can't say but make sure to calculate the leftover damage from previous dot because it might roll into the new dot instead of adding an extra tick.



Yup, you should not refresh it but it should still behave like other dots if you do.

If proof needed https://youtu.be/1tX64eLakrs?t=358
Made sure i clipped at a point he had no temporary haste buffs ( because haste can increase/decrease max duration up to half a tick duration ) and you see a living bomb applied with @12 sec duration and refreshed into 13 second duration and the tick still going off with the same conditions @ 6:15.

**Comment by UltraNix** [comment]
Fixed.
