### ISSUE TITLE
Soulwell ( healthstones )

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4542]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
It despawns after like 5 people take it?

**How to reproduce:**
summon it in a raid and have people spam take healthstones

**How it should work:**
it should have like 25 stacks?

**Database links:**

**Comment by Hermeleen** [comment]
It is because it either tries to give you more than one each time ( you can see that when you press it, it says "you can only carry one" multiple times. OR, because each time you click it even if you already have healthstone, it subtracts one from the well.
In bgs you can keep clicking soulwell and it will disappear very fast.

**Comment by UltraNix** [comment]
Fixed.
