### ISSUE TITLE
Druida Huargen - mision Fuego Lunar

### ISSUE THREAD

**Issue by bourchip** [gamefreedomgit/Maelstrom#4603]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
La mision fuego lunar de la raza de los huargen esta bugeada, te pide subir al nivel 3 y ya llegas a esa mision con nivel 5. Te pide usar fuego lunar contra Huargen Colmillo de Sangre, pero al usarlo no te la toma como completada.

**How to reproduce:**
Debido a la cantidad de experiencia que uno gana, llegas a esa mision con nivel 5 y no con nivel 3 como te lo pide

**How it should work:**

**Database links:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/145870979/cf0cbd85-7098-44ed-a78a-90dd048ac752)

**Comment by Sketish** [comment]
Translate to english

**Comment by alandav11** [comment]
Hola, pudiste solucionar este bug?

**Comment by ThiagoMel** [comment]
The moonfire mission of the worgen race is bugged, it asks you to go up to level 3 and you already reach that mission with level 5. It asks you to use moonfire against Bloodfang Worgen, but when you use it it does not take it as completed.

How to play:
Due to the amount of experience one gains, you arrive at that mission at level 5 and not at level 3 as requested.
