### ISSUE TITLE
[QA Run] Dragon Soul - 10 Normal / Heroic

### ISSUE THREAD

**Issue by Waroxx-QA** [gamefreedomgit/Maelstrom#4629]
**ENTRANCE TRASH MOBS**
------------------------

Troops event doesn't work, Troops should start moving and killing trash mobs on sideways as soon as you kill the first two Elementals in the middle

All trash have wrong melee damage.

Twilight Portal doesn't spawn adds, but the closest Twilight Portals to the temple have some adds already spawned.

**Morchok**
------------------------
Looks fine, to be tested in group.

After killing Morchok, Troops should move to the temple ( event ) and it's not working actually
both drakes that should take people to zonozz and yorsahj are not working because of this event that is not happening.

**Zon'ozz**
---------------------
You cannot click on the drake in the temple so you can't get there. ( event bug )

Void is spawning as soon as you pull the boss and that's incorrect

Void is not bouncing at all, void mechanic should be re-worked.

**Yor'sahj**
-----------------------
You cannot click on the drake in the temple so you can't get there. ( event bug )

Trash mobs are missing their color buff.
[Dark globe](https://www.wowhead.com/npc=57382/dark-globule#abilities;mode:lfr) ( trash one ) is spawning *Forgotten one* ( boss's dark globe adds ) and that's wrong. it should deal shadow damage only ( as it's mentionned on wowhead )
![WoWScrnShot_091923_163358](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/27cfd758-ea8b-4c13-8f04-2bc902f88561)

**Boss fight**
Mana void should have a bigger melee range
Forgotten ones are spawning the wrong way, timing and positionning, sometimes spawning in the air literally.
![WoWScrnShot_091923_164441](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/e685937b-c94e-405a-a0c4-dc6d8c693fe5)
Sometimes spawning on the ground but they don't do anything and they're not even attackable. Trying to charge them but they are Out of Range or Target not in line of sight
![WoWScrnShot_091923_164410](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/de0567f5-f1fb-42ac-b80e-cf1ebe73fc56)
They don't disappear if you kill the boss or after a wipe.
![WoWScrnShot_091923_164441](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/711b6670-c504-488f-a9e9-28e57f51420d)
(This was after the kill)

**Hagara**
----------------------
Pre-boss trash...
The portal should disappear on both hagarra plateform, and the other one on the top of the temple, as soon as you click on the globe to start the trash event. it should reappear after a wipe or after killing Lieutnant Shara
Trash mobs does insane melee damage, to be checked, i had like 114k melee hits from stormbinder adept.
Tornades ( Tornado stalker ) from Stormbinder adept are doing 1 dmg melee hits, they shouldn't melee at all
Frozen Grasp from Lieutnant Shara is always spawning on her, and is moving, following and doing melee damage to players, and that's wrong.

Boss fight...
Focused assault is not doing any dmg. and since it's based on melee damage, here are some damage numbers with 0 armor. ( 10 Normal ) :
![WoWScrnShot_111623_160150](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/22975e87-c19a-4b52-b51f-e89a187102f8)

Ice lances not working at all
Frozen Tempest : Ice wave speed is too high in normal mode, and it's RANGE is bigger than normal, it hits you even if you are inside hagara's water bubble. people should be able to avoid it without having to go 8ft inside the bubble.
![WoWScrnShot_091923_171453](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/59fe79d9-e6f4-4f51-a943-1e24750c3c26)

**Ultrax**
----------------------
Pre-boss trash event ( Thrall : Ultraxion Trash ) : Working but the event speech takes a long time to start.
Boss summoning event bugs out after finishing  the trash, the boss doesn't get summonned, after killing trash it should start Ultraxion entrance event taking everyone to the twilight realm and the boss should appear.
( i could get it summonned using some gm commands )
When summonned, Ultraxion doesn't move to the position where he should be, he stays far from the temple, and is only attackable if you go to the edge of the plateform.
![WoWScrnShot_091923_181357](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/2c8b2f6b-60dd-405a-9007-8fec034a3cc9)
All forms of charges are not working actually, should be working.
I got two debuffs ( maybe cuz i was alone ) but make sure this shouldn't happen on a 10man group.

**Warmaster**
---------------
Doable, to be tested in group.

**Spine**
-------------------
Roll range is too small, and the roll mechanic doesn't work, you get thrown on a roll even if you are standing on a hole ( attached to his back ) 
After getting the amalgamation to 9 stacks and get it exploded, the burning tendon appears and it's attackable, but the animation of the tendon opening is missing and it looks like it's closed.
![WoWScrnShot_092023_002058](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/62442194-da73-4de2-9faf-eb74b8cc781e)
Wiping, then going back to the top of the temple ( wyrmrest summit ) and getting on the Ship, talking to the png "Swayze" on that ship should teleport you you to the Skyfire Deck only, actually it activates Spine directly. Spine fight can be started from Skyfire Deck only.
Boss loot Cache is missing after killing the boss.

Teleports on the entrance are not working.
![WoWScrnShot_092023_001508](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/df28a318-5227-40eb-87c3-e709e4f9564a)

**Madness**
---------------
Doable, to be tested in group.
Missing nameplates on Blistering Tentacles.

**Comment by xmrshoot** [comment]
ice wave speed its too fast, you cant run from it

**Comment by Sketish** [comment]
9.11.2023 Update

Entrace

1.When players hit first mob nearby NPC's should start assault
2.Image of Tyragosa RP is missing + sometimes mobs run through textures under road
https://youtu.be/YQM4xewSmuM?t=5

After Killing Morchok

1.Players are unable to click on drakes to assault Warlord or Yor till NPC's arrived
2.This drake shouldnt' be availble untill bosses are dead on both sides
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/a6e534fd-1612-4a4c-b2c9-d8dcecfaa9b7)
3.NPc's are running in place
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/275985e6-4b5b-415c-a7fa-a163d313903f)
4. After killing Yor or Warlord players shouldnt be able to click again on drake leading to this boss
https://youtu.be/rnoRUUcz1PY?t=264
 
 After killing Yor + Warlord
 1.Players can click multiple times on drakes
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/e6b3a3ff-8de2-42a1-b6ab-3a21b6de19d4)
2. Blue vortex shoudlnt appear at all
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/836b81e6-cf2b-43f6-b12e-ccd2fef04d16)
retail:https://youtu.be/-_XT0QohPLc?t=438
ptr:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/0eb3fdc3-bdaa-4d95-b69f-35f0abe6f293)

Hagara doesnt land on the ground after RP
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/2497630f-661d-49ad-a7ca-75609f9258d7)

**Comment by Waroxx-QA** [comment]
**UPDATE**

**Entrance Trash Mobs**
------------------------------
0.3k melee hits from **Ancient Water Lord**
![WoWScrnShot_111823_013244](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/bd260394-42ef-4706-9bb8-23f46dc8b897)

1 damage melee from **Earthen Soldier**
![Uploading WoWScrnShot_111823_013337.jpg…]()

**Yor'Sahj**
--------------------------

Keeps the yellow globe buff ( Glowing Blood of Shu'ma ) forever
![WoWScrnShot_111923_013132](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/76cc04a1-a594-442e-8569-a3149cb0ee2d)

Players also get the buff, and it stays even after killing the boss lol.
![WoWScrnShot_111923_013159](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/1c277d0d-81d3-461c-82db-572347ea64ef)
![WoWScrnShot_111923_013521](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/8cabceed-db49-4bfb-a771-d321d0c596f3)


**Hagara**
-----------------------------------

Missing [Icicle](http://cata-shoot.tauri.hu/?spell=109315) on the ice phase.

[Ice Wave](http://cata-shoot.tauri.hu/?spell=105314) is a bit fast actually, people should be able to outrun it in Normal mode.
The damage range of Ice Wave should be re-checked
![WoWScrnShot_111923_020120](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/430dcacb-886a-418f-af93-5aa14f3984db)
Players shouldn't get hit by the Ice Wave inside Hagara's water bubble.

**Comment by UltraNix** [comment]
Melee damage will be corrected later.

**Comment by Sketish** [comment]
21.11.2023
 
 Trash 10n
 
 Ancient Water Lord
 https://www.wowhead.com/npc=57160/ancient-water-lord#abilities;mode:h25
 Flood is channeled on players but deals no dmg or miss on player
 
 Earthen Destroyer
 35-40k per hit after armor reduction so basic dmg must be around 80-85k
 Earthen Soldier
 20-25k per hit after armor reduction so basic dmg must be around  55-55k
 Twilight portal
 IT should summon this add every fes seconds
 https://www.wowhead.com/npc=57259/twilight-siege-breaker 
 When portal is killed it's chaning to infernal
 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/420148f6-2a7b-414d-9464-f1ea114829b4)

 After Killing Morchok all remaining trash before temple should despawn
 https://youtu.be/UX4a-rTKS2Y?t=170
 
 Warlord Zon'ozz area
 
 https://www.wowhead.com/npc=55416/eye-of-gorath
 Shadow Gaze is only casted once
 https://www.wowhead.com/npc=55417/flail-of-gorath
 Melee dmg 20-25k after reduction
 Sludge Spiew is not casted at all + Wild Flail pushback is nearly noticeable
 https://www.wowhead.com/npc=55418/claw-of-gorath
 Buff melee dmg to 50-60k so about 100-120k basic
 It should be casted every 2 seconds if noone is in melee range
 Also whole packs claw+3flails+eye should be linked and immune to pushback/grips
 |
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/d9f2c7bb-79c4-4031-bde5-5cc767c4e4c0)

Yor area
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/8164a3ab-8235-468d-8c19-220a6f979946)
all trash mobs are running together cant test
https://youtu.be/KESWy8a--OM?t=1473
Should be moving around in groups of 3

Trash before Hagara 

https://www.wowhead.com/npc=57823/stormbinder-adept#abilities;mode:h25
Tornados currently is following hsi caster, it should be moving around caster
https://youtu.be/KESWy8a--OM?t=3124

https://www.wowhead.com/npc=57821/lieutenant-shara#abilities;mode:h10
 Orbs from Frozen Grasp are barerly griping 

Ultraxion trash event

Fire spreading is very weird its spreading widely instead in single straight way
Also fire left by dragon should despawn after 3-4 secons after taunting drake insted of instantly after being taunted

**Comment by Sketish** [comment]
21.11.2023

Warlord Zon'ozz
1.Void of the Unmaking - basic orb hitbox is a little too big

Hagara
If someone dies during trash event the whole event is reseting - trash should only reset when whole group is dead

1.Boss should follow tank during Focused Assault
2.Ice Lance mechanic is not working correctly is other player is standing between missle and player both players are getting dmg + debuff
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/3a3adb3d-c437-4bcf-8837-2ab7d600cc80)
3.Focused Assault should hit tank fort about 25-30k

Frost Phase
3.Icicle is not being casted at all
4.Players can run through ice wave without getting dmg + sometimes ice wave goes into textures
https://cdn.discordapp.com/attachments/1087141276840890399/1176508735368216646/image.png?ex=656f2024&is=655cab24&hm=031b369284039d2643614abb675ae8bac879061df0f283176a7bace9d17f4f9d&

Ultraxion

1.If tank is not in melee range boss should swap to any target in melee
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/4d88492d-d672-48cc-be85-eb39b67d24c8)
2.Gift of Life should spawn 2 mins into fight
3.Boss should reset after cast of Twilight Eruption

Warmaster Blackhorn
1.Charges are not working on both type of adds
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/09d548dc-f9da-4256-87b2-30ff9706190b)
Also Degeneration and Brutal Strike is dealing no dmg and is casted very rare

Spine of Deathwing

1.There is no raid warning if boss is stable/ planning to roll left or right
2.Boss is not reseting after whole group wipe
https://cdn.discordapp.com/attachments/1149340426071965766/1176616164500185159/image.png?ex=656f8432&is=655d0f32&hm=f73c55d7c25e507d8ec12d68ccada78e17298121cdaceb2511893f478d2c70b2&
3.Grasping Tendris is not being applied to players
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/7e277516-298c-4cf2-83b5-57fa3a7284e5)
4.There is huge issue with LOS on fight, after killing plate there is still los in place were was previous plate so most of the time players cant cast
5.In blizzard up there is special bar which is counting stacks on add
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/5d6d9ef9-bc72-4b84-b76d-0e856acb13b5)


Madness of Deathwing

1.This tentacle shouldnt be visible before boss pull
https://cdn.discordapp.com/attachments/1149340426071965766/1176618838700343316/image.png?ex=656f86af&is=655d11af&hm=e03d8a5e8bc203c3f14481de50850387c4742ac150c06e8c2d8eb2992f0e1798&
2.Boss is geting buff from aspects
https://cdn.discordapp.com/attachments/1149340426071965766/1176618839404978226/image.png?ex=656f86af&is=655d11af&hm=a651adfc79f1e9c4955aeed62dc0481e726e2206804b33d60a2fcb9175716474&
3.Elementium bolt damage when he is pulsating looks very low or is decreasign too fast
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/326ae3fd-98e1-40c6-9dce-ca5ece218275)
4. Adds are fixating on Kalecgos making them evade and unable to kill
5.After killing each limb boss should lose 20% of hp, currently he had 60%+ entering p2 + there should be warning that boss fall on Ysera platform
6.Corrupted Blood is not being casted at all+ should be raid warning
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/68c85efb-0ab7-4403-b3a2-96111a03abd0)

**Comment by Waroxx-QA** [comment]
**TEST RAID - 28/11/2023**

**Morchok**
---------------------------

- [ ] The Earth Consumes You! — Morchok uses the power of the earth to draw all players to him, inflicting 5% of their total health as Physical damage every sec. for 5 sec.
People should be gripped and not able to move or cast anything for 5sec, it's working but some people are not getting that sometimes ( not gripped / can hit the boss ).


**Drakes that takes you to Zon'ozz and Yor'Sahj are bugging players in the air when they drop them, Parachutes are hitting players(melee) and acts like a pet that is unfriendly to everyone.**


**Zon'ozz**
-------------------
**Void of the Unmaking** ( ball ) bouncing is scuffed, it goes sideways even if you hit it in the middle, and its cast timer after the black phase is too fast
Tank shouldn't get **Disrupting Shadows** debuff.

**Yor'sahj**
------------------------
Green buff is not splashing / dealing damage to players.
Purple stacks are scuffed, [This is a list of what gives and doesn't give stacks on purple debuff](https://www.mmo-champion.com/threads/1106062-Healing-Yor-Sahj?p=16159938&viewfull=1#post16159938)
Forgotten Ones should disappear if you kill the boss before you kill them.

**Hagara**
----------------------

No Portal after pre-boss trash / before starting the boss, portal should should spawn as soon as you kill the last add before the boss
Last add before the boss (Lieutnant Shara) [Frozen Grasp](https://www.wowhead.com/spell=109305/frozen-grasp) should grip not only one but ALL PLAYERS.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/f2a502b7-ae3c-4646-b833-eca3d8782214)
Boss didn't cast Water Shield, Hagara should always teleport herself to the middle and cast water shield when switching to Lightning or Ice phase.

If you ress someone who died from [Watery Entrenchment](https://www.wowhead.com/spell=110317) he shouldn't get the debuff.

"Whenever she casts [Focused Assault](http://cata-shoot.tauri.hu/?spell=107851), move out of her immediate frontalcone area; either by moving backwards or sideways.In the event that you cannot do this in time, be prepared to use a defensivecooldown." from Tauri Veins, Tank should be able to avoid Focused Assault by moving backwards or sideways ( ONLY ON NORMAL MODE ), and boss don't move with the tank when she casts it. 


**Ultraxion**
--------------------
Pre-boss trash event : All drakes are getting released at the same time. they should get released one by one, killing everyone and killing Thrall, So you can't run it again.
NPCS/Event should reset if EVERYONE dies.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/6f1af45b-3006-4a18-9666-53bd56008ea4)


**Warmaster**
------------------------
Twilight Sapper timers are incorrect. ( we got double sappers in less than 10s )
Warrior and Feral Bear Charge should work on Drakes when they are gripped to the ship, rogue's killing spree should work on the drakes and keep you on the ship.
After killing the last two drakes, Warmaster shouldn't jump on the ship directly, he should fly with Gorionna to the ship then jump on it.
When he jumps on the ship, half of Warmaster's body was under the texture, and Gorionna's visual is bugged, she's giving her back to the ship.


**Spine**
-------------------
Roll machanic isn't happening at all.
Fiery Grip from [Corruption](https://wowpedia.fandom.com/wiki/Corruption_(mob)) shouldn't happen on the tank.
Burning tendon Opening Visual is bugged, first tendon isn't opening at all, when you open the 2nd tendon, the first tendon visual appears. same for the third.
Warriors and Bear should be able to charge the Burning tendon.

**Madness**
-------------------------
Charge (Warrior,Bear) should work on All Arm Tentacles and Corruption on each plateform
Hemorrhage Spawn is delayed.
Hemorrhage are evading, players are not able to kill them.
Elementium Bolt Visual when it dies looks like it hit.
Players are taking too much damage from **Burning Blood** especially on the last plateform ( the first one on the right) we couldn't survive even with t13 HC gear.
Phase Two:
[Elementium Fragment](https://wowpedia.fandom.com/wiki/Elementium_Fragment_(mob))'s Shrapnel cast should give a debuff on players that shows that they are targeted, and it gets removed when the cast ends, and it should be visible on the raid UI.
[Elementium Terror](https://wowpedia.fandom.com/wiki/Elementium_Terror) are evading.

**Comment by Sketish** [comment]
10 hc test 5.12

Morchok hc looks ok

Yor
Boss is not casting Digestive Acid during green buff
If there is combo blue+yellow only one ball should be summoned

Zonooz
-melee dmg is way too low ,rest looks ok

Pre Ultraxion event - they shoudlnt pull like that
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/520e2358-ec70-4772-8c3c-123a2b6c3747)

Warmaster Blachorn
Broadside is not casted at all
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/ce206337-cd55-4cfb-9050-b8773f0fe408)


Spine of Deeathwing
1.System that check how players are counting wrong when player are at edges
2.Visual is still bad here
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/92e85944-29ea-487f-a872-a1f804cbfa9b)
3.After klling 2nd plate players are unable to move forward
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/814eb3cd-cc04-484c-a42a-942d5d70a66d)

Madness of Deathwing
1.When Corrupting Parasite is beign spawned it fall under textures
2.Corrupting Parasite has buff from kalecgos
3.Mobs are still agrroing on Kalecgos ( dmg source should be player)
4.Congealing Blood has buffs from aspects
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/ad366353-e71f-4905-9480-816117187e67)

**Comment by Sketish** [comment]
7.12.2023

Morchok hc 
1.Resonating Crystals should be spawnign in front of each boss instead of random around bosses.
2.Earth'vegeance is interrupted radomly and stops when player is close to the boss
https://youtu.be/IX967tL21l4?t=91
Warlord Zon'ooz
Looks ok

Yor the Unsleeping
Sometimes trash before boss is grouped up instead of going in groups of 3

When is combination of:
1.Yellow+Blue only one ball should spawn, currently two are spawning

When flying to Hagara, drakes sometime randomly attack players
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/21f2b3b1-6f28-4de1-907f-127d12c0ba4c)

Hagara
1.Focused Assault is interrupted if tank move away from boss

Frost Phase
1.When Frostflake is dispelled under bubble the pool shoudnt spawn on the ground
"One possible strategy is to have targeted players enter the Watery Entrenchment Icon Watery Entrenchment and be dispelled there. They will take a few ticks of damage, but this should be manageable and the Frostflake Snare will be out of everyone's way (currently, dispelling Frostflake inside the Watery Entrenchment prevents the Frostflake Snare from being created). Another possible strategy is that targeted players move to the edges of the platform to be dispelled, though this means that other players need to be careful and stay away from the edge."

Lighting Phase
1,This conduit/gameobject should be moved a little bit so 2 players can move lighting to this one from both sides
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/244ee0e7-ab73-4fa3-8003-9243d3aded14)


Ultraxion
1.Warrior was unable to charge to ultraxion
rest looks ok

Post Ultraxion cinematic
Aspects+ Thrall should move to gunship
https://youtu.be/gwkPiyYB_c8?t=584
https://cdn.discordapp.com/attachments/368446147066462219/1182269304289370152/image.png?ex=65841517&is=6571a017&hm=e7eb8d29655327485d2ced55e63c03b47c40a5f5ce27787173e63cda912b37a7&

Warmaster Blackhorn
1.Goriona is not casting Broadside each wave
2.Twilight Onslaught is not caulcatign dmg correctly, When I entered solo I took whgole dmg and ship took 0.
3.Goriona should land on gunship when reach 90% currently its between 80-85%
4.Also sometimes she is flying on the ground which makes hard to position boss correctly

Spine of Deathwing

1.When players are entering tendrils they should be counted toward Deathwing roll. currently if they enter tendril zone boss wont do roll.
Rest of the fight looks ok

Madness of Deathwing

1.Deathwing and his Limbs bar should be displayed.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/03b339aa-b148-42f4-adde-a47371bad789)

2.Parasites sometimes spawn under textures
3.Warriors werent able to charge on far left/right platforms
4.Corrupting Parasite has buff from kalecgos
5.Mobs are still agrroing on Kalecgos ( dmg source should be player)
6.Congealing bloods also have buffs from aspects

**Comment by Sketish** [comment]
12.12 Update

Morchok
1.Kohcrom should spawn at 90% HP, Bosses are healing during the black phase, Kohcrom is bugging / resetting while/after the black phase i guess that is what makes him heal and so morchok get healed too as their HP is mirrored.

Yor trash

1.After flying on drakes, parachutes start attacking player
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/10348766-8a92-42b0-b3b3-fee7a482d1db)
2.Pack mobs are stacking
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/a4012439-7576-4594-85aa-55f0ce8f127f)

Yor
1.Digestive Acid ( green debuff ) shouldn't miss on players.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/ec01ddcc-f139-4a20-9f35-4575ed93b191)

Hagarra Trash mobs :

1.Tornades are getting stuck and doesn't move to the player who has the debuff

2.Lieutnant Shara's ability Frozen Grasp shouldn't spawn behind the Lieutnant, it should spawn randomly around, Each frozen grasp should grip only one player at a time but it should be able to grip any player and not keep gripping the same players

Hagara
1.Boss shouldn't go undermap if you take her to the edge
![image](https://github.com/gamefreedomgit/Maelstrom/assets/122209088/3eda797d-ffa5-4686-acdb-498f43160644)

2.Frost phase : Frozen Patches left from the debuff should despawn after getting out of the frost phase, and if you dispell a debuff after the end of the frost phase it shouldn't leave a patch.

**Comment by Potatwowo** [comment]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)


**Description:**
Spine
1.1 Fiery Grip breaking takes too much damage in order to happen (more than 300k which is around half of its 801k health pool).
1.2 Spawns of Hideous Amalgamation and should not be instant upon killing the Corruption.

Madness
2.1 Damage from Elementium Bolt hitting the platform is really low. 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/154066913/e2dece46-0a98-4e85-a168-5329dc6b8071)
![bolt hit](https://github.com/gamefreedomgit/Maelstrom/assets/154066913/5a890071-b9cd-4cc2-8652-51d548794e0b)

Zonozz
3.1 Dispelling Disrupting Shadows is making the player jump forward instead of knocked back.

Hagara:
4.1 Ice wave model is too big and rotating too fast.
4.2 Ice lances are applying debuffs that are not stacking when you get hit by another Ice Lance. Instead that makes you have 2 or 3 different debuffs each having their own stacks that wipes the raid as shown here and the target switching seems to not work properly:
![lances](https://github.com/gamefreedomgit/Maelstrom/assets/154066913/38b5e4bf-6103-4ec8-8fb9-1471cfffda9a)
4.3 Ice tombs should make the target immune from all external damage which is not working as people are dying from Ice Lances while in the tomb:
![tombs](https://github.com/gamefreedomgit/Maelstrom/assets/154066913/44248ecc-6fb0-45a4-af08-36bcc7c78cf7)
4.4 Focused Assault is not dealing enough damage tanks survived while not using Icebond/Survival Insticts:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/154066913/528759ee-5793-4149-a7cc-09a3e3042524)


**How to reproduce:**
1.1 Engage in Spine encounter, wait for Fiery Grip to be casted.
1.2 Kill Corruption on Spine.

3.1 Let the Bolt hit the platform, nobody dies even if they stand close.

4.1 Get dispelled while having Disrupting Shadows

5.1 Engage in Hagara encounter, wait for Frost phase.
4.2 Engage in Hagara encounter, wait for Ice Lances.
4.3 Engage in Hagara encounter, wait for Ice Tombs.
4.4 Engage in Hagara encounter, wait for Focused Assault.


**How it should work:**
1.1 Grip should break after 160k damage is done to it or 20% of its max HP as per the provided links and the video: https://youtu.be/48FcvNtZP0Q?si=cZ4T_Hns_aJ5P2C3&t=5416
1.2 Spawn should be delayed by few seconds as in the video: https://youtu.be/48FcvNtZP0Q?si=Teu44NQWBBtvSu5P&t=5495

2.1 Hit should deal 46k damage which is reduced by spell resist and other buffs: https://youtu.be/48FcvNtZP0Q?si=isE5Zvlf0H2vEb72&t=6970

3.1 Dispel should knock you back as shown here with warrior getting dispelled: https://youtu.be/48FcvNtZP0Q?si=tB8pWJHJ3dzNgvbo&t=199

4.1 Rotation speed of Ice Wave: https://youtu.be/48FcvNtZP0Q?t=1710
4.2 Players should be having only 1 debuff while getting stacks from different Ice Lances and the group should not be instantly killed when they start dealing damage to players: https://youtu.be/48FcvNtZP0Q?t=1756
4.3 Players in Ice Tombs should only receive damage from it while they are immune from all other damage sources: https://youtu.be/48FcvNtZP0Q?t=1743 
**Database links:**
1.1 https://cata-twinhead.twinstar.cz/?npc=57880 , https://www.icy-veins.com/wow/spine-of-deathwing-strategy-guide-normal-heroic, 
1.2 No database entry available for this.
2.1 https://www.icy-veins.com/wow/madness-of-deathwing-strategy-guide-normal-heroic, https://cata-twinhead.twinstar.cz/?spell=109601
3.1https://cata-twinhead.twinstar.cz/?spell=103948
4.1 No database entry available for this.
4.2 https://www.icy-veins.com/wow/hagara-the-stormbinder-strategy-guide-normal-heroic, https://cata-twinhead.twinstar.cz/?spell=105316
4.3 https://www.icy-veins.com/wow/hagara-the-stormbinder-strategy-guide-normal-heroic, https://cata-twinhead.twinstar.cz/?spell=104448
4.4 https://www.icy-veins.com/wow/hagara-the-stormbinder-strategy-guide-normal-heroic, https://cata-twinhead.twinstar.cz/?spell=107850

**Comment by Waroxx-QA** [comment]
16/12/2023 - **DS HC TEST RUN**

**Morchok**
---------------------
Players shouldn't be able to cast behind the pillars on the black blood phase.

**Yorshaj**
--------------------------------
Mana void should drain your mana even if you are standing in africa, actually if you run far from it, it doesn't drain your mana.
and Druid's mana should be drained also when he's on Cat/Bear form.

**Zonozz**
----------------------
Add a small delay to the black phase damage / add spawn when the void touches the boss, around 2-3 seconds after the ball touches the boss.

**Hagara**
-------------------------
![WoWScrnShot_121723_164238](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/674e9f4c-8011-4249-a9a9-8e542fad6380)
Ice Wave shouldn't hit you here, as soon as you get the debuff of the water bubble you should be safe.
Lightning phase damage is too weak.
Ice tombs shouldn't be immune to bleeding damage.

**Ultraxion**
------------------------
We got only one set of Fading Light debuff, should be casted three times, each time on boss's target + two random players (dps). heals shouldn't get the debuff.

**Warmaster**
----------------------------
Half of Warmaster's body is under the ship sometimes when he lands on the ship.
Gorionna should disappear after a wipe.
Trash charge should be visible even if they charge on melee.
Warmaster and Gorionna melee damage is too big and not healable.
Gorionna threat is buggy.
Gorionna should fly out at 20% of its HP.
Check timers for drakes/add of the third wave, feels like they came out too fast.

**Madness**
---------------------
Corruption's Crush isn't dealing 130k dmg or its cone is not matching with it's visual
Tank shouldn't get Parasite.
Bloods should regenerate their hp every 10s.
Check spellwave damage ( Should inflict 20k per attack/ability to all enemies in a range of 6 yards EXCEPT the current target )
Bolt visual is broken af, it should start getting slowed right before the edge of the time zone, and it should be smooth, it looks like it has 400ms. on the last plateform ( Kalecgos plateform ) the bolt should land faster and the damage of the impact should be bigger. ( The impact only,  ticks damage is fine )

Head phase ( Phase two )
Head is taking half of the plateform, the model should be moved to the edge so ppl can see the whole plateform.
Bloods are slow, and they're not healing the head when they reach it ( each blood should give deathwing 1% HP if he touches the head, and dies instantly ( actually dropping to 1hp then taking some time to despawn )
Please check if "Corrupted blood" damage is working properly

**Comment by Whatisthisclass** [comment]
> ## **Morchok**
> Players shouldn't be able to cast behind the pillars on the black blood phase.

As far as I know casting behind a pillar LoS'd just fine. Tried casting Death Coil behind a pillar yesterday to test it and it didn't let me because of LoS, so I guess it should be fine. 
You should be able to cast "behind" pillars though, if you are standing in between two (sweetspot between those two where there is no object LoS) as you can see here at 1:00 https://www.youtube.com/watch?v=H7Bd5CR9Jqs#t=1m Spriest starts casting in the sweetspot between two pillars.

> Head phase ( Phase two )
> Head is taking half of the plateform, the model should be moved to the edge so ppl can see the whole plateform.
> Bloods are slow, and they're not healing the head when they reach it ( each blood should give deathwing 1% HP if he touches the head, and dies instantly ( actually dropping to 1hp then taking some time to despawn )
> Please check if "Corrupted blood" damage is working properly

Also Head Hitbox is broken, Melees need to be very close to hit Death Wing and can't move too far from the center of the hitbox. We needed to be almost inside the Head to actually hit it.
Take a look at 13:05 here for reference https://www.youtube.com/watch?v=65GtZcqoyns#t=13m05s .

**Comment by Waroxx-QA** [comment]
Ultraxion's Fading Light [Mechanic](https://youtube.com/clip/UgkxQro4N8Unh2QT_CXcmIx-2ns9ZynhyAiY?si=4iJyRkHUmZ4oXAtK)

**Comment by UltraNix** [comment]
Fixed.
New bugs place on separate, new reports.
