### ISSUE TITLE
Swoop hunter pet talent

### ISSUE THREAD

**Issue by Asirie1** [gamefreedomgit/Maelstrom#4635]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Your pet swoops at an enemy, immobilizing the target for 1sec, and adds 25% melee attack power to the pet's next attack.

**How to reproduce:**
It does the animation but nothing else

**How it should work:**
It should immobilize the enemy like wolfs charge for 1s and enhance its next melee dmg

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=52825

**Comment by djesic** [comment]
It's the same issue as with hunter pet Charge from non flying pets

If your pet is not engaged in combat and the first command you issue is Swoop/Charge, the spell will go on cooldown, use focus, your pet will a 'mini charge' in place but not connect with the target and then just idle from there.

To me it seems that there is no '/petattack' component to this spell that makes your pet engage the target. Could it be caused by pet Passive stance?

**Comment by UltraNix** [comment]
Fixed.
