### ISSUE TITLE
[Hunter] Pet talents bug

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#4679]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When you swap from Bm to Survival or viceVersa, the pet talentes are reseted, and u need to do put points again in them and its annoying and sometimes you forgot and get low dps. Watch Screenshots

**How to reproduce:**
swap between BM and survival specs, i think on MM its the same problem

**How it should work:** Talents should remain saved

**Database links:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/f3f45032-a37e-4144-939e-dc81829d654b)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/128bb73c-7441-4b03-9ec0-162e6af35445)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/baf91afc-f79d-4e39-abd8-f2f6cc155809)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/56bc7064-7c5a-4ac7-899d-d08b51e02d5f)

**Comment by xmrshoot** [comment]
Edit : and the pet spells in pet bar are also reseted(u have to put them again , like add one and remove another)

**Comment by TheHate123** [comment]
I think that's how it's supposed to be, it's because of the extra points from Beast Mastery's final point talent. Otherwise you'd respec and have extra points on the specs that aren't BM. Unless you're claiming that the game is supposed to remember the talents from the other spec, which I don't think it does.

**Comment by djesic** [comment]
Working as intended. This was retail behavior

**Comment by bonfax4** [comment]
> Working as intended. This was retail behavior

Think this was retail wotlk behaviour not cata. Cata pets had their own talents per spec. I'll try to look for video proof but this will be hard.

**Comment by djesic** [comment]
I mean it might just be a nice QoL update if it turns out you can't find anything that confirms this.

**Comment by bonfax4** [comment]
https://www.mmo-champion.com/threads/961903-Switching-talent-specs-from-BM-gt-MM

"Yeah. Dual Specced. The same pet will have different talent builds for each of your specs."

**Comment by xmrshoot** [comment]
so its not a bug, i will close it

**Comment by djesic** [comment]
No, this is a valid report, the pets should have their talents remebered for each spec (BM / non-BM)

**Comment by bonfax4** [comment]
Not sure if he can reopen now. 

@Sketish

**Comment by bonfax4** [comment]
Found a decent videos that clearly shows difference in pet skills between bm and surv

https://youtu.be/SI4eGS_LDEQ?si=agLv3jQWYuHA0Bjg
https://youtu.be/-4NedIWbgGE?si=W5adpa9EISLxN0O7

You can confirm he only has 4 pets on the beggining of part1 so he's not summoning different pets and his turtle in survival spec has a different pet bar skills than his turtle on bm spec. At [a point](https://youtu.be/-4NedIWbgGE?t=3m3s) he even shows the turtle bm spec pet talents on part2 and you can see it's fully talented (  no resets or extra points to set ). You can also see his turtle procs culling of the herd in survival spec part1 but his pet talents in bm don't have culling talented since he went full tank.

**Comment by UltraNix** [comment]
Cannot reproduce it.
