### ISSUE TITLE
Tank Sachel reward bugged in party

### ISSUE THREAD

**Issue by GJKnOcKOuT** [gamefreedomgit/Maelstrom#4739]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When i try to queue in dungeon in hr cataclism as a tank in a party with a friend of mine I see the sachel as a reward, as soon as we find a dungeon the sachel is not listes in the reawards and you don't recevit at the end, only by dismissing the party you can see it again and if you join a party again the same thing happens.

**How to reproduce:**
we were 2 as soon as I invited him and joined dungeon when the dungeon is found the sachel is not a reward, and when you dismiss the party it gose back being a reward

**How it should work:**
it should not bug out and give you the reward

**Database links:**

**Comment by Sketish** [comment]
Need any proof for satchel being a reward when queueing as group

**Comment by GJKnOcKOuT** [comment]
Im gonna take a screen recording when i get home showing the issue

**Comment by Whatisthisclass** [comment]
Satchel is not rewarded if you're queuing in a premade group. It's a reward for solo queuing highly demanded roles. It never worked with premade queues, since it wasn't intended for those.

https://wowpedia.fandom.com/wiki/Patch_4.1.0#Dungeon_Finder:_Call_to_Arms

"[...] To be eligible for the additional rewards you must solo queue for a random level-85 Heroic in the role that is currently being Called to Arms, and complete the dungeon by killing the final boss. Every time you hit these requirements (there is no daily limit) you'll receive a [goodie bag](https://wowpedia.fandom.com/wiki/Satchel_of_Exotic_Mysteries) that will contain some gold, a chance at a rare gem, a chance at a flask/potion, a good chance of receiving a non-combat pet (including cross faction pets), and a very rare chance at receiving a mount."

**Comment by UltraNix** [comment]
As above - CTA does not work in groups.
