### ISSUE TITLE
[Priest] [Talent] Lightwell - not clickable

### ISSUE THREAD

**Issue by djesic** [gamefreedomgit/Maelstrom#4767]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/34022788/8fb75078-e6dc-4217-a0f3-5777e5252f28)

**How to reproduce:**
Not sure, but I can't click my own Lightwell here
I had 6 charges left on it, no Lightwell buff active on me.

I suspect that it could maybe be that I lost the buff from taking damage and then for some reason I was prevented from clicking it?
**How it should work:**
Should always be able to click it if I don't currently have the buff

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=724

**Comment by Hermeleen** [comment]
I suspect two things. Either there is some internal timer preventing spamming lightwell, and you "somehow" lost the buff but the internal timer was still on. ( in which case there wouldn't be anything bugged with lightwell, but with the thing that made you lost buff, because i don't think you can spellsteal it ) Or Second possibility, Since i see you got both nameplates on, is it perhaps possible that the lightwell, even tho unclickable, got somehow destroyed and just left the object on ground? thinking that, only because i don't see lightwell nameplate.

**Comment by djesic** [comment]
The internal timer is kinda present, it's a duration of a GCD before you should be able to reaply the buff on yourself
Buff is lost when receiving too much damage, it's in the tooltip of the spell - although it is magic and subject to dispell
Lightwell is not targetable by enemy players and can't be killed, also it doesn't show up as a friendly nameplate.

**Comment by Hermeleen** [comment]
i dunno, but i definitely can see the lightwell nameplate. i don't use any addons for nameplates.

**Comment by djesic** [comment]
Well, you can see in the tooltip that it has 42/42 HP so, it's alive and kicking.

**Comment by Hermeleen** [comment]
you are right, only as enemy nameplate.

**Comment by djesic** [comment]
It keeps happening and I have the suspicion that it's the 30% of your hp part of the tooltip that is messing with this.

It should remove the buff, but not prevent you from clicking it to reapply

@Sketish

**Comment by Hermeleen** [comment]
yep, confirmed, i just now have it too. definitely has to do with other priest lightwell, there are two here , literally next to each other, and i can  only click his.

**Comment by UltraNix** [comment]
Fixed.
