### ISSUE TITLE
Trinket gives no stats and has bugged hidden cooldown

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Maelstrom#4894]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Edit:**
As bonfax said below the same thing also happens when you are not in LoS of the target you are dealing damage to when it procs.

**Description:**
When using Hellfire pre-pull in order to proc a mastery trinket, my other trinket Darkmoon Card: Volcano will not proc or give any buff or stats, but will still have a hidden 45 second cooldown.

**How to reproduce:** 
Equip Darkmoon Card: Volcano, cast Hellfire for a few seconds, then try to get the trinket to proc using other spells.

**How it should work:** 
Presumably it should proc as normal since the text reads "When dealing damage with spells", but I don't know how it would have behaved in retail.

**Database links:**
https://cata-twinhead.twinstar.cz/?item=62047
https://cata-twinhead.twinstar.cz/?spell=70283

**Comment by bonfax4** [comment]
Equipping trinkets should trigger icd. That's normal behaviour.

**Comment by SimonBpvp** [comment]
Yeah you’re probably equipping it with your macro so yeah ICD gets triggered?

**Comment by NickZedd** [comment]
That was my first thought. I am not using any macro to cause this effect and also the cooldown is 45 sec whereas equipping it causes a 30 sec CD.

**Comment by NickZedd** [comment]
I am also not changing trinkets or swapping my trinkets around.

**Comment by bonfax4** [comment]
I see what u mean. You don't even need to proc another trinket,  the issue seems to be with hellfire self inflicted dmg. I tested outside and while in combat and if hellfire does not hit a target the situation you described happens, an icd is triggered with no buff.

**Comment by Pornoodemon** [comment]
I play a warlock myself and I have this trinket.
In a normal situation, when there is no CD for proc, the trinket works with 1-2 hits at the beginning of the battle
But there are quite a lot of problems with this trinket. Sometimes it just seems to stop working, and does not work for 2-3 duels for 5 minutes, which is theoretically impossible given the fact that the CD is reset before the duel
There is definitely something wrong with the ICD and the problem is not just “hellfire”
I think this concerns some part of the DOT effects since I don’t use hellfire and this happens regularly. By the way, it was because of this problem that I stopped using this trinket.
The problem is clearly present and the developer needs to look at what is happening inside the trinket.

**Comment by bonfax4** [comment]
Hmm I can replicate this 100% of the time with hellfire. I e been dotting for like 10 mins without doing anything else and no issue so far.

**Comment by bonfax4** [comment]
I tried with Los and same issue as hellfire. Ot triggers icd with no buff when I dot, los, then try to proc again.

**Comment by bonfax4** [comment]
Yh proc chance of the trinket is also messed up. It's currently 100%, not 30%.
