### ISSUE TITLE
Uldum enterance quest "Easy Money" is not given

### ISSUE THREAD

**Issue by smhunter2** [gamefreedomgit/Maelstrom#4902]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I got the quest "Warchief's Command: Uldum!" at the board in Orgrimmar and complete the quest at Tanaris.
But, The NPC does not give the next quest "Easy Money" so all of Uldum quests are prevented.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Hermeleen** [comment]
aren't you in a group? same was happening to me until i realised it was because of that. i Was just in group out of habit, so that in bgs i most likely get the lead, for just role check and put marks on healers, because people don't do it. :D Also noticed that quests when in this group, were not giving kill objectives. For example on Tol Barad dailies, the villagers or spiders, when in group and the other person *i pressume* is offline, it doesn't give kills for objectives.

**Comment by smhunter2** [comment]
> aren't you in a group? same was happening to me until i realised it was because of that. i Was just in group out of habit, so that in bgs i most likely get the lead, for just role check and put marks on healers, because people don't do it. :D Also noticed that quests when in this group, were not giving kill objectives. For example on Tol Barad dailies, the villagers or spiders, when in group and the other person _i pressume_ is offline, it doesn't give kills for objectives.

I tried several times with your comment but nothing happen still now.
I dont have any party and party members.

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/b45e7d5b-778c-427c-b321-33b17d3538bf)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/eb843326-a733-4fa1-9b06-6e5fe32a5e36)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/bf987d60-1403-4517-b716-758f17ef5f00)

cannot reproduce
