### ISSUE TITLE
Paladin's Holy Light doesn't benefit from Attack Power and Spell Power 

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#4940]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I am a Ret Paladin and when I get the Crusade Talent and i have trinket strength procs the heals are always the same from Holy Light.

Check it out:

![withtrinket](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/521636dc-5d15-4099-8974-29fc9349d6bd)
![notrinket](https://github.com/gamefreedomgit/Maelstrom/assets/67479994/323336fa-1ea6-4f1a-aa4c-fc66ae3cb898)

The heal is identical.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Pornoodemon** [comment]
Paladins generally need to be rechecked from top to bottom.
The procs are too buggy, and most likely the formulas. .
I have observed more than once how paladins cannot approach the enemy during the entire battle, for example in a duel against frost mages or hunters, but at the same time they kill the enemy at range because of their bugs. without making a single blow in close combat .

**Comment by Renehadox** [comment]
> Paladins generally need to be rechecked from top to bottom. The procs are too buggy, and most likely the formulas. . I have observed more than once how paladins cannot approach the enemy during the entire battle, for example in a duel against frost mages or hunters, but at the same time they kill the enemy at range because of their bugs. without making a single blow in close combat . will be necessary recheck each talent step by step and spells And the problem most likely lies in the fact that those errors that give advantages, paladins do not report this to the bug tracker

What are you blabbering about?

Who kills enemy at range because of their bugs?

Get out of here and dont post in classes which do not concern you.

**Comment by Pornoodemon** [comment]
> > Паладинов вообще нужно перепроверять сверху вниз. Проки слишком глючные, и скорее всего формулы. . Я не раз наблюдал, как паладины не могут приблизиться к противнику в течение всего боя, например в поединке с морозными магами или охотниками, но при этом убивают противника на расстоянии из-за своих багов. не сделав ни одного удара в ближнем бою. нужно будет перепроверить каждый талант пошагово и заклинания. А проблема скорее всего в том, что те ошибки, которые дают преимущества, паладины не сообщают об этом в баг-трекер
> 
> О чем ты болтаешь?
> 
> Кто убивает врага на расстоянии из-за его жуков?
> 
> Уходите отсюда и не публикуйте сообщения на занятиях, которые вас не касаются.

I think that paladins will soon receive significant nerfs.
I just need to be lazy and write tickets.
For half a year, paladins issue tickets for only shortcomings, while ignoring bugs that give an advantage. X)

**Comment by Renehadox** [comment]
Need Information for what?

I just posted 2 proofs, lol.

**Comment by bonfax4** [comment]
Once you realize that most spells don't do a static amount of healing/damage and that dmg you see on tooltips is only the average, the sooner you'll realize that the scenario above can still be possible, so you'd need a bigger sample pool or at least figure out if the numbers can be close to eachother.

[Just in case you need proof that holy light has a range of healing.](https://web.archive.org/web/20120630113402/https://www.wowhead.com/spell=635)

![2cdc2abc9c96b01dd78d844b3d8bd6b5](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/7519605b-0e6a-4be1-aa04-2c1f8b047b52) 
![aea39909f38159c89c640b8add2be4d5](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/de1ee021-1cf5-485b-b8d8-0dc936b940e5)


Now you can do the math yourself @Renehadox and you can conclude how much extra healing you'd get from procs because you get 30% of AP as SP and holy light scales with 43.2% of spell power. Crusade is a 4x multiplier. Go ahead and do proper testing now.

**Comment by Hermeleen** [comment]
Well what i think happened here is that you got lucky with the non-proc one and unlucky with the extra strength one.  I tried normal holy light. was about 6.2k or so. That times 4 should be around 24k and it was. Normal 300% bonus holy light was around 24.5k. Then i pressed my pvp strength trinket and had the normal auto-proc pvp trinket too, and the crusade holy light was around 27-28k.

**Comment by Renehadox** [comment]
> Well what i think happened here is that you got lucky with the non-proc one and unlucky with the extra strength one. I tried normal holy light. was about 6.2k or so. That times 4 should be around 24k and it was. Normal 300% bonus holy light was around 24.5k. Then i pressed my pvp strength trinket and had the normal auto-proc pvp trinket too, and the crusade holy light was around 27-28k. OR perhaps there is something wrong with the trinket you have.

No because multiple times i tested it and the heal is the same, otherwise i wouldnt have reported it if i tested it only once, right? :D

**Comment by SexyPancake** [comment]
> > Well what i think happened here is that you got lucky with the non-proc one and unlucky with the extra strength one. I tried normal holy light. was about 6.2k or so. That times 4 should be around 24k and it was. Normal 300% bonus holy light was around 24.5k. Then i pressed my pvp strength trinket and had the normal auto-proc pvp trinket too, and the crusade holy light was around 27-28k. OR perhaps there is something wrong with the trinket you have.
> 
> No because multiple times i tested it and the heal is the same, otherwise i wouldnt have reported it if i tested it only once, right? :D

Just do a combat log on a dummy with only Holy Light under the trinket proc and another log with Holy Light casts without procs. 
That's the whole point of making github reports, you do all the job to ease the devs otherwise no one is going to do the job for you.....

**Comment by UltraNix** [comment]
Test done with 8k SpellPower and clean char - no auras/no modifiers, etc.

Without Crusader talent:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/97441e9b-cefb-4f5b-a7d7-b40d78895529)

With Crusader talent:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/67fab225-7ea1-43b0-9b4e-059cbb37a131)

Talent works okay.
