### ISSUE TITLE
Social Chat bug 

### ISSUE THREAD

**Issue by Renehadox** [gamefreedomgit/Maelstrom#5075]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

I am surprised nobody ever reported these bugs.

1. When a player is in arena or dungeon or in a party, and you try to invite him it says he is ignoring you which should say he is in group already.

2. When a player ignores you and you whisper me it doesn't show he ignores you, it should be written in red colors  " Afgann is ignoring you ".

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Revly** [comment]
This has already happened to me.

For example:

I am creating a raid, and the person I am going to invite is in Bg or solo instance (dungeon) he is in a difficulty of 5 heroic

And since I am creating the raid I have a difficulty of 5 normal, I want to invite him and it appears to me that he is ignoring me, to correct it I change my difficulty to 5 heroic and I can now invite him and it does not generate "ignore"

Has something like this happened to you?

**Comment by Renehadox** [comment]
Yes it has.

**Comment by Renehadox** [comment]
This is not fixed yet.

**Comment by Renehadox** [comment]
When a player ignores you and you whisper him it doesn't show he ignores you, it should be written in red colors " Afgann is ignoring you " for an example.

In the changelog it said it was fixed but its still not.

**Comment by UltraNix** [comment]
Fixed.
