### ISSUE TITLE
Arena rating roll back

### ISSUE THREAD

**Issue by Osckar12** [gamefreedomgit/Maelstrom#5223]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I have rolled back last 3 games
Ive reached 2.2 and bought elite weapons then logged off. When I log next time my rating was lower. I provide screenshots with my cr and elite weapons. Also my game history that shows I haven't played anymore games to lose any rating

**How to reproduce:**
I dont know

**How it should work:**
The rating should not be rolled back

**Database links:**
https://db.whitemane.org/pvp/maelstrom/solo/590762
![photo_2023-12-17_21-23-59](https://github.com/gamefreedomgit/Maelstrom/assets/154092525/cbc08fd2-d878-4083-9d0c-722e8a278b4d)
![photo_2023-12-17_21-24-03](https://github.com/gamefreedomgit/Maelstrom/assets/154092525/22e2e3bd-9918-451d-beb9-05dbe575cbb7)

**Comment by Sketish** [comment]
Hi, there was a rollback for all players due to bug

We've encountered a bug as a result of the recent update that has caused damage reduction abilities to not function as intended. This issue has been exploited by a significant number of players. In order to rectify this situation, we will be reverting arena ratings and MMR to their state before the update. ⚠️

Sorry for any inconvenience
