### ISSUE TITLE
pve weapons from DS Kaled the Elements of Death as example)

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#5550]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
pve weapons as example https://wowpedia.fandom.com/wiki/No%27Kaled,_the_Elements_of_Death, can proc from other hand

**How to reproduce:**
equip https://wowpedia.fandom.com/wiki/No%27Kaled,_the_Elements_of_Death in left hand, and to attack only right (main) hand

**How it should work:**
attack from other hand where other weapon, should not triggered proc

**Database links:**
https://wowpedia.fandom.com/wiki/No%27Kaled,_the_Elements_of_Death
https://wowpedia.fandom.com/wiki/Gurthalak,_Voice_of_the_Deeps (for fury warrior)
p.s. if weapon in left hand, all attacks from right hand should not triggered proc. And if weapon in right hand, all attacks from left hand should not triggred proc this weapon

**Comment by bonfax4** [comment]
Interesting stuff about no'kaled : 

For shaman : 

- Should proc off of autos/yellow melee attacks from the equipped weapon slot **if the attack is weapon based**. 

- Should proc off of Stormstrike debuff application ( Weirdly counted as a Main-hand melee attack ). This means 1 stormstrike while dual wielding should net you 3 separate chances to proc. Tested this trying trinkets such as fluid death to see if I got 3 stacks with 1 SS which didn't work, I'm assuming proc wont work either based on this.

- Should not proc off windfury or any weapon procs tbh ( rogue mastery also ). It currently does which is insanely broken if allowed in pvp. 
![0c6b533a272452a4c5b49d4ec22b0376](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/9c421c10-5e22-4111-b24f-1ba3c1289e96)

Proof: https://web.archive.org/web/20171227153113/http://enhsim.codeplex.com/workitem/8953 / https://www.mmo-champion.com/threads/1043892-ko-kaled-Question-Mh-or-Oh?highlight=No%27Kaled+windfury

- Unleash winds, it behaves as a [mh attack in terms of procs](https://web.archive.org/web/20121201100926/https://www.wowhead.com/spell=73680#comments). This one works, but i can't replicate the scenario where flametongue weapon ench on mh is procced like described in the comment. This prob means it only works now due to the current bug where it procs from any weapon.

Proof: https://web.archive.org/web/20171227153113/http://enhsim.codeplex.com/workitem/8953 / https://www.mmo-champion.com/threads/1043892-ko-kaled-Question-Mh-or-Oh?highlight=No%27Kaled+windfury

**Comment by bonfax4** [comment]
There seems to be an exception for few non weapon based warrior attacks that can trigger oh equipped or both weapons from all DS proc weapons ? Heroic leap, Blood Thirst, Thunderclap.

source : https://web.archive.org/web/20120506223007/http://www.landsoulcoaching.com/spreadsheet/changelog and simc
>Off-Handing Gurthalak should allow procs from Bloodthirst and Heroic Leap as well as melee swings. If two different versions are dual wielded, then each spell will have an equal chance to proc from Bloodthirst and Heroic Leap. Weapon based attacks such as swinging or raging blow or slam, etc should have one chance to proc from the appropriate hand. Removed chance to proc from Deep Wounds. These changes simultaneously apply to No'Kaled and Souldrinker for now until further notice.

Also if you equipped 2x gurths of the same version ( lfr,normal,hc), it only gave you one chance to proc with abilities. Was recommended for fury warriors to use different versions.

**Comment by mipanka** [comment]
> There seems to be an exception for few non weapon based warrior attacks that can trigger oh equipped or both weapons from all DS proc weapons ? Heroic leap, Blood Thirst, Thunderclap.
> 
> source : https://web.archive.org/web/20120506223007/http://www.landsoulcoaching.com/spreadsheet/changelog and simc
> 
> > Off-Handing Gurthalak should allow procs from Bloodthirst and Heroic Leap as well as melee swings. If two different versions are dual wielded, then each spell will have an equal chance to proc from Bloodthirst and Heroic Leap. Weapon based attacks such as swinging or raging blow or slam, etc should have one chance to proc from the appropriate hand. Removed chance to proc from Deep Wounds. These changes simultaneously apply to No'Kaled and Souldrinker for now until further notice.
> 
> Also if you equipped 2x gurths of the same version ( lfr,normal,hc), it only gave you one chance to proc with the above abilities i think. Was recommended for fury warriors to use different versions.

a little wrong: from ur first post
"For shaman :
Should proc off of autos/yellow melee attacks from the equipped weapon slot."

same for other wep, normal or hc doesnt matter, proc "tied" for hand where equiped

**Comment by UltraNix** [comment]
Fixed.

**Comment by bonfax4** [comment]
![12a202ea8cb497fcef812084cb9bc111](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/f0626205-01a8-4cee-af13-b2bb8390cbb5)

Double trigger from one swing ?

**Comment by bonfax4** [comment]
@Ultranix

**Comment by bonfax4** [comment]
Nvm
