### ISSUE TITLE
Mana void - YORR’SAHJ 

### ISSUE THREAD

**Issue by Roywz** [gamefreedomgit/Maelstrom#5572]
[//]: # https://www.wowhead.com/npc=56231/mana-void

**Description:**
Mana void is running to far away in the room and we can’t taunt or grip. When u are running to kill the mana void, he is start running far away. 

**How to reproduce:**
You need to make him to be around the boss, in the middle of the room and maybe to grip or taunt him to come near the boss.

**How it should work:**
The mana void needs to stay around the boss and not running far away from boss, needs to be at maximum 20-25 yards from where he was spawned.

**Database links:**
https://www.wowhead.com/npc=56231/mana-void

**Comment by UltraNix** [comment]
Jus tested and worked okay to me. Always was inside water circle.
@Roywz Please, provide screenshots or video of this bug on our server.

**Comment by Revly** [comment]
with Letal grip, should be attracted. But is immune can fix this

**Comment by Roywz** [comment]
This was happening at 25hc, the mana voie go too far away from boss.

**Comment by UltraNix** [comment]
@Roywz Show us.

**Comment by Polynomix** [comment]
furthest i've seen it go : https://clips.twitch.tv/ApatheticSucculentWormTF2John-FQhBtmHgwzEGPLGI

**Comment by xmrshoot** [comment]
@UltraNix ye the void sometimes geting too far away , and if its combined with blue , players who need mana must run with the adds to the void to get mana back , or if its red they take more damage , because they are away from boss and sometimes get killed , so netiehr fix void to stay close to the boss or increase mana detonation range , so healers can take mana back without moving to the void who is too far

**Comment by xmrshoot** [comment]
@UltraNix  ![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/db0cc6c2-3498-4cba-82e3-6886cf4ea60e)
dude do something we just wiped cuz void goes to narnia , he is out of water

**Comment by UltraNix** [comment]
Fixed.
