### ISSUE TITLE
Proove that Rathrak, the Poisonous Mind Proc still Bugged 

### ISSUE THREAD

**Issue by Dimonz10** [gamefreedomgit/Maelstrom#5674]
Description:
Hello the last report was closed without considering that there is issue on the Item , i have done more Research and i found a Video that show multiple time that the Rathrak Proc from Dot ticks too , https://www.youtube.com/watch?v=DXDIYOnubS4&t=134s please watch this with x0.25 speed you will see that the GCD still in charge and Rathrak proc from DOT tick and that happened multiple time in this video please watched it carefully with x0.25
so Rathrak Proc Still Bugged and not fixed yet @itsemmastone promote it as fixed but sadly its not
sometime it doesn't proc even once in a 3min+ arena how can we say it fixed !!!!!!!!!!!!!!!!!!!!
i tested it on single and multiple target i notice that it procs only from direct spells it should proc from DOT ticks as well
in arena somehow the proc % doesn't work at all i mean if its a 17 icd with 15% proc and multiple target in arena are dotted it should proc constantly .... here is the tests
My testing in Dummy Single target 10M dmg:

![rathraksingletar](https://github.com/gamefreedomgit/Maelstrom/assets/135762364/5fa40837-6a15-4973-977e-fb6661b9507c)
in Single Target Dummy it should do 5.5%-6.5% Total Damage
![rathrak-wowhead](https://github.com/gamefreedomgit/Maelstrom/assets/135762364/91bee10f-a43f-42a2-b3bb-826e0a856586)

https://ibb.co/smsCzNh
Multiple target for 10M dmg:

![rathrakmultipletar](https://github.com/gamefreedomgit/Maelstrom/assets/135762364/effd1992-4249-4ac6-96ec-a6432ceb43f4)
in a Multiple Target it should do 7.5%-8.5%
https://ibb.co/myRLN8R
Arena tests :
![rathrak1](https://github.com/gamefreedomgit/Maelstrom/assets/135762364/5dd8f0d5-8a38-4486-b933-08600496bc94)

https://ibb.co/0ZL7S0y

![rathrak2](https://github.com/gamefreedomgit/Maelstrom/assets/135762364/411212e2-ecbb-485c-8a51-06b70bc2d47f)

https://ibb.co/hy8N2h7

How to reproduce:

it has an ICD of 17 Sec and 15% chance ( as an Affliction warlock it should proc constantly cuz of the multi dots)

How it should work:

"This weapon's damage does NOT scale with anything other than spell damage and nature spell damage modifiers.
Even the tooltip on weapon changes, the tooltip on buff ([ Blast of Corruption](https://www.wowhead.com/spell=107831/blast-of-corruption)) always stays as "1742 damage...", BUT the real damage it does is what weapon tooltip says plus any spell damage modifier applied on mob (e.g: [(Spell #48506)](https://www.wowhead.com/spell=48506)).
Since [(Spell #77492)](https://www.wowhead.com/spell=77492) increases damage of your nature spells within[ Eclipse (Solar)](https://www.wowhead.com/spell=48517/eclipse-solar), it also increases this weapon's damage and this is shown in weapon's tooltip.
It DOES proc from DOT ticks.
It DOES proc from[ Soothe](https://www.wowhead.com/spell=2908/soothe) and [(Spell #770)](https://www.wowhead.com/spell=770).
It does NOT proc from any physical damage.
edit:
currently I am testing this weapon on bgs with 1492 mastery rating (+32% bonus dmg) and it seems it does 3572 (5519 crit) dmg per tick."

Database links:
https://www.wowhead.com/item=77195/rathrak-the-poisonous-mind#comments

**Comment by Dimonz10** [comment]
Please watch this https://youtu.be/DXDIYOnubS4?si=mEnwbAmRjazQR51M&t=135 with x 0.25 speed and if u watched it correctly you will see that inside the GCD it procs its means it procs from a dot ticks please watch it and rewatch it.

conclusion "it does proc from dot tics"

![rathraaak1](https://github.com/gamefreedomgit/Maelstrom/assets/135762364/58f90043-73ef-4dfc-badd-2c516cbd3b96)
in the same GCD
![rathraaaak11](https://github.com/gamefreedomgit/Maelstrom/assets/135762364/168a0cbb-bd61-46fc-8296-e90910337ff2)

**Comment by pizza-with-pineapple** [comment]
I don't think that is correct. 
In the video the dagger procs while the mage is on GCD due to ignite being applied. So while ignite is a DoT, its not the ticks that procs the dagger, but rather the application of ignite.

As stated earlier: 
It should not proc from DoT ticks,
but it should proc from spell casts, that includes direct damage, DoTs, spells that do Zero dmg such as purge / soothe / curse of elements / curse of tongues / fear / poly, etc.
It should NOT benefit from character stat ratings such as Spellpower, haste, crit. (the item itself has an inbuilt crit chance around 15-20%, it does NOT scale from character stats but it can benefit from debuffs on the target such as "shadow and flame" or "curse of elements")
It SHOULD benefit from +DMG modifiers such as Tricks of the trade / metamorphosis / curse of elements / earth and moon / ebonplague bringer / Eclipse / etc.

It literally says on the item: "your harmful spell casts". 
It does not say "when you deal damage".

DoT Ticks should NOT proc it.
However casting any harmful spell even if it does Zero damage or delayed damage SHOULD proc it.
Examples:
So while corruption is ticking on the target will not proc the dagger.
applying corruption can proc it, even if corruption does damage after ~3sec.
applying bane of doom can proc it even if it does damage after 15sec.
applying curse of elements can proc it even if does Zero damage.
applying unstable affliction can proc it even if it does no direct damage.
applying Fear can proc it even if it does Zero damage

ALL harmful spells can proc it. but DoT ticks cannot.

**Comment by Dimonz10** [comment]
You need to watch All the Procs in the Video (please with x0.25 speed) some times it applied inst after Direct Spell and sometime inside the GCD that prove the deference Between Direct Spell and Dot Ticks 
as u said ignite applied it it should proc directly when it applied and not at End of GCD ;) the guy is clearly play with no 1000 ms ping

**Comment by bonfax4** [comment]
Retail had a delay to most things tho. And there's also stuff that operate with a a invisible "travel time" iirc.

Look how no'khaled has a 0.8sec delay to the proc on the logs shown [here](https://web.archive.org/web/20171227153113/http://enhsim.codeplex.com/workitem/8953)

**Comment by UltraNix** [comment]
@Dimonz10 If you rewatch you can clearly see it's not from DoT.
On both screenshots you sent Ignite still have 3 sec and when the proc happened, the Ignite still did not tick.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/d71b934c-95b5-4a11-9b0e-63adb451289b)
The moment when proc is applied;

![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/a4d25d9c-a657-4c98-8559-bbff90586a98)
Ignite tick.

If procs from DoTs, then it would happend AFTER damage done by tick of Ignite.

It's rather from Ignite application (and consider that retail had delay as @bonfax4 said).

**Comment by SimonBpvp** [comment]
It’s currently proccing from polymorph 😑😑😑

**Comment by bonfax4** [comment]
> It’s currently proccing from polymorph 😑😑😑

Should according to comments, but it should ignore cc'd targets (breakable kind I assume ). Should hit everyone around the polymorph target.

**Comment by UltraNix** [comment]
No further info - closing.
