### ISSUE TITLE
Mu'ru never drops armor pieces

### ISSUE THREAD

**Issue by Daethalion** [gamefreedomgit/Maelstrom#5740]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Mu'ru in Sunwell Plateau has a bugged loot table.  Every week only rings, trinkets, and weapons are dropped.  Armor is never dropped.

**How to reproduce:**
Kill Mu'ru on Maelstrom, see loot.

**How it should work:**
Boss should drop from full loot table

**Database links:**

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/8de75e81-8a15-46a5-8843-2d80390d4212)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/398043/4a85c8a2-d238-4629-8b05-849e1119f79a)

it's your unluck, because I've tried 2 debug runs, both of them contained armor pieces.
Closing
