### ISSUE TITLE
light of echo and Holy Word: Sanctuary

### ISSUE THREAD

**Issue by Zaraelh** [gamefreedomgit/Maelstrom#5796]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description: Holy Priest's mastery is not being calculated correctly, nor is it accruing the remaining ticks to the next heal. 
Holy Word: Sanctuary is healing less than the description says and is not benefiting from healing modifiers**

**How to reproduce: 
Holy Priest's mastery : This is due to a rounding error and is not taking into account the remaining ticks for the next mastery upgrade after casting a heal in a row.
Holy Word: Sanctuary: Occurs when casting the spell**

**How it should work: 
Holy Priest's mastery : light of echo heals for 6 seconds, for example if light of echo heals 10% of 6000 = 600 each tick it will heal 100 every second, if only light of echo heals 2 ticks and another healing of 1000 is cast the remaining 4 ticks will go to add to the new updated mastery, that is, 1000 x 0.10 = 100; 4 ticks remaining from the previous light of echo 100 x 4 = 400; Now it adds (400+100)/ 6 = 83. But this calculation is failing, sometimes it heals less or it doesn't count a tick or two. 
In the image we can see that I fell and lost a amount of life, I cast a lightning healing and it healed me 17951 my mastery is 20% light of echo heals me 25%, 17951 x 0.25 = 4488, I didn't heal any tick then add the 6 ticks to the next healing, word serenity healed me 11789, 11789 x 0.25 = 2947; (4488+2947) / 6 = 7435 / 6 =1239, but as we can see I only healed 1125 and that's when everything started to go haywire. (https://postimg.cc/JyD4sf64) (https://postimg.cc/DSYwyvcM)
(https://web.archive.org/web/20120614091327/http://www.mmo-champion.com/threads/862352-Echo-of-Light-how-does-it-work)

Holy Word: Sanctuary : Holy Word: Sanctuary is healing less than what is in its description, it should not go below 767 pts but as seen in the image it heals 702, 696, it should only lower its healing when it heals more than 6 PCs, it acts as A radiance means that its healing decreases when it heals more than 6 characters, but at 6 characters it heals the same or more. It should be noted that the description in Spanish is poorly translated from English, the description in Spanish notes that it reduces the healing by 6 pts for each character within, but it is poorly translated, in reality it says it should say that it reduces the effectiveness of the healing on top of it. of 6 pjs. In patch 4.1 blizzar increased healing to Holy Word: Sanctuary by 35%. (https://wow.fandom.com/es/wiki/Parche_4.1.0#Sacerdotes) (https://postimg.cc/w3dGf3yc)
**

**Comment by bonfax4** [comment]
This was discussed a bit before. 

But it actually had weird behaviour in retail. The first echo of light application will always be a -1 tick in the calculation once refreshed (People's theory was that the initial application itself counted as a tick for some weird reason). Refreshes should work properly and split the ticks  bank/6  per tick and the 7th heal is always a "free tick" if it happens, it should not be affected by calculations.

Example with the numbers you linked : 

- ( [4488 - (4488/6) **<- application of buff equals minus one tick tick** ] + 11789 * 0.25 ) / 6 = (3740 + 2947) / 6 = **1115**. Now the new refreshed echo of light would heal 1115 for 7x times. The 7th last tick is a "free heal" if it went through. After this if you refresh it should work normally again in the way you described.

@UltraNix 

https://www.mmo-champion.com/threads/862352-Echo-of-Light-how-does-it-work?highlight=echo+of+light

Simc emulating this behaviour somewhat but Simc does not emulate 7th tick at all but it's clear on videos and the example listed on mmo that it does happen.

![317ed73193830865d161f4a35466e157](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/8e323478-336a-4731-a9c7-f2690f84897b)

My only problem is that its not clear what happens if you refresh between the 6th and 7th tick, since the 6th tick would empty the bank. It should prob work itself out if you always make application/refresh itself count as a tick for bank calculation purposes and the refreshes will always add up to 6 (7-1) this way and application always up to 5 (6-1).

**Comment by UltraNix** [comment]
@Zaraelh Echo of Light HoT calculations already discussed #5651
How it works for us: If 1. application, then the heal is divided by 6 ticks. Then if we have 2. application (refresh), then we add additional heal to existing hots minus 1 tick (according to simcraft @bonfax4 linked). If we have 3rd application (2nd refresh) then we add additional heal to existing hots without any tick substractions.
So using your situation:
17951 x 0.25 = 4488 / 6 ticks = 748 pet tick
11789 x 0.25 = 2947
Now we add only 5 ticks from prev application: 5 x 748 = 3740
3740 + 2947 = 6687 / 6 ticks = 1114 as @bonfax4 described

**Comment by UltraNix** [comment]
@bonfax4 About the 7th ticks:
If you refresh between 6th and 7th tick, then we still have 1 tick in bank + 6 new ticks.

**Comment by bonfax4** [comment]
Hmm but if you follow mmo champion calculations you can tell the 7th tick was never accounted for the bank. It was 6- tickamount after the 1st refresh that took 5

**Comment by UltraNix** [comment]
But then we are waisting the 7th tick not counted into the bank.

**Comment by bonfax4** [comment]
Blizzard shenanigans. Is it not possible to make the last tick simply not count for the bank ? I think this issue would also occur if you refreshed 1st echo between 5th and the 6th tick too now that I thought about it.

**Comment by UltraNix** [comment]
Of course I can make it, but I said - weirdo Blizzard :)

**Comment by UltraNix** [comment]
Fixed.
