### ISSUE TITLE
Matrix Restabilizer Abuse

### ISSUE THREAD

**Issue by Yarikels666** [gamefreedomgit/Maelstrom#5816]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
People can abuse this trinket https://www.wowhead.com/item=68994/matrix-restabilizer 
In raids

**How to reproduce:**
You need https://www.wowhead.com/item=46780/ogre-pinata in raids to abuse it, you can ungear ur char and hit Pinata and get proc of this trinket
Video proof: https://www.youtube.com/watch?v=1S1QuG1rhZg
I test on dummy, but it should work on a Pinata too, just need to wait 20-30 seconds when you gear this trinket and 1-2 hits = proc
**How it should work:**
The buff of trinket should not remain when you remove it, this is abuse

**Database links:**
https://www.wowhead.com/item=68994/matrix-restabilizer 
https://www.wowhead.com/item=46780/ogre-pinata

**Comment by bonfax4** [comment]
@UltraNix 

This is blizzlike regardless... Proc trinkets remain after swapping. Only the on-use ones disappear after you unequip. You can change the behavior but it won't be blizzlike. If anything the pinata should be removed or disabled in raids, since its not obtainable through normal means anyway. Not to mention that the pinata has a 30 min cd and low health and trinkets don't proc with 100% chance, not even that optimal.

**Comment by bonfax4** [comment]
They also have more health than they did in cata. Should be around 5k https://www.youtube.com/watch?v=a7RmrDFJRcI

**Comment by Yarikels666** [comment]
Whether you want to fix it or not, it doesn’t matter to me, I’m just bringing to your attention that people give more dps in raids this way

**Comment by UltraNix** [comment]
We are gonna stay with this exception for Matrix Destabilizer.
Pinata health - #5842
Fixed.
