### ISSUE TITLE
polymorph interaction with shapeshifted druids not working properly

### ISSUE THREAD

**Issue by dididadadududada** [gamefreedomgit/Maelstrom#5851]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
polymorph shouldn't be castable on druids that are shapeshifted. i know they are immune when it lands, but they shouldn't even be able to begin casting the spell when targetting a druid who is in shapeshift form. they're not humanoids

edit: its the same bug with hex, i can make another bug tracker if needed

**How to reproduce:**
have a druid shapeshift into travel form/cat/bear/tree, then have a mage cast polymorph

**How it should work:**
u shouldn't be able to begin to cast polymorph on a druid who is shapeshifted

**Database links:**

**Comment by Revly** [comment]
First of all, how is it working correctly: Because they are Humanoids, all players are humanoids
Second: if it is how you say it works, then it will not be possible to anticipate a Druid with polymorph who uses beast form and is going to cast spells removing his beast form and will be humanoid so that the polymorph affects him in terms of PVP

If anyone else knows about this there should be proof...

**Comment by SimonBpvp** [comment]
Wrong, you could always spam cast sheeps on the druid on cata, if i had time I think I could find a Ziqo mage video to prove it

**Comment by dididadadududada** [comment]
Sure take your time
