### ISSUE TITLE
Wartorn Bone-link Fetish DMG bugged

### ISSUE THREAD

**Issue by raller1006** [gamefreedomgit/Maelstrom#5871]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The trinket proc does not apply to resilience.

**How to reproduce:**
Duel a person using the trinket. Put on full resilience gear, and see the damage. Now try to put on a gear set with no resilience.

The damage is the same.

**How it should work:**
It should deal less damage to people having alot of resilience.

**Database links:**
Cata-twinhead.twinstar.cz/?item=78002

**Comment by raller1006** [comment]
Mipanadog (rogue) abusing the trinket somehow. 

Oneshotting people. Critting 60-80k with the trinket

**Comment by Pornoodemon** [comment]
It is worth highlighting that this problem is observed only among rogues.
Most likely it's not a matter of resilience, but the fact that a talent that reduces armor by 70% should only work for rogue attack(Which by the way is indicated in the talent tooltip), since it does not reduce armor in stat - this should not work for other attacks and spells.
If you look at it objectively, this introduces a crazy imbalance in pvp when this item instantly takes away 50-60% of the player’s HP when triggered.

**Comment by mipanka** [comment]
this rogues abused bug on dmg no more, I hope he was banned. Idk how, but some players abusing dmg bug and have 40-50k ambush hit.
p.s. its not my rogue

**Comment by UltraNix** [comment]
Damage done against target with 0 resilience:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/7cb98b86-2730-4f67-8920-d31fddfd6a94)

Damage done against target with 7000 resilience (58.9% reduction):
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/fdb5586e-05fe-498c-9095-78569fd0e151)
(9226 - 3850) / 9226 ~ 58,27
There is no bug here.

@Pornoodemon You mean Find Weakness? If so, then it works only for rogue attacks.

**Comment by Pornoodemon** [comment]
> Damage done against target with 0 resilience: ![image](https://private-user-images.githubusercontent.com/80540499/322499799-7cb98b86-2730-4f67-8920-d31fddfd6a94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxOTIyMTIsIm5iZiI6MTcxMzE5MTkxMiwicGF0aCI6Ii84MDU0MDQ5OS8zMjI0OTk3OTktN2NiOThiODYtMjczMC00ZjY3LTg5MjAtZDMxZmRkZmQ2YTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDE0MzgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwM2M2NjVhNjUzY2I4ODBmMzIyYjlhMDVmM2NjOTc1ZDM5OTFkYTk5NGM4MTI1Y2VhOTQzNGU3NzM1YmQ5MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jzhIgsUF_T2ewoGyuew9y40doMfQBg5_mLlMzCY8qsE)
> 
> Damage done against target with 7000 resilience (58.9% reduction): ![image](https://private-user-images.githubusercontent.com/80540499/322503037-fdb5586e-05fe-498c-9095-78569fd0e151.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxOTIyMTIsIm5iZiI6MTcxMzE5MTkxMiwicGF0aCI6Ii84MDU0MDQ5OS8zMjI1MDMwMzctZmRiNTU4NmUtMDVmZS00OThjLTkwOTUtNzg1NjlmZDBlMTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDE0MzgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMmZjMGY4OTJiMDRkZWFjY2Y4MjI0ODkyMzNhYmUyODJkNTEzZDUyODFhM2JlYWYyMDgxODEyOGFlYjY4ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gFif5Il6Y3OqQ7e4U-H43POyGgzIcdn_c_ABzSkHBfY) (9226 - 3850) / 9226 ~ 58,27 There is no bug here.
> 
> @Pornoodemon You mean Find Weakness? If so, then it works only for rogue attacks.

Apparently by mistake this also works for Bone link and Vial of Shadows.

**Comment by UltraNix** [comment]
I mean - it works for all attacks done by this rogue. Damage done by these trinkets is still done by rogue, so it's modified by the talent.

**Comment by Pornoodemon** [comment]
> I mean - it works for all attacks done by this rogue. Damage done by these trinkets is still done by rogue, so it's modified by the talent.

It is because of this that it seems to everyone that these trinkets ignore resilence .
The fact is that I have big doubts that this talent should work for third-party sources of damage other than the abilities of the robber himself. I searched a lot of information but could not find a single comment or topic where it was mentioned about some combination of this talent and these trinkets. In my opinion, if this could significantly increase the damage of these trinkets, it would most likely be described in every guide kata for robbers. But there is no mention of this anywhere at all, even on secondary sources and forums.
Well, therefore, I also cannot find information that this should not work, since most likely this talent did not work in this way. .

**Comment by Pornoodemon** [comment]
In addition, from the outside it looks like a bug when a trinket instantly takes away 40%-50% of HP.
And all this can be seen in contrast with any melee class for which this trinket works normally: Warior, DK, Pala.
But unfortunately, I cannot confirm this because I cannot find any  information at all about the operation of this keychain for robbers.

**Comment by Krysztal** [comment]
Up. Bug is still pressent.
![Zrzut ekranu 2024-09-22 212141](https://github.com/user-attachments/assets/449edf98-3e5b-483e-954f-ad19f07bd072)
![Zrzut ekranu 2024-09-22 205123](https://github.com/user-attachments/assets/b83243e6-14b4-477d-b120-3c9efb3085da)

**Comment by Pornoodemon** [comment]
> Вверх. Ошибка все еще присутствует. !
Эта  проблема только у рог и только в одной ветке но всеровно не достаточно пруфов чтобы там чтото поменять .
Я думаю что дело скорее всего в таланте который игнорит 70% брони для атак разбойника но нету пруфов должен он или не должен работать для этой трини  но сам факт увеличения урона происходит именно изза этого таланта.
Устойчивость работает для этой трини и это проверялось неоднократно

**Comment by Krysztal** [comment]
> @Krysztal Эта проблема только у ро и только в одной ветке но всеровно не достаточно пруфов чтобы там чтото поменять . Я думаю что дело скорее всего в таланте который игнорит 70% брони для атак разбойника но нету пруфов должен он или не должен работать для этой трини но сам факт увеличения урона происходит именно изза этого таланта. Устойчивость работает для этой трини и это проверялось неоднократно

Nope it is not working.
Pure damage from trinket is on burst is 25000 none crit. 
Crit would be ~50k.
I have 38.55% armory -70% from talent gives 11.565% reduction.
So 50000 dmg reduced by 11.565% = 44217 dmg
44217 dmg reduced by 45.5% resilience = 24098 dmg (crit)

From this numbers we see it is not working correctrly. Resilience does not apply for this trinket.

**Comment by Pornoodemon** [comment]
Просто сравни урон  с 0 устойчивости и с 45%  и сам  увидиш  что дело не в ресе
