### ISSUE TITLE
Dungeon: Utgarde Pinnacle and Childrens Week

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#5933]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**

Problem 1: Utgarde Pinnacle
1st boss: Svala Sorrowgrave - she move with me all over the map. I cant target her and i cant kill her.
3nd boss: Skadi the Ruthless - I cant use Harooon Launcher to kill him. I cant kill him. I cant continue till the end. 

Problem 2:
I need King Ymiron to compleate his achievement for "Hall to the King, Baby" Childrens week event.

This event must rewrite. Vendors in Orgrimmar missing like Grogg Skullsmasher, Alowicious Czervik, Rachelle Gothena from them i can buy Tigule's Strawberry Ice Cream.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
Grogg Skullsmasher -- didnt exist in CATA
Alowicious Czervik -- FIXED - he will have item
Rachelle Gothena - she is from Hallow End event

Utgarde Pinnacle bosses:

Svala - FIXED 80yrd range to reset fight
Skadi- you have to kill Harpooners and pick up harpoon from ground. When Skadi is in front of harpoons you can shoot, otherwise harpoon is blocked. 


fixed 05.05.2024 SERVER RESTART REQUIRED
