### ISSUE TITLE
Frost DK Hit(cap) bug

### ISSUE THREAD

**Issue by VioLanze** [gamefreedomgit/Maelstrom#5984]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
~12% hit rate on a frost DK with ~12% miss rate. how is that possible? o.O

**How to reproduce:**

**How it should work:**

8% hit rate should be near 0% missrate

**Database links:**

![wowbug](https://github.com/gamefreedomgit/Maelstrom/assets/97470768/aff0aa03-96eb-4ffb-929b-c4f745b223fe)
![wowbug1](https://github.com/gamefreedomgit/Maelstrom/assets/97470768/ed808be9-aa05-4680-b034-4b7b423f929b)

**Comment by SexyPancake** [comment]
I would suggest posting github report in english to avoid any confusion.

You are dual-wielding which doesn't cover white hits which you are referencing on details.
It's totally normal for you to have around 14.63% miss in that case since getting hit capped on the second line only involve yellow hits aka abilities.

**Comment by PanJanuszek** [comment]
"You have a base 8% miss-chance vs. a bossmob (+3 lvl) as a melee. Dualwielding adds another 19% miss but ONLY for your autoattacks (white hits). Because of Precision (+3% hit) you´ll get 5% (8-3) hit to cap your specials. More hit isnt bad, since you boost your autoattack-hits, therefore damage, therefore rage, but other stats become more important once you reach 8% hit."

Closing as not adefect
