### ISSUE TITLE
[Quest] A Yeti of Your Own not available

### ISSUE THREAD

**Issue by AngryEndUser** [gamefreedomgit/Maelstrom#6316]
**Description:**
NPC [Umi Rumplesnicker](https://www.wowhead.com/cata/npc=10305/umi-rumplesnicker) in Everlook should give the quest [A Yeti of Your Own](https://www.wowhead.com/cata/quest=8798/a-yeti-of-your-own) which awards a pet, after finishing the [Are We There, Yeti?](https://www.wowhead.com/cata/quest=28629/are-we-there-yeti) quest line, for characters with at least level 55, and engineering level of at least 250. She does not.

**How to reproduce:**

1. Reach level 55.
2. Reach Engineering level 250.
3. Finish [Are We There, Yeti?](https://www.wowhead.com/cata/quest=28629/are-we-there-yeti), then [The Perfect Horns](https://www.wowhead.com/cata/quest=28631/the-perfect-horns), and finally [Yetiphobia](https://www.wowhead.com/cata/quest=28722/yetiphobia).
4. Try to get the quest [A Yeti of Your Own](https://www.wowhead.com/cata/quest=8798/a-yeti-of-your-own) from [Umi Rumplesnicker](https://www.wowhead.com/cata/npc=10305/umi-rumplesnicker) in Everlook.

**How it should work:**
NPC should give the quest.

**Database links:**
- Umi Rumplesnicker: https://www.wowhead.com/cata/npc=10305/umi-rumplesnicker
- A Yeti of Your Own: https://www.wowhead.com/cata/quest=8798/a-yeti-of-your-own
- Are We There, Yeti?: https://www.wowhead.com/cata/quest=28629/are-we-there-yeti

**Comment by Afgann** [comment]
Currently quest is available after finishing https://www.wowhead.com/cata/quest=28722/yetiphobia.

https://www.wowhead.com/cata/quest=8798/a-yeti-of-your-own#comments:id=424438
This comment mentions questline instead of a quest.

https://www.wowhead.com/cata/quest=28629/are-we-there-yeti
And here the quest series is ended with Yetiphobia.

https://www.wowhead.com/cata/quest=8798/a-yeti-of-your-own#comments:id=1519485
Also this comment mentions Yetiphobia in the end, so i think it works fine currently.

**Comment by AngryEndUser** [comment]
It does not work.
In my original post I mentioned quest line, not quest. "The **quest line** leading up to the **quest** A Yeti of Your Own"

I did finish the quest line, including Yetiphobia (the quest you linked).
NPC does not award the A Yeti of Your Own.

**Comment by AngryEndUser** [comment]
Quest Completist output (Yetiphobia is completed):
![WoWScrnShot_112524_173247](https://github.com/user-attachments/assets/2acfbf6e-c8ca-41a7-9d4c-1027e0b3e353)

**Comment by Afgann** [comment]
fixed
